/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T22:43:54.631089992Z[GMT]
 * <br>
*  The generated test suite contains 5 tests
 * <br>
*  Covered targets: 17
 * <br>
*  Used time: 0h 2m 2s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_product_customer_others {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/product-variations/{id}
    */
    @Test @Timeout(60)
    public void test_0_getOnProduct_variReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTI0MDksImlhdCI6MTc3NDM5MjEwOSwianRpIjoiZjA5OGQyMzMtMmUxOS00YjZlLWE5ZjEtNWE3M2RkMzQzMDE3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijk1NzZkNDYzLTU4OGMtNDRmMi1hN2NiLTU1YTIxYWM5OGM5YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.WupIR687AoHWnOqEzfI63FkytP157Tr3IqiRBUZxscwN5ZLb9pwP4wgaw6O-gi9jhxvCGWcyzZH3bCPhctAbKhc4sVE5ISawtgCG-G-60nSbm1_bWJ1_txjons3PdwGV3oASfE4wL3sJkTwJB9riZkCo9dwTcT0EictM-dXu_iSwG3t9cCEQ5CdAWNaceDrjcywD3ITZ5qh2moXdOhrIlLyLDxhtGLMOpNd-mm1VmD4an_ByXEUmxY2Nzx8w7nlbHceLQkIjUJLOSzjCfMW2yFemtfY9hd-5ZIg9th3FydvbXn8B1oxYWg7Tmn5mIhAntVEflE7SvUmfL28cE9938w") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/product-variations/221")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 221 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/product-option-values/{productId}
    */
    @Test @Timeout(60)
    public void test_1_getOnProduct_option_valuReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTI0MDksImlhdCI6MTc3NDM5MjEwOSwianRpIjoiZjA5OGQyMzMtMmUxOS00YjZlLWE5ZjEtNWE3M2RkMzQzMDE3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijk1NzZkNDYzLTU4OGMtNDRmMi1hN2NiLTU1YTIxYWM5OGM5YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.WupIR687AoHWnOqEzfI63FkytP157Tr3IqiRBUZxscwN5ZLb9pwP4wgaw6O-gi9jhxvCGWcyzZH3bCPhctAbKhc4sVE5ISawtgCG-G-60nSbm1_bWJ1_txjons3PdwGV3oASfE4wL3sJkTwJB9riZkCo9dwTcT0EictM-dXu_iSwG3t9cCEQ5CdAWNaceDrjcywD3ITZ5qh2moXdOhrIlLyLDxhtGLMOpNd-mm1VmD4an_ByXEUmxY2Nzx8w7nlbHceLQkIjUJLOSzjCfMW2yFemtfY9hd-5ZIg9th3FydvbXn8B1oxYWg7Tmn5mIhAntVEflE7SvUmfL28cE9938w") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/product-option-values/407")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 407 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/:-1/product/v3/api-docs
    */
    @Test @Timeout(60)
    public void test_2_getOnApi_docsReturns404() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/:-1/product/v3/api-docs")
                .then()
                .statusCode(404);
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/product-option-combinations/{productId}/values
    */
    @Test @Timeout(60)
    public void test_3_getOnValuesReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTI0MDksImlhdCI6MTc3NDM5MjEwOSwianRpIjoiZjA5OGQyMzMtMmUxOS00YjZlLWE5ZjEtNWE3M2RkMzQzMDE3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijk1NzZkNDYzLTU4OGMtNDRmMi1hN2NiLTU1YTIxYWM5OGM5YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.WupIR687AoHWnOqEzfI63FkytP157Tr3IqiRBUZxscwN5ZLb9pwP4wgaw6O-gi9jhxvCGWcyzZH3bCPhctAbKhc4sVE5ISawtgCG-G-60nSbm1_bWJ1_txjons3PdwGV3oASfE4wL3sJkTwJB9riZkCo9dwTcT0EictM-dXu_iSwG3t9cCEQ5CdAWNaceDrjcywD3ITZ5qh2moXdOhrIlLyLDxhtGLMOpNd-mm1VmD4an_ByXEUmxY2Nzx8w7nlbHceLQkIjUJLOSzjCfMW2yFemtfY9hd-5ZIg9th3FydvbXn8B1oxYWg7Tmn5mIhAntVEflE7SvUmfL28cE9938w") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/product-option-combinations/457/values")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 457 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/products/related-products/{id}
    */
    @Test @Timeout(60)
    public void test_4_getOnRelated_productReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTI0MDksImlhdCI6MTc3NDM5MjEwOSwianRpIjoiZjA5OGQyMzMtMmUxOS00YjZlLWE5ZjEtNWE3M2RkMzQzMDE3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijk1NzZkNDYzLTU4OGMtNDRmMi1hN2NiLTU1YTIxYWM5OGM5YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.WupIR687AoHWnOqEzfI63FkytP157Tr3IqiRBUZxscwN5ZLb9pwP4wgaw6O-gi9jhxvCGWcyzZH3bCPhctAbKhc4sVE5ISawtgCG-G-60nSbm1_bWJ1_txjons3PdwGV3oASfE4wL3sJkTwJB9riZkCo9dwTcT0EictM-dXu_iSwG3t9cCEQ5CdAWNaceDrjcywD3ITZ5qh2moXdOhrIlLyLDxhtGLMOpNd-mm1VmD4an_ByXEUmxY2Nzx8w7nlbHceLQkIjUJLOSzjCfMW2yFemtfY9hd-5ZIg9th3FydvbXn8B1oxYWg7Tmn5mIhAntVEflE7SvUmfL28cE9938w") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/products/related-products/1457882066?pageSize=602")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 1457882066 is not found"))
                .body("'fieldErrors'", nullValue());
    }


}
