/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T05:02:34.155385120Z[GMT]
 * <br>
*  The generated test suite contains 4 tests
 * <br>
*  Covered targets: 52
 * <br>
*  Used time: 0h 1m 42s
 * <br>
*  Needed budget for current results: 71%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_promotion_admin_only_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/promotion/backoffice/promotions
    */
    @Test @Timeout(60)
    public void test_0_getOnBackofficePromotionsWithQueryParamsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTUxNDksImlhdCI6MTc3NDQxNDg0OSwianRpIjoiZDM3NjU3YTktZGJlOS00MjVkLThhYjktNzUyNTliYmZhOGFjIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4ZjA5OGViLTQ1OGUtNDMxZi1iNWRhLTE3ZGFmYzhjZjE4NyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.TM73MOHS60T55i0BgN35zQgcsYZvVqc_mRfKO6tf-_de85DXn--mD8Ne-t6JG1yEtokwcd-2bUrMoD8pPg6u37UxvOUk0GOwb6BvQ8qadbgLCBkQ9bgmv1sgrLiKI4MecFBaqdSAXPbLcsoRUNdzctlZ3Yi3BKV-wrl9Q8Gur5IYFhLDV20aRVF9hOiZjdFj3A-JnJi3btT1R8FjWGuZzX3A18dpXKc65zWalB96XbcJcp07c4xgpjo88JD5sQx-Zi3DxScfdFOhfVurRzq1J5VYQH5lg0xKI2UBTaY9F0IrxogzNJvkO1MHP7ZSP6Gjyd1dn1_ezt0xjewxf8brnQ") // Fixed Headers
                .get(baseUrlOfSut + "/promotion/backoffice/promotions?" + 
                    "promotionName=yPc7H5kukGTIi9Wa&" + 
                    "startDate=2029-12-21T16%3A35%3A22.715Z")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'promotionDetailVmList'.size()", equalTo(0))
                .body("'pageNo'", numberMatches(0))
                .body("'pageSize'", numberMatches(5))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/promotion/backoffice/promotions
    */
    @Test @Timeout(60)
    public void test_1_getOnBackofficePromotionsWithQueryParamReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTUxNDksImlhdCI6MTc3NDQxNDg0OSwianRpIjoiZDM3NjU3YTktZGJlOS00MjVkLThhYjktNzUyNTliYmZhOGFjIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4ZjA5OGViLTQ1OGUtNDMxZi1iNWRhLTE3ZGFmYzhjZjE4NyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.TM73MOHS60T55i0BgN35zQgcsYZvVqc_mRfKO6tf-_de85DXn--mD8Ne-t6JG1yEtokwcd-2bUrMoD8pPg6u37UxvOUk0GOwb6BvQ8qadbgLCBkQ9bgmv1sgrLiKI4MecFBaqdSAXPbLcsoRUNdzctlZ3Yi3BKV-wrl9Q8Gur5IYFhLDV20aRVF9hOiZjdFj3A-JnJi3btT1R8FjWGuZzX3A18dpXKc65zWalB96XbcJcp07c4xgpjo88JD5sQx-Zi3DxScfdFOhfVurRzq1J5VYQH5lg0xKI2UBTaY9F0IrxogzNJvkO1MHP7ZSP6Gjyd1dn1_ezt0xjewxf8brnQ") // Fixed Headers
                .get(baseUrlOfSut + "/promotion/backoffice/promotions?pageSize=5")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'promotionDetailVmList'.size()", equalTo(0))
                .body("'pageNo'", numberMatches(0))
                .body("'pageSize'", numberMatches(5))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) POST:/promotion/storefront/promotions/updateUsage
    */
    @Test @Timeout(60)
    public void test_2_postOnUpdateUsageReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTUxNDksImlhdCI6MTc3NDQxNDg0OSwianRpIjoiZDM3NjU3YTktZGJlOS00MjVkLThhYjktNzUyNTliYmZhOGFjIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4ZjA5OGViLTQ1OGUtNDMxZi1iNWRhLTE3ZGFmYzhjZjE4NyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.TM73MOHS60T55i0BgN35zQgcsYZvVqc_mRfKO6tf-_de85DXn--mD8Ne-t6JG1yEtokwcd-2bUrMoD8pPg6u37UxvOUk0GOwb6BvQ8qadbgLCBkQ9bgmv1sgrLiKI4MecFBaqdSAXPbLcsoRUNdzctlZ3Yi3BKV-wrl9Q8Gur5IYFhLDV20aRVF9hOiZjdFj3A-JnJi3btT1R8FjWGuZzX3A18dpXKc65zWalB96XbcJcp07c4xgpjo88JD5sQx-Zi3DxScfdFOhfVurRzq1J5VYQH5lg0xKI2UBTaY9F0IrxogzNJvkO1MHP7ZSP6Gjyd1dn1_ezt0xjewxf8brnQ") // Fixed Headers
                .contentType("application/json")
                .body(" [ ] ")
                .post(baseUrlOfSut + "/promotion/storefront/promotions/updateUsage")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) DELETE:/promotion/backoffice/promotions/{promotionId}
    */
    @Test @Timeout(60)
    public void test_3_deleteOnPromotReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTUxNDksImlhdCI6MTc3NDQxNDg0OSwianRpIjoiZDM3NjU3YTktZGJlOS00MjVkLThhYjktNzUyNTliYmZhOGFjIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjE4ZjA5OGViLTQ1OGUtNDMxZi1iNWRhLTE3ZGFmYzhjZjE4NyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.TM73MOHS60T55i0BgN35zQgcsYZvVqc_mRfKO6tf-_de85DXn--mD8Ne-t6JG1yEtokwcd-2bUrMoD8pPg6u37UxvOUk0GOwb6BvQ8qadbgLCBkQ9bgmv1sgrLiKI4MecFBaqdSAXPbLcsoRUNdzctlZ3Yi3BKV-wrl9Q8Gur5IYFhLDV20aRVF9hOiZjdFj3A-JnJi3btT1R8FjWGuZzX3A18dpXKc65zWalB96XbcJcp07c4xgpjo88JD5sQx-Zi3DxScfdFOhfVurRzq1J5VYQH5lg0xKI2UBTaY9F0IrxogzNJvkO1MHP7ZSP6Gjyd1dn1_ezt0xjewxf8brnQ") // Fixed Headers
                .delete(baseUrlOfSut + "/promotion/backoffice/promotions/904")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
