/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T22:33:25.398265767Z[GMT]
 * <br>
*  The generated test suite contains 5 tests
 * <br>
*  Covered targets: 78
 * <br>
*  Used time: 0h 1m 46s
 * <br>
*  Needed budget for current results: 76%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_order_admin_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/order/backoffice/orders
    */
    @Test @Timeout(60)
    public void test_0_getOnOrdersReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE3OTcsImlhdCI6MTc3NDM5MTQ5NywianRpIjoiODAyM2IyNWEtNThlOC00MDBmLTgyYjAtYTAyNWQ5YjlkZTU5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijg1ZWYwYmEzLTVmMmItNDkzNi1iYTgyLWY0MTM0MGNmOTNmNyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.dZHc5EDwDVjlehYoQn8Bxee_uxprltSwDkl_9najwSda7OS_EwgPZlkxaZSK4z8nKwip5JlbHMbW-PmrzzdcpCbSzXCJ7coZc5r4uZ08e4W6VoG7kMslh-ERPN1bgovt50glLj_eZVKkxM20SFoCCjIFqIZUmWDlCGvqHxEClZ1BcXY5R0Uf1FphRpPbshmrb6waAp1b82tfLVtxaNPeI4MDZl72S5gO7vxdm-3qXHZOOY6qimIItZzMpVETdGspkTTgXBJMtgyvB-JO08XbRZMhn7lf_QtOfF7ZPIuNzi8-5fB5yF7Di2_so-MkWm4b---jlLh6r_zzmId1cXR1wg") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdFrom=1940-09-28T10%3A35%3A35Z&" + 
                    "createdTo=2034-07-01T04%3A27%3A20.774%2B10%3A41&" + 
                    "email=4MXBri&" + 
                    "pageSize=91")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'orderList'", nullValue())
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/order/storefront/orders/completed
    */
    @Test @Timeout(60)
    public void test_1_getOnCompletedReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE3OTcsImlhdCI6MTc3NDM5MTQ5NywianRpIjoiODAyM2IyNWEtNThlOC00MDBmLTgyYjAtYTAyNWQ5YjlkZTU5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijg1ZWYwYmEzLTVmMmItNDkzNi1iYTgyLWY0MTM0MGNmOTNmNyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.dZHc5EDwDVjlehYoQn8Bxee_uxprltSwDkl_9najwSda7OS_EwgPZlkxaZSK4z8nKwip5JlbHMbW-PmrzzdcpCbSzXCJ7coZc5r4uZ08e4W6VoG7kMslh-ERPN1bgovt50glLj_eZVKkxM20SFoCCjIFqIZUmWDlCGvqHxEClZ1BcXY5R0Uf1FphRpPbshmrb6waAp1b82tfLVtxaNPeI4MDZl72S5gO7vxdm-3qXHZOOY6qimIItZzMpVETdGspkTTgXBJMtgyvB-JO08XbRZMhn7lf_QtOfF7ZPIuNzi8-5fB5yF7Di2_so-MkWm4b---jlLh6r_zzmId1cXR1wg") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/orders/completed?productId=1")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'isPresent'", equalTo(false));
    }
    
    
    /**
    * Calls:
    * (200) GET:/order/storefront/orders/my-orders
    */
    @Test @Timeout(60)
    public void test_2_getOnMy_ordersReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE3OTcsImlhdCI6MTc3NDM5MTQ5NywianRpIjoiODAyM2IyNWEtNThlOC00MDBmLTgyYjAtYTAyNWQ5YjlkZTU5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijg1ZWYwYmEzLTVmMmItNDkzNi1iYTgyLWY0MTM0MGNmOTNmNyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.dZHc5EDwDVjlehYoQn8Bxee_uxprltSwDkl_9najwSda7OS_EwgPZlkxaZSK4z8nKwip5JlbHMbW-PmrzzdcpCbSzXCJ7coZc5r4uZ08e4W6VoG7kMslh-ERPN1bgovt50glLj_eZVKkxM20SFoCCjIFqIZUmWDlCGvqHxEClZ1BcXY5R0Uf1FphRpPbshmrb6waAp1b82tfLVtxaNPeI4MDZl72S5gO7vxdm-3qXHZOOY6qimIItZzMpVETdGspkTTgXBJMtgyvB-JO08XbRZMhn7lf_QtOfF7ZPIuNzi8-5fB5yF7Di2_so-MkWm4b---jlLh6r_zzmId1cXR1wg") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/orders/my-orders?productName=jXblizcbIo9wPOP")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/order/backoffice/orders/latest/{count}
    */
    @Test @Timeout(60)
    public void test_3_getOnLatestReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE3OTcsImlhdCI6MTc3NDM5MTQ5NywianRpIjoiODAyM2IyNWEtNThlOC00MDBmLTgyYjAtYTAyNWQ5YjlkZTU5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijg1ZWYwYmEzLTVmMmItNDkzNi1iYTgyLWY0MTM0MGNmOTNmNyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.dZHc5EDwDVjlehYoQn8Bxee_uxprltSwDkl_9najwSda7OS_EwgPZlkxaZSK4z8nKwip5JlbHMbW-PmrzzdcpCbSzXCJ7coZc5r4uZ08e4W6VoG7kMslh-ERPN1bgovt50glLj_eZVKkxM20SFoCCjIFqIZUmWDlCGvqHxEClZ1BcXY5R0Uf1FphRpPbshmrb6waAp1b82tfLVtxaNPeI4MDZl72S5gO7vxdm-3qXHZOOY6qimIItZzMpVETdGspkTTgXBJMtgyvB-JO08XbRZMhn7lf_QtOfF7ZPIuNzi8-5fB5yF7Di2_so-MkWm4b---jlLh6r_zzmId1cXR1wg") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders/latest/-1999239595")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/order/backoffice/orders/latest/{count}
    */
    @Test @Timeout(60)
    public void test_4_getOnLatestReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE3OTcsImlhdCI6MTc3NDM5MTQ5NywianRpIjoiODAyM2IyNWEtNThlOC00MDBmLTgyYjAtYTAyNWQ5YjlkZTU5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijg1ZWYwYmEzLTVmMmItNDkzNi1iYTgyLWY0MTM0MGNmOTNmNyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.dZHc5EDwDVjlehYoQn8Bxee_uxprltSwDkl_9najwSda7OS_EwgPZlkxaZSK4z8nKwip5JlbHMbW-PmrzzdcpCbSzXCJ7coZc5r4uZ08e4W6VoG7kMslh-ERPN1bgovt50glLj_eZVKkxM20SFoCCjIFqIZUmWDlCGvqHxEClZ1BcXY5R0Uf1FphRpPbshmrb6waAp1b82tfLVtxaNPeI4MDZl72S5gO7vxdm-3qXHZOOY6qimIItZzMpVETdGspkTTgXBJMtgyvB-JO08XbRZMhn7lf_QtOfF7ZPIuNzi8-5fB5yF7Di2_so-MkWm4b---jlLh6r_zzmId1cXR1wg") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders/latest/978")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }


}
