/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T04:59:14.511119882Z[GMT]
 * <br>
*  The generated test suite contains 3 tests
 * <br>
*  Covered targets: 20
 * <br>
*  Used time: 0h 2m 9s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_inventory_admin_only_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/inventory/backoffice/warehouses
    */
    @Test @Timeout(60)
    public void test_0_getOnWarehousesReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ5MjEsImlhdCI6MTc3NDQxNDYyMSwianRpIjoiMzZmNWRmYmItMjJlMC00MWM4LWEzYjQtNWExM2FkMWE5YzY3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjIyMDBmNGQ1LWUwYzUtNDhjNC1hN2JhLTMyMWY4ZDFkOTUyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.cqU5UJVoXL-g96SlT2qm2qF0kxkPsmFLIYoSePbvkGWNSlxiW1TtEimZCpE35YbAWRaGc2NZ-Nql4087eHs3GyB2hs6BVwdVdnICjmNlYZrnixVuGBfl_GfT5ZEXv7GkgvHObizELMoZmKzZ7xw_k0Si70TGZ25czOL-DXEady6uUj8LfaxZyI6emGpxYR3Et8S07ZYdhB27nYp6TW_17lqzODPBg5bvr-YnEsynL6Et6tjzPtxgl1Ds7AbGpQBa3QnhAb_ByU3Lo1G-wCRgcYfHYlcF5FxP6K_4inqUpvtDwu4l9Mww10qM3zjep3USm_dTs5-6ME8jkVwF8snRjg") // Fixed Headers
                .get(baseUrlOfSut + "/inventory/backoffice/warehouses")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) PUT:/inventory/backoffice/stocks
    */
    @Test @Timeout(60)
    public void test_1_putOnStocksReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ5MjEsImlhdCI6MTc3NDQxNDYyMSwianRpIjoiMzZmNWRmYmItMjJlMC00MWM4LWEzYjQtNWExM2FkMWE5YzY3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjIyMDBmNGQ1LWUwYzUtNDhjNC1hN2JhLTMyMWY4ZDFkOTUyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.cqU5UJVoXL-g96SlT2qm2qF0kxkPsmFLIYoSePbvkGWNSlxiW1TtEimZCpE35YbAWRaGc2NZ-Nql4087eHs3GyB2hs6BVwdVdnICjmNlYZrnixVuGBfl_GfT5ZEXv7GkgvHObizELMoZmKzZ7xw_k0Si70TGZ25czOL-DXEady6uUj8LfaxZyI6emGpxYR3Et8S07ZYdhB27nYp6TW_17lqzODPBg5bvr-YnEsynL6Et6tjzPtxgl1Ds7AbGpQBa3QnhAb_ByU3Lo1G-wCRgcYfHYlcF5FxP6K_4inqUpvtDwu4l9Mww10qM3zjep3USm_dTs5-6ME8jkVwF8snRjg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"stockQuantityList\" : [ { " + 
                    " \"stockId\" : 566, " + 
                    " \"quantity\" : 454 " + 
                    " }, { " + 
                    " \"stockId\" : 131, " + 
                    " \"note\" : \"X_Of1SkT0X1j\" " + 
                    " }, { " + 
                    " \"stockId\" : 157, " + 
                    " \"note\" : \"2FRG3Q\" " + 
                    " } ] " + 
                    " } ")
                .put(baseUrlOfSut + "/inventory/backoffice/stocks")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) GET:/inventory/backoffice/warehouses/paging
    */
    @Test @Timeout(60)
    public void test_2_getOnPagingReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ5MjEsImlhdCI6MTc3NDQxNDYyMSwianRpIjoiMzZmNWRmYmItMjJlMC00MWM4LWEzYjQtNWExM2FkMWE5YzY3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjIyMDBmNGQ1LWUwYzUtNDhjNC1hN2JhLTMyMWY4ZDFkOTUyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.cqU5UJVoXL-g96SlT2qm2qF0kxkPsmFLIYoSePbvkGWNSlxiW1TtEimZCpE35YbAWRaGc2NZ-Nql4087eHs3GyB2hs6BVwdVdnICjmNlYZrnixVuGBfl_GfT5ZEXv7GkgvHObizELMoZmKzZ7xw_k0Si70TGZ25czOL-DXEady6uUj8LfaxZyI6emGpxYR3Et8S07ZYdhB27nYp6TW_17lqzODPBg5bvr-YnEsynL6Et6tjzPtxgl1Ds7AbGpQBa3QnhAb_ByU3Lo1G-wCRgcYfHYlcF5FxP6K_4inqUpvtDwu4l9Mww10qM3zjep3USm_dTs5-6ME8jkVwF8snRjg") // Fixed Headers
                .get(baseUrlOfSut + "/inventory/backoffice/warehouses/paging?pageNo=25")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'warehouseContent'.size()", equalTo(0))
                .body("'pageNo'", numberMatches(25))
                .body("'pageSize'", numberMatches(10))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0))
                .body("'isLast'", equalTo(true));
    }


}
