backend:
  replicaCount: 1
  image:
    repository: danzgne/yas-inventory
    tag: main

  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: false
