baseUrl: /swagger-ui
urls: "[{ url: 'http://backoffice.dev.yas.local.com/product/v3/api-docs', name: 'Product' },
      { url: 'http://backoffice.dev.yas.local.com/media/v3/api-docs', name: 'Media' },
      { url: 'http://backoffice.dev.yas.local.com/customer/v3/api-docs', name: 'Customer' },
      { url: 'http://backoffice.dev.yas.local.com/cart/v3/api-docs', name: 'Cart' },
      { url: 'http://backoffice.dev.yas.local.com/order/v3/api-docs', name: 'Order' },
      { url: 'http://backoffice.dev.yas.local.com/inventory/v3/api-docs', name: 'Inventory' },
      { url: 'http://backoffice.dev.yas.local.com/tax/v3/api-docs', name: 'Tax' },
      { url: 'http://backoffice.dev.yas.local.com/search/v3/api-docs', name: 'Search' },
      { url: 'http://backoffice.dev.yas.local.com/sampledata/v3/api-docs', name: 'Sampledata' }]"

ingress:
  enabled: true
  className: "traefik"
  host: api.dev.yas.local.com
  hosts:
    - host: api.dev.yas.local.com
      paths:
        - path: /swagger-ui
          pathType: ImplementationSpecific
        - path: /
          pathType: ImplementationSpecific
