{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend.serviceAccountName" . }}
  # 🛠️ BỔ SUNG KHỐI ANNOTATIONS NÀY ĐỂ ĐÓNG DẤU CHÍNH CHỦ HELM
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  # 🛠️ BỔ SUNG LABEL MANAGED-BY VÀO ĐÂY
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    {{- include "backend.labels" . | nindent 4 }}
{{- end }}