{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend.serviceAccountName" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    # 🌟 CỜ LỆNH QUYẾT ĐỊNH: Ép Helm bỏ qua việc check metadata ownership nếu tài nguyên đã tồn tại sẵn
    helm.sh/resource-policy: keep
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}