services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: yas-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - yas-network

volumes:
  jenkins_home:

networks:
  yas-network:
    external: true
