title = "Gitleaks configuration for YAS Project"

[extend]
useDefault = true

[allowlist]
description = "Whitelist triệt để cho đồ án YAS - Clean 8 lỗi cuối"

paths = [
    '''target''',
    '''automation-ui''',
    '''src/test/resources''',
    '''test-classes''',
    '''realm-export\.json''',
    '''test-realm\.json''',
    '''keycloak-yas-realm-import\.yaml''',
    '''values\.yaml''',
    '''\.gitleaksignore''',
    '''k8s/deploy/.*''',
    '''README\.md''',
    '''gitleaks-report\.json'''
]

regexes = [
    '''invalidPassword''',
    '''[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}''',
    '''NKAr3rnjwm9jlakgKpelukZGFaHYqIWE''',
    '''TVacLC0cQ8tiiEKiTVerTb2YvwQ1TRJF''',
    '''ZrU9I0q2uXBglBnmvyJdkl1lf0ncr8tn''',
    '''[a-zA-Z0-9]{30,40}''',
    '''LarUmB3A49NTg9YmgW4='''
]