sonar.projectKey=JuzHarii_yas
sonar.organization=juzharii
sonar.host.url=https://sonarcloud.io
sonar.projectName=yas
sonar.sources=backoffice,backoffice-bff,cart,common-library,customer,delivery,inventory,location,media,order,payment,payment-paypal,product,promotion,rating,recommendation,sampledata,search,storefront,storefront-bff,tax,webhook
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/dist/**,**/build/**,**/target/generated-sources/**,**/src/test/**,**/src/it/**,**/*.min.js,automation-ui/**,checkstyle/**,deployment/**,docker/**,docs/**,k8s/**,kafka/**,nginx/**,screenshots/**,scripts/**,tempo-data/**
sonar.java.binaries=**/target/classes
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
