/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T22:28:26.170268332Z[GMT]
 * <br>
*  The generated test suite contains 3 tests
 * <br>
*  Covered targets: 12
 * <br>
*  Used time: 0h 1m 47s
 * <br>
*  Needed budget for current results: 81%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_customer_admin_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/customer/storefront/user-address
    */
    @Test @Timeout(60)
    public void test_0_getOnUser_addressReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE0OTYsImlhdCI6MTc3NDM5MTE5NiwianRpIjoiZDJkMmU4ODAtNTZkZi00MmU1LWEyNGItMmYwODY5M2UzOGVlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjQyNDgyMmE0LWEwNjgtNGE4Mi04OTBjLTk1YTE4ZGI5NDE5MyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.iXQ04MGFVbVhErSDJG7ksTW7s5YzVXL5LricG0v9X3D6vLPH4hnyAlVMs-4EpLCZSJwSN7aHg39uwOgKfg8uufUghkWPlkKyHCgpgv0w4KBXKV-7cbwvUljMFQaB0sdpE3gYMfl-_FLdxQP_OGBmSkOLOkHJVJIfz_ndkQWRGUR2o5dVV8-XpbMr2WqzHYdyDQnm0QpMULXOZneKcbuKnlJWeWTjEVVa_Jdh4VHpoAKHLP9Tx--C2YX8l94OrmmJtTZLBvsrR-tI21_JXMISg8mngxoeBsTWC-OjTSjxl6oRS5mNkn3-I_ad6tLh52vYBK59Wg1hioWiclCuRiUWTg") // Fixed Headers
                .get(baseUrlOfSut + "/customer/storefront/user-address")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer/storefront/customer/profile
    */
    @Test @Timeout(60)
    public void test_1_getOnProfileReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE0OTYsImlhdCI6MTc3NDM5MTE5NiwianRpIjoiZDJkMmU4ODAtNTZkZi00MmU1LWEyNGItMmYwODY5M2UzOGVlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjQyNDgyMmE0LWEwNjgtNGE4Mi04OTBjLTk1YTE4ZGI5NDE5MyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.iXQ04MGFVbVhErSDJG7ksTW7s5YzVXL5LricG0v9X3D6vLPH4hnyAlVMs-4EpLCZSJwSN7aHg39uwOgKfg8uufUghkWPlkKyHCgpgv0w4KBXKV-7cbwvUljMFQaB0sdpE3gYMfl-_FLdxQP_OGBmSkOLOkHJVJIfz_ndkQWRGUR2o5dVV8-XpbMr2WqzHYdyDQnm0QpMULXOZneKcbuKnlJWeWTjEVVa_Jdh4VHpoAKHLP9Tx--C2YX8l94OrmmJtTZLBvsrR-tI21_JXMISg8mngxoeBsTWC-OjTSjxl6oRS5mNkn3-I_ad6tLh52vYBK59Wg1hioWiclCuRiUWTg") // Fixed Headers
                .get(baseUrlOfSut + "/customer/storefront/customer/profile")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'username'", containsString("admin"))
                .body("'email'", containsString("admin@gmail.com"))
                .body("'firstName'", containsString("John"))
                .body("'lastName'", containsString("Doe"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer/backoffice/customers/profile/{id}
    */
    @Test @Timeout(60)
    public void test_2_getOnProfilReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE0OTYsImlhdCI6MTc3NDM5MTE5NiwianRpIjoiZDJkMmU4ODAtNTZkZi00MmU1LWEyNGItMmYwODY5M2UzOGVlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjQyNDgyMmE0LWEwNjgtNGE4Mi04OTBjLTk1YTE4ZGI5NDE5MyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.iXQ04MGFVbVhErSDJG7ksTW7s5YzVXL5LricG0v9X3D6vLPH4hnyAlVMs-4EpLCZSJwSN7aHg39uwOgKfg8uufUghkWPlkKyHCgpgv0w4KBXKV-7cbwvUljMFQaB0sdpE3gYMfl-_FLdxQP_OGBmSkOLOkHJVJIfz_ndkQWRGUR2o5dVV8-XpbMr2WqzHYdyDQnm0QpMULXOZneKcbuKnlJWeWTjEVVa_Jdh4VHpoAKHLP9Tx--C2YX8l94OrmmJtTZLBvsrR-tI21_JXMISg8mngxoeBsTWC-OjTSjxl6oRS5mNkn3-I_ad6tLh52vYBK59Wg1hioWiclCuRiUWTg") // Fixed Headers
                .get(baseUrlOfSut + "/customer/backoffice/customers/profile/6a4ccf58-14a7-4c68-8f35-9107f98755b2")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'username'", containsString("admin"))
                .body("'email'", containsString("admin@gmail.com"))
                .body("'firstName'", containsString("John"))
                .body("'lastName'", containsString("Doe"));
    }


}
