configuration:
  akhq:
    server:
      access-log:
        enabled: false
        name: org.akhq.log.access
    connections:
      kafka-connection:
        properties:
          bootstrap.servers: kafka-cluster-kafka-bootstrap:9092
        connect:
          - name: debezium-connect-cluster
            url: http://debezium-connect-cluster-connect-api:8083
hostname: &hostname akhq.yas.local.com
ingress:
  enabled: true
  ingressClassName: nginx
  annotations: {}
  paths:
    - /
  hosts:
    - *hostname
  tls: []
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - pool-ij7dmpaq8-3cbimb
