/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T23:09:01.205898076Z[GMT]
 * <br>
*  The generated test suite contains 20 tests
 * <br>
*  Covered targets: 104
 * <br>
*  Used time: 0h 1m 45s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_order_none_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdFrom=2000-12-15T23%3A55%3A44Z&" + 
                    "createdTo=2038-04-23T16%3A43%3A38.902Z&" + 
                    "productName=Q6qkrP7m&" + 
                    "email=tgt7IJta&" + 
                    "billingCountry=S9&" + 
                    "pageNo=488&" + 
                    "pageSize=10")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdTo=2085-13-16T23%3A22%3A00Z&" + 
                    "productName=q2&" + 
                    "orderStatus=PAID&orderStatus=PENDING_PAYMENT&orderStatus=SHIPPING&orderStatus=REFUND&" + 
                    "billingPhoneNumber=CfJhmq&" + 
                    "billingCountry=pY1vSlRP_3r0nvoa&" + 
                    "pageSize=367")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_getOnBackofficeOrdersWithQueryParamsEmptyBillingPhoneNumberReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdFrom=2090-05-02T00%3A39%3A27Z&" + 
                    "createdTo=1995-06-25T10%3A19%3A29Z&" + 
                    "billingPhoneNumber=&" + 
                    "email=UPS33HUud7PJLV&" + 
                    "pageSize=413")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdTo=2086-06-24T25%3A44%3A19.194Z&" + 
                    "orderStatus=COMPLETED&" + 
                    "billingPhoneNumber=hxeOl&" + 
                    "billingCountry=MHVP&" + 
                    "pageSize=301")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdTo=1908-07-16T21%3A24%3A38Z&" + 
                    "billingPhoneNumber=FeRw1fhCV6Hs")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/storefront/checkouts
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_postOnCheckoutsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"\", " + 
                    " \"promotionCode\" : \"oO1WrYl3p\", " + 
                    " \"shipmentMethodId\" : \"yS2CCOWd5Nu\", " + 
                    " \"paymentMethodId\" : \"8D8lFuIlwq\", " + 
                    " \"shippingAddressId\" : \"Q3sQ74bmyhI1o\", " + 
                    " \"checkoutItemPostVms\" : [ { " + 
                    " \"productId\" : 710, " + 
                    " \"description\" : \"klpZ_I1Un5Rx3g\" " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/checkouts")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/storefront/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_postOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/orders'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"UjjEz3R7axSgh\", " + 
                    " \"email\" : \"i9R0oVKS\", " + 
                    " \"shippingAddressPostVm\" : { " + 
                    " \"contactName\" : \"Tv\", " + 
                    " \"phone\" : \"JLl5bTSGEi9qcavW\", " + 
                    " \"addressLine1\" : \"_VuMrboR4xm3zTXl\", " + 
                    " \"city\" : \"F7SRUDvU\", " + 
                    " \"zipCode\" : \"gGymXWeqdsn\", " + 
                    " \"districtId\" : 8076991702841094027, " + 
                    " \"districtName\" : \"4dDuOM4\", " + 
                    " \"stateOrProvinceId\" : 422, " + 
                    " \"stateOrProvinceName\" : \"NzGxUTHXvrDTzPnb\", " + 
                    " \"countryId\" : 919, " + 
                    " \"countryName\" : \"LRD5m3_e\" " + 
                    " }, " + 
                    " \"billingAddressPostVm\" : { " + 
                    " \"contactName\" : \"5\", " + 
                    " \"phone\" : \"9upkhoC40Luh\", " + 
                    " \"addressLine1\" : \"ZF\", " + 
                    " \"addressLine2\" : \"uqJnG\", " + 
                    " \"city\" : \"4ZuGVLoeWGF\", " + 
                    " \"zipCode\" : \"q4Nk8d5O96ycW69_\", " + 
                    " \"districtId\" : 637, " + 
                    " \"districtName\" : \"V\", " + 
                    " \"stateOrProvinceId\" : 703, " + 
                    " \"stateOrProvinceName\" : \"y\", " + 
                    " \"countryId\" : -1114506449, " + 
                    " \"countryName\" : \"9t67gV\" " + 
                    " }, " + 
                    " \"note\" : \"v\", " + 
                    " \"tax\" : -4.7550992E8, " + 
                    " \"numberItem\" : 1645491763, " + 
                    " \"totalPrice\" : 1.4070019024755824E9, " + 
                    " \"couponCode\" : \"ce6\", " + 
                    " \"deliveryMethod\" : \"VIETTEL_POST\", " + 
                    " \"paymentMethod\" : \"PAYPAL\", " + 
                    " \"paymentStatus\" : \"CANCELLED\", " + 
                    " \"orderItemPostVms\" : [ { " + 
                    " \"productId\" : 854, " + 
                    " \"productName\" : \"OTikmM_\", " + 
                    " \"quantity\" : 48, " + 
                    " \"productPrice\" : 1.9241718213624516E8, " + 
                    " \"discountAmount\" : 3.595508399965077E8, " + 
                    " \"taxAmount\" : 2.901453101068993E8 " + 
                    " }, { " + 
                    " \"productId\" : 665, " + 
                    " \"quantity\" : 680, " + 
                    " \"discountAmount\" : -1.0301552021952178E9, " + 
                    " \"taxAmount\" : 8.62841000807708E8 " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/orders")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/orders"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/checkouts/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_7_getOnStorefrontCheckoutShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/checkouts/GJlXmrEinsYMs")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts/GJlXmrEinsYMs"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/completed
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_8_getOnOrdersCompletedWithQueryParamShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/completed'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/orders/completed?productId=829")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/completed"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/my-orders
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_9_getOnOrdersMy_ordersWithQueryParamsShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/my-orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/orders/my-orders?" + 
                    "productName=L&" + 
                    "orderStatus=PENDING_PAYMENT")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/my-orders"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/completed
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_10_getOnOrdersCompletedWithQueryParamNegativeProductIdShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/completed'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/orders/completed?productId=-2055533110978688593")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/completed"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/my-orders
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_11_getOnOrdersMy_ordersWithQueryParamShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/my-orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/orders/my-orders?productName=GJsTs7fJ")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/my-orders"));
    }
    
    
    /**
    * Calls:
    * (400) GET:/order/storefront/orders/my-orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_12_getOnMy_ordersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/storefront/orders/my-orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/orders/my-orders?" + 
                    "productName=peMxIclCsIh1&" + 
                    "orderStatus=EVOMASTER")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/storefront/orders/my-orders"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_13_getOnOrderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders/1454610349")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/backoffice/orders/csv
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_14_postOnCsvReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders/csv'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"createdFrom\" : \"1924-05-16T15:22:54Z\", " + 
                    " \"orderStatus\" : [ ], " + 
                    " \"billingPhoneNumber\" : \"q_\", " + 
                    " \"email\" : \"otS6yZ3z5_vZ\", " + 
                    " \"billingCountry\" : \"ywa7QMX3H86Y\", " + 
                    " \"pageNo\" : 679 " + 
                    " } ")
                .post(baseUrlOfSut + "/order/backoffice/orders/csv")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/backoffice/orders/csv"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/checkouts/status
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_15_putOnCheckoutsStatusReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts/status'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"yDWBNidx\" " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/status")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts/status"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/orders/status
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_16_putOnOrdersStatusReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/orders/status'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"paymentId\" : 892, " + 
                    " \"paymentStatus\" : \"q1LwATh\" " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/orders/status")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/orders/status"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/checkout/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_17_getOnOrdersCheckoutShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/checkout/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/orders/checkout/_SjMK2SoA")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/checkout/_SjMK2SoA"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders/latest/{count}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_18_getOnLatestReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders/latest/{count}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders/latest/215")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/checkouts/{id}/payment-method
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_19_putOnPayment_methodReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts/{id}/payment-method'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"paymentMethodId\" : \"vSK9w3VYVUI\" " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/ZLxR3d8/payment-method")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts/ZLxR3d8/payment-method"));
    }


}
