sonar.projectKey=dorayakiiiiz_yas-devops-1-storefront
sonar.organization=yas-devops-1

# Project name and version
sonar.projectName=yas-storefront
sonar.projectVersion=1.0

# Source and test paths
sonar.sources=utils,modules,pages,common,context
sonar.tests=utils/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**