backend:
  replicaCount: 1
  image:
    repository: danzgne/yas-search
    tag: main

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
