apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: product-istio-mutual
  namespace: yas
spec:
  host: product.yas.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: cart-istio-mutual
  namespace: yas
spec:
  host: cart.yas.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: customer-istio-mutual
  namespace: yas
spec:
  host: customer.yas.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: inventory-istio-mutual
  namespace: yas
spec:
  host: inventory.yas.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: media-istio-mutual
  namespace: yas
spec:
  host: media.yas.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: order-istio-mutual
  namespace: yas
spec:
  host: order.yas.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: search-istio-mutual
  namespace: yas
spec:
  host: search.yas.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: tax-istio-mutual
  namespace: yas
spec:
  host: tax.yas.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: storefront-bff-istio-mutual
  namespace: yas
spec:
  host: storefront-bff.yas.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: backoffice-bff-istio-mutual
  namespace: yas
spec:
  host: backoffice-bff.yas.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10

