/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T04:54:42.359614192Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 14
 * <br>
*  Used time: 0h 1m 47s
 * <br>
*  Needed budget for current results: 93%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_order_admin_only_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/order/storefront/orders/my-orders
    */
    @Test @Timeout(60)
    public void test_0_getOnMy_ordersReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/orders/my-orders?productName=2AWm")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/order/backoffice/orders/latest/{count}
    */
    @Test @Timeout(60)
    public void test_1_getOnLatestReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders/latest/632")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }


}
