/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T04:54:42.340726293Z[GMT]
 * <br>
*  The generated test suite contains 28 tests
 * <br>
*  Covered targets: 138
 * <br>
*  Used time: 0h 1m 47s
 * <br>
*  Needed budget for current results: 93%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_order_admin_only_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) GET:/order/backoffice/orders
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_getOnOrdersShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdFrom=1950-12-09T11%3A02%3A01-15%3A40&" + 
                    "billingPhoneNumber=sD4bXzFzeQ5w&" + 
                    "billingCountry=UNA")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/backoffice/orders"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/backoffice/orders
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_getOnOrdersShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "productName=9gxTj1PZ&" + 
                    "email=5YKo4&" + 
                    "pageNo=235")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/backoffice/orders"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/order/storefront/checkouts
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_2_postOnCheckoutsShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"RieokS25nnm5\", " + 
                    " \"paymentMethodId\" : \"b0DAqQ1\", " + 
                    " \"shippingAddressId\" : \"LG\", " + 
                    " \"checkoutItemPostVms\" : [ { " + 
                    " \"quantity\" : 1535178609 " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/checkouts")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts"));
    }
    
    
    /**
    * Calls:
    * (400) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdFrom=2056-08-16T06%3A25%3A05%2B18%3A43&" + 
                    "productName=H&" + 
                    "orderStatus=PENDING&" + 
                    "billingPhoneNumber=&" + 
                    "billingCountry=0vybu52JDYf&" + 
                    "pageSize=278687706")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/backoffice/orders"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/order/storefront/checkouts
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_postOnCheckoutsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/storefront/checkouts'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"promotionCode\" : \"aITuvzNiJgQ7Dos\", " + 
                    " \"shipmentMethodId\" : \"EUw\", " + 
                    " \"paymentMethodId\" : \"wDccHot3Un1tg\", " + 
                    " \"checkoutItemPostVms\" : [ { " + 
                    " \"quantity\" : -762695262 " + 
                    " }, { " + 
                    " \"quantity\" : 178 " + 
                    " }, { " + 
                    " \"productId\" : 617 " + 
                    " }, { }, { " + 
                    " \"productId\" : 420, " + 
                    " \"quantity\" : 140 " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/checkouts")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/storefront/checkouts"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/order/storefront/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_postOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/storefront/orders'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"w9JkKPz_Vn0dP\", " + 
                    " \"email\" : \"Q9ltxGL6PP2Kw5\", " + 
                    " \"shippingAddressPostVm\" : { " + 
                    " \"contactName\" : \"Is7B\", " + 
                    " \"phone\" : \"xpTwhdbSeeV\", " + 
                    " \"addressLine1\" : \"hzXao\", " + 
                    " \"city\" : \"JTmH\", " + 
                    " \"zipCode\" : \"5jdUE\", " + 
                    " \"districtId\" : 569, " + 
                    " \"districtName\" : \"pbxKA1\", " + 
                    " \"stateOrProvinceId\" : 80, " + 
                    " \"stateOrProvinceName\" : \"T\", " + 
                    " \"countryId\" : 608, " + 
                    " \"countryName\" : \"Ri65\" " + 
                    " }, " + 
                    " \"billingAddressPostVm\" : { " + 
                    " \"contactName\" : \"Q6\", " + 
                    " \"phone\" : \"UDWWo\", " + 
                    " \"addressLine1\" : \"HljwJDjOHDI\", " + 
                    " \"city\" : \"I\", " + 
                    " \"zipCode\" : \"8I\", " + 
                    " \"districtId\" : 458, " + 
                    " \"districtName\" : \"lV7ypu6\", " + 
                    " \"stateOrProvinceId\" : 798, " + 
                    " \"stateOrProvinceName\" : \"UdAKljVBlr4b4_\", " + 
                    " \"countryId\" : -404364923969223866, " + 
                    " \"countryName\" : \"3VXvR\" " + 
                    " }, " + 
                    " \"totalPrice\" : 9.903838950318427E8, " + 
                    " \"deliveryMethod\" : \"SHOPEE_EXPRESS\", " + 
                    " \"paymentMethod\" : \"COD\", " + 
                    " \"paymentStatus\" : \"CANCELLED\", " + 
                    " \"orderItemPostVms\" : [ ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/orders")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/storefront/orders"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdFrom=1942-07-21T19%3A14%3A59Z&" + 
                    "createdTo=2034-09-30T15%3A35%3A18.437-10%3A34&" + 
                    "orderStatus=COMPLETED&" + 
                    "billingPhoneNumber=mxcqda7TELJgc")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_getOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders?" + 
                    "createdFrom=1911-08-05T20%3A08%3A44%2B01%3A33&" + 
                    "createdTo=1967-10-06T03%3A42%3A44%2B02%3A19&" + 
                    "billingPhoneNumber=E&" + 
                    "email=MZfBtzrg721gzgP")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/storefront/checkouts
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_8_postOnCheckoutsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"note\" : \"jW0K3_wnnLxO8nD8\", " + 
                    " \"promotionCode\" : \"BJRwdD0eUxk\", " + 
                    " \"paymentMethodId\" : \"r2\", " + 
                    " \"shippingAddressId\" : \"MC\", " + 
                    " \"checkoutItemPostVms\" : [ { " + 
                    " \"description\" : \"o9\", " + 
                    " \"quantity\" : 607 " + 
                    " }, { " + 
                    " \"description\" : \"NDqstSE9DG24\" " + 
                    " }, { " + 
                    " \"description\" : \"DX3gyt7g\", " + 
                    " \"quantity\" : 184 " + 
                    " }, { " + 
                    " \"description\" : \"3THfxCXK\", " + 
                    " \"quantity\" : -1281489520 " + 
                    " }, { " + 
                    " \"productId\" : 957, " + 
                    " \"quantity\" : 392 " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/checkouts")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/storefront/orders
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_9_postOnOrdersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/orders'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"Izbo5d\", " + 
                    " \"email\" : \"cyrtMeRuq\", " + 
                    " \"shippingAddressPostVm\" : { " + 
                    " \"contactName\" : \"51Kj\", " + 
                    " \"phone\" : \"n\", " + 
                    " \"addressLine1\" : \"8KXGs2\", " + 
                    " \"addressLine2\" : \"L3FuUe\", " + 
                    " \"city\" : \"op6mcZ1oO\", " + 
                    " \"zipCode\" : \"HXwkzyC9ahJa3HG\", " + 
                    " \"districtId\" : 68, " + 
                    " \"districtName\" : \"yilMLduapd06sFro\", " + 
                    " \"stateOrProvinceId\" : 165, " + 
                    " \"stateOrProvinceName\" : \"kmLM9m\", " + 
                    " \"countryId\" : 842, " + 
                    " \"countryName\" : \"VEopVn\" " + 
                    " }, " + 
                    " \"billingAddressPostVm\" : { " + 
                    " \"contactName\" : \"jLpY7kS\", " + 
                    " \"phone\" : \"cEsHxaLdJg\", " + 
                    " \"addressLine1\" : \"5NfvKtsmtSdu\", " + 
                    " \"city\" : \"38jqJ\", " + 
                    " \"zipCode\" : \"wHmvWsT\", " + 
                    " \"districtId\" : 324, " + 
                    " \"districtName\" : \"Itzl8tR9IG\", " + 
                    " \"stateOrProvinceId\" : -464472040, " + 
                    " \"stateOrProvinceName\" : \"gbPKD7mFOoh3_\", " + 
                    " \"countryId\" : 791, " + 
                    " \"countryName\" : \"pWIHLl\" " + 
                    " }, " + 
                    " \"note\" : \"MBIM98\", " + 
                    " \"totalPrice\" : 1.1618179126064148E9, " + 
                    " \"deliveryFee\" : 4.2648996547606707E8, " + 
                    " \"deliveryMethod\" : \"SHOPEE_EXPRESS\", " + 
                    " \"paymentMethod\" : \"PAYPAL\", " + 
                    " \"paymentStatus\" : \"EVOMASTER\", " + 
                    " \"orderItemPostVms\" : [ { " + 
                    " \"productPrice\" : -5.028024229330445E8, " + 
                    " \"note\" : \"fc\", " + 
                    " \"discountAmount\" : 1.2367600840781513E8, " + 
                    " \"taxPercent\" : -1.1975631043152115E9 " + 
                    " }, { " + 
                    " \"productName\" : \"mRI9_iemWeEXxn\", " + 
                    " \"note\" : \"ilCa0CAn3FZ2Js\" " + 
                    " }, { " + 
                    " \"productName\" : \"DTLxn4DIN98IrBxs\", " + 
                    " \"quantity\" : 44, " + 
                    " \"productPrice\" : 2.436327096858006E8 " + 
                    " } ] " + 
                    " } ")
                .post(baseUrlOfSut + "/order/storefront/orders")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/orders"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/backoffice/orders/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_10_getOnOrderShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/backoffice/orders/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders/165")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/backoffice/orders/165"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/checkouts/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_11_getOnStorefrontCheckoutShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/checkouts/x")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts/x"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/completed
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_12_getOnOrdersCompletedWithQueryParamShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/completed'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/orders/completed?productId=231")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/completed"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/my-orders
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_13_getOnMy_ordersShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/my-orders'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/orders/my-orders?productName=yGi5DPRXV5aGqzu")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/my-orders"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/completed
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_14_getOnOrdersCompletedWithQueryParamNegativeProductIdShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/completed'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/storefront/orders/completed?productId=-2068717903709042170")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/completed"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/backoffice/orders/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_15_getOnOrderShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/backoffice/orders/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .get(baseUrlOfSut + "/order/backoffice/orders/-40806180")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/backoffice/orders/-40806180"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/order/backoffice/orders/csv
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_16_postOnCsvShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/backoffice/orders/csv'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"billingPhoneNumber\" : \"AUXOAaG7idIBBu\", " + 
                    " \"email\" : \"1u\", " + 
                    " \"billingCountry\" : \"fTiUyZGXyhH240jb\", " + 
                    " \"pageNo\" : 522, " + 
                    " \"pageSize\" : 107 " + 
                    " } ")
                .post(baseUrlOfSut + "/order/backoffice/orders/csv")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/backoffice/orders/csv"));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/order/storefront/checkouts/status
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_17_putOnCheckoutsStatusShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts/status'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutId\" : \"VH5IpDOj1zRX8\" " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/status")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts/status"));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/order/storefront/orders/status
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_18_putOnOrdersStatusShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/status'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"orderId\" : 586 " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/orders/status")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/status"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/order/backoffice/orders/csv
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_19_postOnCsvReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/backoffice/orders/csv'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"warehouse\" : \"ECsJs\", " + 
                    " \"billingPhoneNumber\" : \"E1nWIIs_QUR8C\" " + 
                    " } ")
                .post(baseUrlOfSut + "/order/backoffice/orders/csv")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/order/backoffice/orders/csv"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_20_getOnOrderReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders/179")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/order/backoffice/orders/csv
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_21_postOnCsvReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/orders/csv'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"productName\" : \"aK_gHk\", " + 
                    " \"billingPhoneNumber\" : \"sLZBIyQ\", " + 
                    " \"pageNo\" : 208, " + 
                    " \"pageSize\" : 589 " + 
                    " } ")
                .post(baseUrlOfSut + "/order/backoffice/orders/csv")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/backoffice/orders/csv"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/checkouts/status
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_22_putOnCheckoutsStatusReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts/status'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"checkoutStatus\" : \"bHG5DNuyEeBmq_5W\" " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/status")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts/status"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/orders/status
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_23_putOnOrdersStatusReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/orders/status'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"orderId\" : 8246350302524585324 " + 
                    " } ")
                .put(baseUrlOfSut + "/order/storefront/orders/status")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/orders/status"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/order/storefront/orders/checkout/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_24_getOnOrdersCheckoutShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/orders/checkout/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/orders/checkout/USN")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/orders/checkout/USN"));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/order/storefront/checkouts/{id}/payment-method
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_25_putOnPayment_methodShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/checkouts/{id}/payment-method'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ2NzIsImlhdCI6MTc3NDQxNDM3MiwianRpIjoiMjAxMTY2OTYtMDZiNi00YmZlLTg1N2MtZDg5NThmNDBkY2M5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImU0MmUzMGQ1LTQwMTUtNGNiYy1iZmE4LTUzZTU2MjYzZTI3MSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.PEIT6qc0Jk9KeTN097p8xvbLXuusKUG8RStvZ8KXc3vKNj9C3xEXe9BTJDTql1FiNZsa7vYknzu6-sxGlBWWH7uuGuq1pF8CoPjmz8Iw4W-U1GuTYvvY8Gb9eW1IjJuBIFeldkXZ2YzO4_G_KWtzFbYQc1mzf1tz5Kz91nKjaObqzddu5leE01Lu_NVkHNchiSYIyClO_MP5DuXy0LXjyk3GLKdAWeFJK8k3jiZfewulwPDbVQZhG8Cs6nqa2Wkzi0YFCwYsnHsU5Q-5KwuzS505f9cDXVJplP3q8545yCrM6DtsjR9dEtu7xQg4M4rh5SOKO5CU2UQSWSqiWaLSeA") // Fixed Headers
                .contentType("application/json")
                .body(" { } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/3o/payment-method")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/order/storefront/checkouts/3o/payment-method"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/order/backoffice/orders/latest/{count}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_26_getOnLatestReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/orders/latest/{count}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/order/backoffice/orders/latest/123")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/order/storefront/checkouts/{id}/payment-method
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_27_putOnPayment_methodReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/checkouts/{id}/payment-method'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { } ")
                .put(baseUrlOfSut + "/order/storefront/checkouts/v/payment-method")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/order/storefront/checkouts/v/payment-method"));
    }


}
