apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: yas
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: yas-developer
  labels:
    istio-injection: enabled
