domain: yas.local.com
postgresql:
  replicas: 1
  username: yasadminuser
  password: admin
kafka:
  replicas: 1
zookeeper:
  replicas: 1
elasticsearch:
  replicas: 1
  username: yas
  password: LarUmB3A49NTg9YmgW4=
keycloak:
  bootstrapAdmin:
    username: admin
    password: admin
  backofficeRedirectUrls:
    - http://backoffice.yas.local.com
    - http://backoffice.dev.yas.local.com
    - http://backoffice.staging.yas.local.com
    - http://localhost:3000
    - http://localhost:8087
  storefrontRedirectUrls:
    - http://storefront.yas.local.com
    - http://storefront.dev.yas.local.com
    - http://storefront.staging.yas.local.com
    - http://localhost:8087
grafana:
  username: admin
  password: admin
redis:
  password: redis