apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-nodeport
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30084
  selector:
    app: keycloak
