/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T04:52:51.705340096Z[GMT]
 * <br>
*  The generated test suite contains 10 tests
 * <br>
*  Covered targets: 104
 * <br>
*  Used time: 0h 1m 54s
 * <br>
*  Needed budget for current results: 94%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_rating_admin_only_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/rating/backoffice/ratings
    */
    @Test @Timeout(60)
    public void test_0_getOnRatingsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ1NTQsImlhdCI6MTc3NDQxNDI1NCwianRpIjoiODkwZWQ4ZjUtODc0Ni00MzRkLWFhYWQtNTYzNWMzN2ZhZTA5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjNmY2IzZGUwLTJjNzQtNDgwNS04OWRjLTRiNzMwMzcxYWFlNCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.gYY_cCZ1rjFTenheLrKwJDH-Cf4JJQU4iAjIZpWS7IF3fWPSPkeR7wogCCtf389x4mNn6qttXb0VyI3q89wQFAYtsAv2kbv0L19jVXjqtjr9AndOqs3VnA7PVP1JOdhYuV3-AJObWN77j2e-HkWZ5f7DdKQ8kcAEsh7JZQ6lsAF02Pfl1zTEBTRD29zLeLRHvAoAT9wRRXfa8jAu8EyuTq7G8w7mmlhRRLZClaxElkIhk0hZDUpioG9m1LbWDaiVz446soO_aReaRNY6i9SoJBfZ_oePsZ1IyRCVH3KRNnIyK88G5h_J3IRXNCzp4cQOcyPp6j7qkLMVw6iMDxF2_Q") // Fixed Headers
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "message=rxQqiexd3fTtK&" + 
                    "createdFrom=1920-09-15T15%3A53%3A02.391-17%3A33&" + 
                    "createdTo=1947-03-10T16%3A56%3A32.384-07%3A19&" + 
                    "pageSize=566")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/backoffice/ratings
    */
    @Test @Timeout(60)
    public void test_1_getOnRatingsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ1NTQsImlhdCI6MTc3NDQxNDI1NCwianRpIjoiODkwZWQ4ZjUtODc0Ni00MzRkLWFhYWQtNTYzNWMzN2ZhZTA5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjNmY2IzZGUwLTJjNzQtNDgwNS04OWRjLTRiNzMwMzcxYWFlNCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.gYY_cCZ1rjFTenheLrKwJDH-Cf4JJQU4iAjIZpWS7IF3fWPSPkeR7wogCCtf389x4mNn6qttXb0VyI3q89wQFAYtsAv2kbv0L19jVXjqtjr9AndOqs3VnA7PVP1JOdhYuV3-AJObWN77j2e-HkWZ5f7DdKQ8kcAEsh7JZQ6lsAF02Pfl1zTEBTRD29zLeLRHvAoAT9wRRXfa8jAu8EyuTq7G8w7mmlhRRLZClaxElkIhk0hZDUpioG9m1LbWDaiVz446soO_aReaRNY6i9SoJBfZ_oePsZ1IyRCVH3KRNnIyK88G5h_J3IRXNCzp4cQOcyPp6j7qkLMVw6iMDxF2_Q") // Fixed Headers
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "productName=F9jt1m7XmN0MG&" + 
                    "createdFrom=2026-09-27T20%3A51%3A20.369-11%3A08&" + 
                    "pageNo=69")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/backoffice/ratings
    */
    @Test @Timeout(60)
    public void test_2_getOnRatingsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ1NTQsImlhdCI6MTc3NDQxNDI1NCwianRpIjoiODkwZWQ4ZjUtODc0Ni00MzRkLWFhYWQtNTYzNWMzN2ZhZTA5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjNmY2IzZGUwLTJjNzQtNDgwNS04OWRjLTRiNzMwMzcxYWFlNCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.gYY_cCZ1rjFTenheLrKwJDH-Cf4JJQU4iAjIZpWS7IF3fWPSPkeR7wogCCtf389x4mNn6qttXb0VyI3q89wQFAYtsAv2kbv0L19jVXjqtjr9AndOqs3VnA7PVP1JOdhYuV3-AJObWN77j2e-HkWZ5f7DdKQ8kcAEsh7JZQ6lsAF02Pfl1zTEBTRD29zLeLRHvAoAT9wRRXfa8jAu8EyuTq7G8w7mmlhRRLZClaxElkIhk0hZDUpioG9m1LbWDaiVz446soO_aReaRNY6i9SoJBfZ_oePsZ1IyRCVH3KRNnIyK88G5h_J3IRXNCzp4cQOcyPp6j7qkLMVw6iMDxF2_Q") // Fixed Headers
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "customerName=P3r3Y4j5wd&" + 
                    "message=8&" + 
                    "createdTo=1945-12-12T14%3A39%3A02%2B11%3A23")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/backoffice/ratings/latest/{count}
    */
    @Test @Timeout(60)
    public void test_3_getOnLatestReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ1NTQsImlhdCI6MTc3NDQxNDI1NCwianRpIjoiODkwZWQ4ZjUtODc0Ni00MzRkLWFhYWQtNTYzNWMzN2ZhZTA5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjNmY2IzZGUwLTJjNzQtNDgwNS04OWRjLTRiNzMwMzcxYWFlNCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.gYY_cCZ1rjFTenheLrKwJDH-Cf4JJQU4iAjIZpWS7IF3fWPSPkeR7wogCCtf389x4mNn6qttXb0VyI3q89wQFAYtsAv2kbv0L19jVXjqtjr9AndOqs3VnA7PVP1JOdhYuV3-AJObWN77j2e-HkWZ5f7DdKQ8kcAEsh7JZQ6lsAF02Pfl1zTEBTRD29zLeLRHvAoAT9wRRXfa8jAu8EyuTq7G8w7mmlhRRLZClaxElkIhk0hZDUpioG9m1LbWDaiVz446soO_aReaRNY6i9SoJBfZ_oePsZ1IyRCVH3KRNnIyK88G5h_J3IRXNCzp4cQOcyPp6j7qkLMVw6iMDxF2_Q") // Fixed Headers
                .get(baseUrlOfSut + "/rating/backoffice/ratings/latest/504")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_4_getOnRatingsProductWithQueryParamsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/540?" + 
                    "pageNo=391&" + 
                    "pageSize=754")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_5_getOnProductReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ1NTQsImlhdCI6MTc3NDQxNDI1NCwianRpIjoiODkwZWQ4ZjUtODc0Ni00MzRkLWFhYWQtNTYzNWMzN2ZhZTA5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjNmY2IzZGUwLTJjNzQtNDgwNS04OWRjLTRiNzMwMzcxYWFlNCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.gYY_cCZ1rjFTenheLrKwJDH-Cf4JJQU4iAjIZpWS7IF3fWPSPkeR7wogCCtf389x4mNn6qttXb0VyI3q89wQFAYtsAv2kbv0L19jVXjqtjr9AndOqs3VnA7PVP1JOdhYuV3-AJObWN77j2e-HkWZ5f7DdKQ8kcAEsh7JZQ6lsAF02Pfl1zTEBTRD29zLeLRHvAoAT9wRRXfa8jAu8EyuTq7G8w7mmlhRRLZClaxElkIhk0hZDUpioG9m1LbWDaiVz446soO_aReaRNY6i9SoJBfZ_oePsZ1IyRCVH3KRNnIyK88G5h_J3IRXNCzp4cQOcyPp6j7qkLMVw6iMDxF2_Q") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/861?pageNo=597")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_6_getOnProductReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ1NTQsImlhdCI6MTc3NDQxNDI1NCwianRpIjoiODkwZWQ4ZjUtODc0Ni00MzRkLWFhYWQtNTYzNWMzN2ZhZTA5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjNmY2IzZGUwLTJjNzQtNDgwNS04OWRjLTRiNzMwMzcxYWFlNCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.gYY_cCZ1rjFTenheLrKwJDH-Cf4JJQU4iAjIZpWS7IF3fWPSPkeR7wogCCtf389x4mNn6qttXb0VyI3q89wQFAYtsAv2kbv0L19jVXjqtjr9AndOqs3VnA7PVP1JOdhYuV3-AJObWN77j2e-HkWZ5f7DdKQ8kcAEsh7JZQ6lsAF02Pfl1zTEBTRD29zLeLRHvAoAT9wRRXfa8jAu8EyuTq7G8w7mmlhRRLZClaxElkIhk0hZDUpioG9m1LbWDaiVz446soO_aReaRNY6i9SoJBfZ_oePsZ1IyRCVH3KRNnIyK88G5h_J3IRXNCzp4cQOcyPp6j7qkLMVw6iMDxF2_Q") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/1322371020?pageSize=115")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_7_getOnProductReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ1NTQsImlhdCI6MTc3NDQxNDI1NCwianRpIjoiODkwZWQ4ZjUtODc0Ni00MzRkLWFhYWQtNTYzNWMzN2ZhZTA5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjNmY2IzZGUwLTJjNzQtNDgwNS04OWRjLTRiNzMwMzcxYWFlNCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.gYY_cCZ1rjFTenheLrKwJDH-Cf4JJQU4iAjIZpWS7IF3fWPSPkeR7wogCCtf389x4mNn6qttXb0VyI3q89wQFAYtsAv2kbv0L19jVXjqtjr9AndOqs3VnA7PVP1JOdhYuV3-AJObWN77j2e-HkWZ5f7DdKQ8kcAEsh7JZQ6lsAF02Pfl1zTEBTRD29zLeLRHvAoAT9wRRXfa8jAu8EyuTq7G8w7mmlhRRLZClaxElkIhk0hZDUpioG9m1LbWDaiVz446soO_aReaRNY6i9SoJBfZ_oePsZ1IyRCVH3KRNnIyK88G5h_J3IRXNCzp4cQOcyPp6j7qkLMVw6iMDxF2_Q") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/-926105228?pageSize=166")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/product/{productId}/average-star
    */
    @Test @Timeout(60)
    public void test_8_getOnAverage_starReturnsContent() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ1NTQsImlhdCI6MTc3NDQxNDI1NCwianRpIjoiODkwZWQ4ZjUtODc0Ni00MzRkLWFhYWQtNTYzNWMzN2ZhZTA5IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjNmY2IzZGUwLTJjNzQtNDgwNS04OWRjLTRiNzMwMzcxYWFlNCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.gYY_cCZ1rjFTenheLrKwJDH-Cf4JJQU4iAjIZpWS7IF3fWPSPkeR7wogCCtf389x4mNn6qttXb0VyI3q89wQFAYtsAv2kbv0L19jVXjqtjr9AndOqs3VnA7PVP1JOdhYuV3-AJObWN77j2e-HkWZ5f7DdKQ8kcAEsh7JZQ6lsAF02Pfl1zTEBTRD29zLeLRHvAoAT9wRRXfa8jAu8EyuTq7G8w7mmlhRRLZClaxElkIhk0hZDUpioG9m1LbWDaiVz446soO_aReaRNY6i9SoJBfZ_oePsZ1IyRCVH3KRNnIyK88G5h_J3IRXNCzp4cQOcyPp6j7qkLMVw6iMDxF2_Q") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/product/493/average-star")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body(containsString("0.0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/product/{productId}/average-star
    */
    @Test @Timeout(60)
    public void test_9_getOnAverage_starReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/storefront/ratings/product/166/average-star")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body(containsString("0.0"));
    }


}
