/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T22:51:53.998542997Z[GMT]
 * <br>
*  The generated test suite contains 1 tests
 * <br>
*  Covered targets: 8
 * <br>
*  Used time: 0h 1m 27s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_order_customer_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/order/storefront/orders/my-orders
    */
    @Test @Timeout(60)
    public void test_0_getOnMy_ordersReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTI5MjQsImlhdCI6MTc3NDM5MjYyNCwianRpIjoiOWZkNjk5MGQtYTE0Ni00ZTEzLTkyZjktMWFlZDg2NmQyZGI3IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjliNThmMDg0LTZlZTItNDQ2My05MTU5LWVlZTdhZmRkOGJhNSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.WSWEv4KHwCrq6iyca2z6CXTGfNVA2WagDDaL3tvlPfwmyScINEkwmHi8SSFNA0EBuRns9h3XAn-QzqRlSmgZPPIdnD_i4iG9zgQjFOdM9mLQ6F9VV7AwJ5ba0LzlCMA0TWTAZ9eNiD_MXJLu9XJppzjclLnrydr6JPyfXnTUq9vhP74xw9eitEj9ZBRMYLxQxizG5e9dI_X0t_AuoJKs-IQjIeztfIwE05tm4w1DJjJgSMPb2nvXdEhHt-Rw4w66YnXB0Sx043FyA2GWgkmozw0A1vBAjCwWjCpenckGo6BsjJXYBcawe8JJjrE-zTZddYV2O2u_ZkOR-XfhRlzE_w") // Fixed Headers
                .get(baseUrlOfSut + "/order/storefront/orders/my-orders?productName=GTpE")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }


}
