export enum ECheckoutState {
  COMPLETED = 'COMPLETED',
  PENDING = 'PENDING',
  LOCK = 'LOCK',
  CHECKED_OUT = 'CHECKED_OUT',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  FULFILLED = 'FULFILLED',
}
