export enum ECheckoutProgress {
  INIT = 'INIT',
  PROMOTION_CODE_APPLIED = 'PROMOTION_CODE_APPLIED',
  PROMOTION_CODE_APPLIED_FAILED = 'PROMOTION_CODE_APPLIED_FAILED',
  STOCK_LOCKED = 'STOCK_LOCKED',
  STOCK_LOCKED_FAILED = 'STOCK_LOCKED_FAILED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_CREATED_FAILED = 'PAYMENT_CREATED_FAILED',
}
