export enum EOrderStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  SHIPPING = 'SHIPPING',
  COMPLETED = 'COMPLETED',
  REFUND = 'REFUND',
  CANCELLED = 'CANCELLED',
  PAID = 'PAID',
  REJECT = 'REJECT',
}
