/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T22:57:20.313575214Z[GMT]
 * <br>
*  The generated test suite contains 29 tests
 * <br>
*  Covered targets: 118
 * <br>
*  Used time: 0h 1m 45s
 * <br>
*  Needed budget for current results: 87%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_tax_customer_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_getOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_getOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_postOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"e5fUvR9zE\", " + 
                    " \"name\" : \"zxSgPCFTzpap7UI\" " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-rates
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_postOnTax_ratesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\" : -1.8187517370445888E9, " + 
                    " \"zipCode\" : \"74ZW9B5Lb\", " + 
                    " \"taxClassId\" : 307, " + 
                    " \"stateOrProvinceId\" : 98, " + 
                    " \"countryId\" : 681 " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-rates")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-classes
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_postOnTax_classesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"Ph\" " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-classes"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/tax/backoffice/tax-rates
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_postOnTax_ratesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\" : 4008359.94979182, " + 
                    " \"taxClassId\" : 521, " + 
                    " \"stateOrProvinceId\" : 130, " + 
                    " \"countryId\" : 199 " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-rates")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-rates"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_getOnTax_ratesPagingWithQueryParamReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-rates/paging'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/paging?pageSize=117")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/tax-percent
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_getOnTax_percentReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-rates/tax-percent'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/tax-percent?" + 
                    "taxClassId=675&" + 
                    "countryId=884&" + 
                    "stateOrProvinceId=857&" + 
                    "zipCode=HDaS")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-classes/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_8_getOnPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-classes/paging'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/paging")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/location-based-batch
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_9_getOnLocation_based_batchReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-rates/location-based-batch'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/location-based-batch?" + 
                    "taxClassIds=743&taxClassIds=943&taxClassIds=391&" + 
                    "countryId=680&" + 
                    "stateOrProvinceId=884")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_10_getOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/-859952209")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_11_getOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/10")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-classes/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_12_getOnTax_classesPagingWithQueryParamsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/paging'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/paging?" + 
                    "pageNo=32&" + 
                    "pageSize=432")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-classes/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_13_getOnPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/paging'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/paging")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-classes/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_14_getOnTax_classesPagingWithQueryParamReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/paging'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/paging?pageNo=870")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/location-based-batch
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_15_getOnLocation_based_batchReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/location-based-batch'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/location-based-batch?" + 
                    "taxClassIds=909&taxClassIds=471&" + 
                    "countryId=254&" + 
                    "stateOrProvinceId=367")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_16_getOnTax_ratesPagingWithQueryParamsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/paging'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/paging?" + 
                    "pageNo=712&" + 
                    "pageSize=10")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/paging
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_17_getOnTax_ratesPagingReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/paging'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/paging")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/tax-percent
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_18_getOnTax_percentReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/tax-percent'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/tax-percent?" + 
                    "taxClassId=571&" + 
                    "countryId=937")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_19_getOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/405")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_20_getOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/91")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_21_putOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"308\" " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-classes/308")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_22_putOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\" : 901.0, " + 
                    " \"zipCode\" : \"DPUZ4UygR_b90n\", " + 
                    " \"taxClassId\" : -4145467775558829085, " + 
                    " \"stateOrProvinceId\" : 499, " + 
                    " \"countryId\" : 4495942198064580936 " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-rates/901")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_23_putOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"166\" " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-classes/166")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-classes/166"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_24_putOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\" : 740.0, " + 
                    " \"zipCode\" : \"8N3skYeGXLs4uEZ\", " + 
                    " \"taxClassId\" : 6894490827493702679, " + 
                    " \"stateOrProvinceId\" : 330, " + 
                    " \"countryId\" : -6684510148795588921 " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-rates/740")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-rates/740"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_25_deleteOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .delete(baseUrlOfSut + "/tax/backoffice/tax-classes/176")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_26_deleteOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTMyMzMsImlhdCI6MTc3NDM5MjkzMywianRpIjoiZTM0Nzg5MWQtOWI2YS00Mzk5LWIzNmYtMDM5ZTAwOTg3NmIyIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6Ijc3ZWU4NWU2LTQ2YmUtNGM4ZS05NDJkLTY0YWRiZTkzODllYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.Qy3Ye8F6dDAKGXtyf26fKNdhT9dWttN4Hw9M19PJTF5iL9CwCKUgQ9sIB7waCR8koojwD0zGed2PbiI41SSZ2xaKAcc4nG87qzpOIt68de2ATzgJ-QqaUu9ifGNrA9ewXXGdB-MRHmS1Wl_SIQ2CkthCUOqOBTHPoo34BNdyWl5njVsEuAl5iyoKh2aLXG1GzJOH-xig4DlMn_lgvAgNzre-0l9xeGdug8K3NARyo-04Ecvu0WcCVPEW-1E9H5RZU8GVRfOukGXDBoeYJCfrL0voJslHkSNMgYfdqp5WFHrfl9PEJyjsDawgugrq1FlstErCkR2KmEEQ40wVfoLZsw") // Fixed Headers
                .delete(baseUrlOfSut + "/tax/backoffice/tax-rates/181121330783026990")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-classes/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_27_deleteOnTax_classReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-classes/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/tax/backoffice/tax-classes/596")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-classes/596"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/tax/backoffice/tax-rates/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_28_deleteOnTax_ratReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/tax-rates/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/tax/backoffice/tax-rates/168")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/tax/backoffice/tax-rates/168"));
    }


}
