apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-customer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/luc1fe4/yas.git'
    targetRevision: 'clean-setup-ok'
    path: k8s/charts/customer
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
