apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-backoffice-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/luc1fe4/yas.git'
    targetRevision: 'gitops-dev'
    path: k8s/charts/backoffice-ui
    helm:
      parameters:
        - name: ui.image.tag
          value: '88f6c0b6'
        - name: ui.image.repository
          value: 'besukem/backoffice'
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
