/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T23:04:29.386677512Z[GMT]
 * <br>
*  The generated test suite contains 14 tests
 * <br>
*  Covered targets: 47
 * <br>
*  Used time: 0h 1m 29s
 * <br>
*  Needed budget for current results: 52%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_customer_none_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (401) GET:/customer/backoffice/customers
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_getOnBackofficeCustomersWithQueryParamReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/customers'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/backoffice/customers?pageNo=627")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/backoffice/customers
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_getOnBackofficeCustomersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/customers'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/backoffice/customers")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/customer/storefront/user-address
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_getOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/storefront/user-address")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("403 FORBIDDEN"))
                .body("'title'", containsString("Forbidden"))
                .body("'detail'", containsString("ACTION FAILED, PLEASE LOGIN"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (403) POST:/customer/backoffice/customers
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_postOnCustomersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"username\" : \"B\", " + 
                    " \"email\" : \"FU\", " + 
                    " \"firstName\" : \"g83vDMIjYMjF\", " + 
                    " \"lastName\" : \"1x\", " + 
                    " \"password\" : \"5CCPoSo7ECxY\", " + 
                    " \"role\" : \"DgW\" " + 
                    " } ")
                .post(baseUrlOfSut + "/customer/backoffice/customers")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/backoffice/customers"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/customer/storefront/user-address
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_postOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"phone\" : \"8APg_KCjNNqq\", " + 
                    " \"city\" : \"XvBG3k2\", " + 
                    " \"districtId\" : 661, " + 
                    " \"stateOrProvinceId\" : 804 " + 
                    " } ")
                .post(baseUrlOfSut + "/customer/storefront/user-address")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/user-address"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/backoffice/customers/{email}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_getOnCustomReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/customers/{email}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/backoffice/customers/43SNGM")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/storefront/customer/profile
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_getOnProfileReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/storefront/customer/profile'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/storefront/customer/profile")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/customer/storefront/user-address/default-address
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_getOnDefault_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address/default-address'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/storefront/user-address/default-address")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("403 FORBIDDEN"))
                .body("'title'", containsString("Forbidden"))
                .body("'detail'", containsString("ACTION FAILED, PLEASE LOGIN"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (403) POST:/customer/storefront/customer/guest-user
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_8_postOnGuest_userReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/customer/guest-user'.
        given().accept("*/*")
                .post(baseUrlOfSut + "/customer/storefront/customer/guest-user")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/customer/guest-user"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/customer/storefront/user-address/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_9_putOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address/{id}'.
        given().accept("*/*")
                .put(baseUrlOfSut + "/customer/storefront/user-address/318")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/user-address/318"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/customer/storefront/user-address/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_10_deleteOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/customer/storefront/user-address/650")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/user-address/650"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_11_getOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/backoffice/customers/profile/Kfu")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_12_putOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"firstName\" : \"r77WnpI\" " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/backoffice/customers/profile/dxPT")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/backoffice/customers/profile/dxPT"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_13_deleteOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/customer/backoffice/customers/profile/7XKx4l")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/backoffice/customers/profile/7XKx4l"));
    }


}
