/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T22:39:43.629180220Z[GMT]
 * <br>
*  The generated test suite contains 8 tests
 * <br>
*  Covered targets: 70
 * <br>
*  Used time: 0h 2m 0s
 * <br>
*  Needed budget for current results: 65%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_tax_admin_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/tax/backoffice/tax-classes
    */
    @Test @Timeout(60)
    public void test_0_getOnTax_classesReturns5Elements() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(5))
                .body("[0].'name'", containsString("2ke9"))
                .body("[1].'name'", containsString("S"))
                .body("[2].'name'", containsString("Uud6UjH"))
                ; // Skipping assertions on the remaining 2 elements. This limit of 3 elements can be increased in the configurations
    }
    
    
    /**
    * Calls:
    * (200) GET:/tax/backoffice/tax-classes/paging
    */
    @Test @Timeout(60)
    public void test_1_getOnTax_classesPagingWithQueryParamsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/paging?" + 
                    "pageNo=376&" + 
                    "pageSize=597")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'taxClassContent'.size()", equalTo(0))
                .body("'pageNo'", numberMatches(376))
                .body("'pageSize'", numberMatches(597))
                .body("'totalElements'", numberMatches(5))
                .body("'totalPages'", numberMatches(1))
                .body("'isLast'", equalTo(true));
    }
    
    
    /**
    * Calls:
    * (200) GET:/tax/backoffice/tax-rates/location-based-batch
    */
    @Test @Timeout(60)
    public void test_2_getOnLocation_based_batchReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/location-based-batch?" + 
                    "taxClassIds=348&taxClassIds=229&taxClassIds=171&taxClassIds=922&taxClassIds=914&" + 
                    "countryId=946&" + 
                    "stateOrProvinceId=71")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/tax/backoffice/tax-rates/paging
    */
    @Test @Timeout(60)
    public void test_3_getOnTax_ratesPagingWithQueryParamReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/paging?pageSize=186")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'taxRateGetDetailContent'.size()", equalTo(1))
                .body("'taxRateGetDetailContent'[0].'rate'", numberMatches(8.0))
                .body("'taxRateGetDetailContent'[0].'zipCode'", containsString("70000"))
                .body("'taxRateGetDetailContent'[0].'taxClassName'", containsString("Value Added Tax (VAT)"))
                .body("'taxRateGetDetailContent'[0].'stateOrProvinceName'", containsString("Hồ Chí Minh"))
                .body("'taxRateGetDetailContent'[0].'countryName'", containsString("Viet Nam"))
                .body("'pageNo'", numberMatches(0))
                .body("'pageSize'", numberMatches(186))
                .body("'totalElements'", numberMatches(1))
                .body("'totalPages'", numberMatches(1))
                .body("'isLast'", equalTo(true));
    }
    
    
    /**
    * Calls:
    * (200) GET:/tax/backoffice/tax-rates/tax-percent
    */
    @Test @Timeout(60)
    public void test_4_getOnTax_ratesTax_percentWithQueryParamsNegativeCountryIdReturnsContent() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/tax-percent?" + 
                    "taxClassId=977&" + 
                    "countryId=-1659206823&" + 
                    "stateOrProvinceId=901")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body(containsString("0.0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/tax/backoffice/tax-classes/paging
    */
    @Test @Timeout(60)
    public void test_5_getOnTax_classesPagingWithQueryParamReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/paging?pageSize=443")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'taxClassContent'.size()", equalTo(5))
                .body("'taxClassContent'[0].'name'", containsString("Value Added Tax (VAT)"))
                .body("'taxClassContent'[1].'name'", containsString("2ke9"))
                .body("'taxClassContent'[2].'name'", containsString("S"))
                // Skipping assertions on the remaining 2 elements. This limit of 3 elements can be increased in the configurations
                .body("'pageNo'", numberMatches(0))
                .body("'pageSize'", numberMatches(443))
                .body("'totalElements'", numberMatches(5))
                .body("'totalPages'", numberMatches(1))
                .body("'isLast'", equalTo(true));
    }
    
    
    /**
    * Calls:
    * (200) GET:/tax/backoffice/tax-rates/tax-percent
    */
    @Test @Timeout(60)
    public void test_6_getOnTax_percentReturnsContent() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/tax-percent?" + 
                    "taxClassId=846&" + 
                    "countryId=204&" + 
                    "zipCode=70000")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body(containsString("0.0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/tax/backoffice/tax-rates/tax-percent
    */
    @Test @Timeout(60)
    public void test_7_getOnTax_percentReturnsContent() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/tax-percent?" + 
                    "taxClassId=5&" + 
                    "countryId=802&" + 
                    "stateOrProvinceId=687&" + 
                    "zipCode=70000")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body(containsString("0.0"));
    }


}
