/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T22:39:43.633246759Z[GMT]
 * <br>
*  The generated test suite contains 10 tests
 * <br>
*  Covered targets: 27
 * <br>
*  Used time: 0h 2m 0s
 * <br>
*  Needed budget for current results: 65%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_tax_admin_others {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (400) POST:/tax/backoffice/tax-classes
    */
    @Test @Timeout(60)
    public void test_0_postOnTax_classesReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"9oKGEyBzP\", " + 
                    " \"name\" : \"Uud6UjH\" " + 
                    " } ")
                .post(baseUrlOfSut + "/tax/backoffice/tax-classes")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("NAME_ALREADY_EXITED"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/tax/backoffice/tax-classes/{id}
    */
    @Test @Timeout(60)
    public void test_1_getOnTax_classReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-classes/883")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("TAX_CLASS_NOT_FOUND"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/tax/backoffice/tax-rates/{id}
    */
    @Test @Timeout(60)
    public void test_2_getOnTax_ratReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .get(baseUrlOfSut + "/tax/backoffice/tax-rates/483")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("TAX_RATE_NOT_FOUND"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/:-1/tax/v3/api-docs
    */
    @Test @Timeout(60)
    public void test_3_getOnApi_docsReturns404() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/:-1/tax/v3/api-docs")
                .then()
                .statusCode(404);
    }
    
    
    /**
    * Calls:
    * (404) PUT:/tax/backoffice/tax-classes/{id}
    */
    @Test @Timeout(60)
    public void test_4_putOnTax_classReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"834\" " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-classes/834")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("TAX_CLASS_NOT_FOUND"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) PUT:/tax/backoffice/tax-rates/{id}
    */
    @Test @Timeout(60)
    public void test_5_putOnTax_ratReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\" : 768.0, " + 
                    " \"zipCode\" : \"NUqldAdpb_Rh8n4P\", " + 
                    " \"taxClassId\" : 680, " + 
                    " \"stateOrProvinceId\" : 672, " + 
                    " \"countryId\" : 326 " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-rates/768")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("TAX_RATE_NOT_FOUND"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) PUT:/tax/backoffice/tax-rates/{id}
    */
    @Test @Timeout(60)
    public void test_6_putOnTax_ratReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"rate\" : 109.0, " + 
                    " \"taxClassId\" : 165, " + 
                    " \"countryId\" : 74 " + 
                    " } ")
                .put(baseUrlOfSut + "/tax/backoffice/tax-rates/-7385774387547745753")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("TAX_RATE_NOT_FOUND"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) DELETE:/tax/backoffice/tax-classes/{id}
    */
    @Test @Timeout(60)
    public void test_7_deleteOnTax_classReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .delete(baseUrlOfSut + "/tax/backoffice/tax-classes/626")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("TAX_CLASS_NOT_FOUND"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) DELETE:/tax/backoffice/tax-rates/{id}
    */
    @Test @Timeout(60)
    public void test_8_deleteOnTax_ratReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .delete(baseUrlOfSut + "/tax/backoffice/tax-rates/4611575565402118590")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("TAX_RATE_NOT_FOUND"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) DELETE:/tax/backoffice/tax-rates/{id}
    */
    @Test @Timeout(60)
    public void test_9_deleteOnTax_ratReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIxNjAsImlhdCI6MTc3NDM5MTg2MCwianRpIjoiZmY3ZjIxNmMtYzI3Zi00YjRhLTk5NzEtMTAxZDM3ZGM0YTViIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImFlMWEwNjgwLWMyN2QtNGI5YS04NGY2LTk2YzNkNDM0MTI1YyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.gUWZ2ZtrY4-BW5XAZtkgOIuW3TYooG9wXb6WgFZqQsUU8ExcqNOQJ-_-fGfjO3CuyPVLHgEQFBO7g7MJPGdD0gsh4KRyLlmdblATqIgOhw4hNvbrpgeHzHkdsrjvFutq9gsB4IiT4H3meS2A6V_wk_TOgSNrm2Vqgwn2PgDbk3Paqw3Syt-54ziePjVhPSjlvkbapYIfUaXwjimJeq8lq11gike3cgBqrwIGMPaefbpEIgg-Ys0G4XsHspZTOzM_ylbj39ch6rltWR-ypRXVbg6OjB_Xo0hShnrCYdiTp2EnVJZbQu1Co0VkoWM9dMiugaU8dvTC0R7mo_KLL3OChg") // Fixed Headers
                .delete(baseUrlOfSut + "/tax/backoffice/tax-rates/-7385774387547745753")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("TAX_RATE_NOT_FOUND"))
                .body("'fieldErrors'", nullValue());
    }


}
