backend:
  replicaCount: 1
  image:
    repository: danzgne/yas-product
    tag: main

  nameOverride: product
  fullnameOverride: product
  databaseName: product
  ingress:
    enabled: false
  extraVolumes:
    - name: product-application-config
      configMap:
        name: product-application-configmap
  extraVolumeMounts:
    - name: product-application-config
      mountPath: /opt/yas/product
  extraApplicationConfigPaths:
    - /opt/yas/product/product-application.yaml  
