backend:
  replicaCount: 1
  image:
    repository: danzgne/yas-promotion
    tag: main

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  ingress:
    enabled: false
