/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T22:48:53.904059921Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 10
 * <br>
*  Used time: 0h 1m 27s
 * <br>
*  Needed budget for current results: 69%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_cart_customer_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/cart/storefront/cart/items
    */
    @Test @Timeout(60)
    public void test_0_getOnItemsReturns1Element() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTI3NDQsImlhdCI6MTc3NDM5MjQ0NCwianRpIjoiM2Y0ODkyNjAtOWNjYS00MDg5LThiYzktM2JkZTdiN2M4M2Y2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImM0ZGJmZDYyLTAwZjUtNDVlYi04NzQ3LWUxMzFjZTFlYzE5OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.QelYPEVmXzK9-Fn-QEGQqpMKblrErJSdBxLRcRQuXtQ8VNiVTUn1wyNZphwu-pffDkGvNizwh5x88ZeoFfR2xdxyqKunsNyhpbhESvXhzJ60fdeK4Hrui08JOSQpURFqfGrsEsJM2ComRqBce-IleUFniMdtp-ET_o34sBGbXpmddn07uJhHbR1OkwB3V70FaA6hlKnfhCFoaLHLPQq3QqKRIZZscFcxqj_uZnIlCzK5ypv9vI8xk9tQk4vGdYOaPDhXvo4VU8QRizQ5RUe1703PKRqrzkZ8AdkGOSitdl23GeM5fHfwfjS43i3ABvi_b8NrIxkaWCZbYYB98Du9Sw") // Fixed Headers
                .get(baseUrlOfSut + "/cart/storefront/cart/items")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(1))
                .body("[0].'customerId'", containsString("05aac2ba-1f0e-4d33-a047-ffb9a3f2a481"))
                .body("[0].'productId'", numberMatches(5))
                .body("[0].'quantity'", numberMatches(1732139864));
    }
    
    
    /**
    * Calls:
    * (200) POST:/cart/storefront/cart/items/remove
    */
    @Test @Timeout(60)
    public void test_1_postOnRemoveReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTI3NDQsImlhdCI6MTc3NDM5MjQ0NCwianRpIjoiM2Y0ODkyNjAtOWNjYS00MDg5LThiYzktM2JkZTdiN2M4M2Y2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImM0ZGJmZDYyLTAwZjUtNDVlYi04NzQ3LWUxMzFjZTFlYzE5OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.QelYPEVmXzK9-Fn-QEGQqpMKblrErJSdBxLRcRQuXtQ8VNiVTUn1wyNZphwu-pffDkGvNizwh5x88ZeoFfR2xdxyqKunsNyhpbhESvXhzJ60fdeK4Hrui08JOSQpURFqfGrsEsJM2ComRqBce-IleUFniMdtp-ET_o34sBGbXpmddn07uJhHbR1OkwB3V70FaA6hlKnfhCFoaLHLPQq3QqKRIZZscFcxqj_uZnIlCzK5ypv9vI8xk9tQk4vGdYOaPDhXvo4VU8QRizQ5RUe1703PKRqrzkZ8AdkGOSitdl23GeM5fHfwfjS43i3ABvi_b8NrIxkaWCZbYYB98Du9Sw") // Fixed Headers
                .contentType("application/json")
                .body(" [ { " + 
                    " \"productId\" : 31, " + 
                    " \"quantity\" : 670 " + 
                    " }, { " + 
                    " \"productId\" : 918, " + 
                    " \"quantity\" : 304 " + 
                    " }, { " + 
                    " \"productId\" : 877, " + 
                    " \"quantity\" : 2147483016 " + 
                    " } ] ")
                .post(baseUrlOfSut + "/cart/storefront/cart/items/remove")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }


}
