/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T04:47:48.805693574Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 11
 * <br>
*  Used time: 0h 1m 26s
 * <br>
*  Needed budget for current results: 50%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_media_admin_only_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/media/medias
    */
    @Test @Timeout(60)
    public void test_0_getOnMediasReturns1Element() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQyODAsImlhdCI6MTc3NDQxMzk4MCwianRpIjoiOWE0ZjNmYTctYmEyOS00ZmNlLWFhZjktNDZmNjVjZTcyN2Q1IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjIyY2IxNzA2LTM0NGMtNGFjMS1iYzczLTFhMDVmMTk2YjkwNSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.W7DbOfPj-9P8k7Hv-5byHJKvt2bfJZ2DiiIQ92Vm0SMUG0tyn4ixM1z5MLaxMnZxbRsHEaZQ9liumpUrBFA_OX00FfpGuaRsc9lKSMa2taU-CNstqSVb8CACrlxJ58X1h38Xdfovfu0h7dQWL4eHa1QwiJl8GUhvi-ob97mo31pbbe5mHJ7f3UrM9XQwqkodVa2LI7H76_6OlcHnsgOVeYEZ9lBe5eNqu_op2vy86R9gZBPLckty04_3rk1ogR7yWlXh8Y9d_Bhm_8yyvn_rTaCcmuMUGH06XvcoH4MbU3l0WtCZxSjqzitowELqvttw2GNe5PkTDmBR1rq3MhLz7Q") // Fixed Headers
                .get(baseUrlOfSut + "/media/medias?ids=69&ids=-769095646")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(1))
                .body("[0].'caption'", nullValue())
                .body("[0].'fileName'", containsString("Sam-Z_Flip_4.jpg"))
                .body("[0].'mediaType'", containsString("image/jpeg"))
                .body("[0].'url'", containsString("http://api.yas.local/media/medias/69/file/Sam-Z_Flip_4.jpg"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/media/medias
    */
    @Test @Timeout(60)
    public void test_1_getOnMediasReturns1Element() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/media/medias?ids=416&ids=890&ids=855&ids=984&ids=1")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(1))
                .body("[0].'caption'", nullValue())
                .body("[0].'fileName'", containsString("phone_category.jpg"))
                .body("[0].'mediaType'", containsString("image/jpeg"))
                .body("[0].'url'", containsString("http://api.yas.local/media/medias/1/file/phone_category.jpg"));
    }


}
