package com.yas.customer;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class CustomerApplicationTest {

    @Test
    void testMainAndConstructor() {
        CustomerApplication app = new CustomerApplication();
        assertNotNull(app);
        
        // We can't actually start the real spring app in a unit test easily without context loading,
        // but often context loading is enough.
        // There's usually a CustomerApplicationTests generated by spring but let's just cover the constructor here.
    }
}
