/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T04:46:19.851591479Z[GMT]
 * <br>
*  The generated test suite contains 13 tests
 * <br>
*  Covered targets: 40
 * <br>
*  Used time: 0h 2m 0s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_product_admin_only_others {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (400) POST:/product/backoffice/categories
    */
    @Test @Timeout(60)
    public void test_0_postOnCategoriesReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"name\" : \"OrDw9\", " + 
                    " \"slug\" : \"tHgbi\", " + 
                    " \"parentId\" : 111, " + 
                    " \"metaDescription\" : \"F2m2We\", " + 
                    " \"isPublish\" : false " + 
                    " } ")
                .post(baseUrlOfSut + "/product/backoffice/categories")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Parent category 111 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (400) POST:/product/backoffice/product-attribute-groups
    */
    @Test @Timeout(60)
    public void test_1_postOnProduct_attribute_groupsReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"name\" : \"MG_WelO\" " + 
                    " } ")
                .post(baseUrlOfSut + "/product/backoffice/product-attribute-groups")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Request name MG_WelO is already existed"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (400) POST:/product/backoffice/product-attribute-value
    */
    @Test @Timeout(60)
    public void test_2_postOnProduct_attribute_valueReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"productId\" : 3537675678149538803 " + 
                    " } ")
                .post(baseUrlOfSut + "/product/backoffice/product-attribute-value")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Product 3537675678149538803 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (400) POST:/product/backoffice/product-attribute
    */
    @Test @Timeout(60)
    public void test_3_postOnProduct_attributeReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"name\" : \"FZF9oikwTL\" " + 
                    " } ")
                .post(baseUrlOfSut + "/product/backoffice/product-attribute")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Request name FZF9oikwTL is already existed"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (400) POST:/product/backoffice/product-options
    */
    @Test @Timeout(60)
    public void test_4_postOnProduct_optionsReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"name\" : \"y\" " + 
                    " } ")
                .post(baseUrlOfSut + "/product/backoffice/product-options")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Request name y is already existed"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/backoffice/product-variations/{id}
    */
    @Test @Timeout(60)
    public void test_5_getOnBackofficeProduct_variReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .get(baseUrlOfSut + "/product/backoffice/product-variations/280")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 280 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/product-variations/{id}
    */
    @Test @Timeout(60)
    public void test_6_getOnStorefrontProduct_variReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/product-variations/810")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 810 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/product-option-values/{productId}
    */
    @Test @Timeout(60)
    public void test_7_getOnProduct_option_valuReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/product-option-values/684")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 684 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/:-1/product/v3/api-docs
    */
    @Test @Timeout(60)
    public void test_8_getOnApi_docsReturns404() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/:-1/product/v3/api-docs")
                .then()
                .statusCode(404);
    }
    
    
    /**
    * Calls:
    * (404) DELETE:/product/backoffice/brands/{id}
    */
    @Test @Timeout(60)
    public void test_9_deleteOnBrandReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .delete(baseUrlOfSut + "/product/backoffice/brands/692")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Brand 692 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/backoffice/products/related-products/{id}
    */
    @Test @Timeout(60)
    public void test_10_getOnRelated_productReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .get(baseUrlOfSut + "/product/backoffice/products/related-products/275")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 275 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/product-option-combinations/{productId}/values
    */
    @Test @Timeout(60)
    public void test_11_getOnValuesReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/product-option-combinations/40/values")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 40 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/product/storefront/products/related-products/{id}
    */
    @Test @Timeout(60)
    public void test_12_getOnRelated_productReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQxNTYsImlhdCI6MTc3NDQxMzg1NiwianRpIjoiZDQzYzE3NDgtYzMzOC00MzU1LWEyMTItYjI3MGU4NDNkODM2IiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImRkNDkzNjM5LWVjMzktNDFiMS1hOTY5LWEyNGM1N2RmZDYyOSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.BCzgho71BWbHmp2SV9eaRM3qe7vJd5n_Yrqo78huKG0sA6MlVxEbSY77ftdxh3vOt2lEsYkb3sQ5h2mCA23ctsYBkbj2PO8YChqOVNHptKdkHgjCZyeOQ9lfovMKz2V7qvS8ww8hVnAWAiTi5wnhpNjF4uiiWvhug0xi6PDVkbm8-uh6Xu5YMhi9p8caYWeHcONiUlTjGZ2fMsojR0ZvlbDfuzxZVu-jxmKTP9PEKX1BDWeqNTtz9OXGfbD72x0q1umCylherMZuiOW_4xkpZd8P4SLoTElophUgQmgtPpuhnzkFlXAURt9xzV8MRQF4rSFuJ_6rw-qO2qcmjy7abA") // Fixed Headers
                .get(baseUrlOfSut + "/product/storefront/products/related-products/522")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("Product 522 is not found"))
                .body("'fieldErrors'", nullValue());
    }


}
