pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JDK11'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                dir('backoffice') {
                    sh 'mvn clean test'
                }
            }
            post {
                always {
                    // Upload test result
                    junit 'backoffice/target/surefire-reports/*.xml'

                    // Upload coverage (JaCoCo)
                    publishCoverage adapters: [
                        jacocoAdapter('media-service/target/site/jacoco/jacoco.xml')
                    ]
                }
            }
        }

        stage('Build') {
            steps {
                dir('backoffice') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
    }
}
