@startuml Checkout Lifecycle
title Checkout Lifecycle
[*] --> NEW : check-out from Shopping Cart
NEW --> FULFILLED: place-order
FULFILLED --> [*]: auto removed after 2 days
NEW --> [*]: auto removed after 2 days

NEW: place-order
NEW: auto removed
FULFILLED: auto removed

@enduml
