apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: false
    livenessProbe:
      initialDelaySeconds: 90
      timeoutSeconds: 10
      periodSeconds: 15
      failureThreshold: 6
    readinessProbe:
      initialDelaySeconds: 90
      timeoutSeconds: 10
      periodSeconds: 15
      failureThreshold: 6
    resources:
      requests:
        memory: 512Mi
        cpu: 20m
      limits:
        memory: 1.5Gi
        cpu: 1
    storage:
      type: ephemeral
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    template:
      pod:
        tolerations:
          - key: "node.kubernetes.io/memory-pressure"
            operator: "Exists"
            effect: "NoSchedule"
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    resources:
      requests:
        memory: 512Mi
        cpu: 20m
      limits:
        memory: 1Gi
        cpu: 500m
    storage:
      type: ephemeral
    template:
      pod:
        tolerations:
          - key: "node.kubernetes.io/memory-pressure"
            operator: "Exists"
            effect: "NoSchedule"
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 20m
        limits:
          memory: 512Mi
          cpu: 200m
      livenessProbe:
        initialDelaySeconds: 90
        timeoutSeconds: 10
        periodSeconds: 15
        failureThreshold: 6
      readinessProbe:
        initialDelaySeconds: 90
        timeoutSeconds: 10
        periodSeconds: 15
        failureThreshold: 6
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 20m
        limits:
          memory: 512Mi
          cpu: 200m
      livenessProbe:
        initialDelaySeconds: 90
        timeoutSeconds: 10
        periodSeconds: 15
        failureThreshold: 6
      readinessProbe:
        initialDelaySeconds: 90
        timeoutSeconds: 10
        periodSeconds: 15
        failureThreshold: 6
    template:
      pod:
        tolerations:
          - key: "node.kubernetes.io/memory-pressure"
            operator: "Exists"
            effect: "NoSchedule"