---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-credentials-secret
  namespace: elasticsearch-production
spec:
  encryptedData:
    users: AgA92249scq+pjUtCZni1NxrhpOB+LxdIqCUtquWBkdalNj7q526Mb5ujEYg9L/P5pHCYBX09YnrNGCnjKRfSajBUryFgVrNhgnKxn/5BtRIoJ1kuPwbqYZ1408mOP+u229pxD7YfjKxvEG89oxhgjKU+PIPkYmypAOctluiWczOx22PSJzj0euPjwQmmwHP95Qca/5XsvBffH30XPt4T38F3BRTgunjtUc9b734tq6ltg05vQbCgFb5z60QAHm5915IjDF0Q8h1PFB7H6AuZpMGdHAljgkN7UywzCfvjKXjSliZK2E1P+6TmTZYvhT0dcX0pCYFq+9nN0z44HxN1TL9JxHZPW7sufM0qlJe9n+azL70xKG/D44ds2hllw+XiuuNj+423/uFFHqy89/MWq47m1vEbwj0OkZYCgaBjpwQSynXnSBezui9efF9H7x33drQArtF61kpxQZb2F0BZILWCtYXh/zd3hKr4EE6L/GXPdqPHuqbr0NTXpS3FUGlVU1stmmWwL64c0VAH17LeKdnYbFgadtlINizT8+81keLWAiobRjYp3iS+qfg/V+k0MooGbiceYlJOjGs0jiH1ZUIncM0CDr7FQzRddgRkd5oVbBZgEr6+nbgA5A5NGDmTRv6CZWdKd0fqFYmo1JQFsFaUSl9LGyRgB8JbfWtI7J3o1UpmT5rbNe++g3YK74K5XPFXYChYXmKILtvpNoaZ9Z/1VDhvZHnNrtl+i/LSrpQkYKItR8NUsy0vG0pqhV2jhfmK5pextux6HZq0nUlLXq1ow==
    users_roles: AgAArFDDsP7kkA9qBAfcoa1UTUZR0Vzv+r/loU20xAfv51rxkOxTf8q8zwrOaHRTMsKPLHfMrODjs6VaD9KSI3WsTfp/asaV1pwYGlkQCSr5iISwgrX6hPB6T8FvCrEnkfO3Zrj+NSdDam9IkThtWGDbwWpjG7RjjKd3G5Cirwy+H8r2lApK9cr3OoReisK7pjUY/zqEHQJTHd/M2UfBHDuXyqBiMIlXiCKH/nAEaUSUsrgR0nARCQYDNoB17zr7mNvA8+GUiGcXAf2UG/fTw9e5qpeyaTLV9oovsY3dHZQxSlioFQyiUlo7ZVoiV2j0VsqqmTPczDAEO6bDql8YbzEPdGPusrPfkaQtEQ4MPbBfN5y7hFNq6Q/qpdOpxpd8kQ+GfqB5tIyAcg3AUjAS5YtQJzeDfkUBIf5xeOoXEyQvG1dLG7gsrafJYOYLcua+EppFo8tMCNeryx8rlu49pnVVpx451NyieKxTv0kY5EbcVe083FvwcND8tFLvv98argQTZDJ0WKPwW9L6kxMNqPdhEy8iQkfRsC0VQQuoN6OKPCQzBn2ByxVBIZyAQe9tu8CaqoLXotewIRj57lj6CWYYJoEEi/sAplOOgl7TXxGRDiW4DmnDzl1pwaC3UWK4S8UzzgDYk4KoF45qGBZR1oc6Om+Bwz9MY1M4/yHQvBCaUHJQR+7yOTsRp0PzPJnRMFy5iUzaYrKu6kIpF6AhKw==
  template:
    metadata:
      creationTimestamp: null
      name: user-credentials-secret
      namespace: elasticsearch-production
    type: Opaque
