---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-credentials
  namespace: keycloak-production
spec:
  encryptedData:
    password: AgAQAkPInDoo7eT+LmCrF9I2tPgHc+X5NnolLwlY9zbHK/+nnAZuQwZLsw+3ZPXHRkRXr7+uGTfT2CzoNGGt/LXU5d4lHG/jjqgmNtSOnGNfYBPXNZRr1qLxviCkARkxYKMeyfdyTde4hfqGUpgvPzT+UKLSpWKE7QqVbCzGqhpYoPu3m0snB+bPqCrp+CgIdVVIauYi8LW8unXHrqhf2xYeyScxzGuDZ44g8swhu7HgCkQNtkX3p+QxKwYSmABT59cvxz+5kmd1zyhB+Woq01EPGABtbZZr1XhV/Z+Z/M4RHN58zboHABA++nN+rIKszHu/4NXEw0wzydfQyt05AXuCJswmyJUgbzxH5zu6BHv4K6yKgki2kao7HaT/FZlHdH1uhXdOgut/fiuZt7zrJnRGt4T5697cNqgbrCfM+ziDppUpLsbMfl1LZJ4roifBakt//JowwajFoAEIJNF+Qghq8BBsFyUfahfdZOOIKmOsLZUhtSvASd/Tk5kZ6cVPV+m1gi/qVNlOlCxe/rTq+KSsGl9A+++t6Y28amPioMJrFCQJhsgmgypJJNT5MpC3jJglJq5QjKLaSf7ZX90yCJGOR3BK+s6kOe3XJwRPuZekgom8XTrTIXAFXSUObqBxKvz5OaifEs1QjcgP1JUKqmEsnPaYdQDDTjmKONAmJDKYOpFwW6YJ++Hv5Y2c80w5FLsyMAYeEg==
    username: AgB523sSUej0NHdW6ar9mummurDpl07T0QfyXNMJbiCMVJaUdZxnAQ6fr+aWw5St4vk4ENlIz8R54qsTH9n5pSWHdWlFrgeWwoqikzKMCBOyiHntz+KWQe9eIzvYpEQ+b5B9m4UmLCtrcfCGGmLUYkOKxqU4aQlRZbvJDMoq2/aFK+fBhjY+s3twwW5+11MZrgGvUkvM1WTUEpDybGshYgCrcfegZSaBn9I4K9ZAJckrexv+Ip65kPl9N/AfaYoY3FTpVEG4CBI6t3dvSQ6BXWJ6NwIWUZOXglizSs2C6NtrL4cPVMy/2lAUB9wPPzN2uQtTpL12XW0gXE2jFcfeSyOfZsAC67ASIWkA/bAM0l7EOSQuXNxQB5K7gMJimkTkSS83qPuA4dvl95eNGS1rUriHvHG89X9nvfrCbwo+WUELW0KqqDgmTc1lMfn6h68ban47TRyMlk972GSCgShG7JsmRjJi6zjTqZHaz2LL1ZHtZ0+wu1RjXK4xjiDboUriZ4dH/21rK9wqcWqhfobZ7/5+77g3I4El+lhAq3Jb+tq5U9l6hxWMZVn6T6/QA8jEX2mPlUZEMr7EkJYIJvsU6zkcPKW6mhrznk/DRYS7kF+2Ty2ecp3DIqaZfwaBYsIXcok0Fi0QsT1tAz9kFbYGabiChC734koTYGrJxIJ4tm91M3DWyaneG5uO0ZBno+OedS/czr/ydw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-credentials
      namespace: keycloak-production
    type: Opaque
