---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: keycloak-production
spec:
  encryptedData:
    password: AgBNljdIg/kDSiwcgHtaQYS2ri3Gy4wp5bUd4/UGE7TYKLgspxzZ5q9m2TigUlWv2NMPH5g++pgaFNk7u2fuUIxwg/C5P3BcKrCbd05oME7SaSW/KQ0ovVoUPF9wmeouRad/3vUxmKnKv96KTEdQwvTJIs7kA4U2FUIcUDwHtEXMC8ylPM2LS83QfWk8VcJqsnPxrIml/3lMWACloLgrNYgro1uXJ55mX+EQt+q1eq4awvwcUVGXuE1Ephqw23Ng0PeMrzOTYSFhCFetNq9UNFh3MPlRElMIR3qJOLH9rjdGOltJtThGSBPOK9bqt7vN6g22suaj2KYT7GCK4NAOUuadQ46rYRZBggpSzkTHEwcQ5GAS28xZMcuXiJNgvIPFECw+bUP65c1fCKqVSrBcLfd9csAA0yvSMWN4+q/aHw86fgEZmdy2deDPn9ueXzwRSXx78rPlTmlV1zTGG21/DSbk1vFinSIW84jJgKgUaj8zAPBhgROClOb7lUpML8Veal+bG/jsEHDnbhiNoa0tH+ZVC+iwy8NxJc6M2qiFPKVHWRc7NdxUHyn84Yzsq+Wfr/YbouaJapd1+Xt6eMZnLOXa73JNsQZn9UyZG+2i38Kqqs70DA5uErgN3AZZEexcKdcnMmPgGJZKLyFwgv545M5y9AsflSn9h4HdjW2Yi5QXO8cqr/W/bXQDPu3x83KP3R854YUexg==
    username: AgBYxzTATXKkrpoaLZtx71boIN1TeRi/gG3GkDBiBuS0ak6EoQrt0bHelOhfwDlJKHVZcywNVWQrm0x26lfwj2jgtZ/UXBYTq1SW2jlrDGrTm7Vz9m6zzhWS7l8R388Dfj+BpIB/HXl1Iq+A02IIMXdJBwWgDCCP+/WSfR2uVp6qjeAKiThwh3KtF9q51mdgIlRLoNWCKsw8xLaV2CFv94baO4fEL4S4JE2M+yENqubWpp1Bq2dYpkW2sKHU1s5tyP5eWbMkUaapBsbab8SWS/n14IQ9jBzB9pCpF2CsstP/YKOj3uiUXvJblaDz/seXc/fG8itjrKZXeRThATVE3LqCbdAah9eXJdl5amPY1AOjJd/vWBLgZEYJHr6a8ikNqCVYaGzmKYc56LAn51hJLhYXeHnxvHjB9irPcwAbZmeaXFMwtvimUoWkD7lcWs5xn72HGjpMkNRcAnddqSvVGChsfuD3qzss+X+CUl/aCfSndJG6pa8BFGRJsEh3KAXSg/dgqQESjpb90aJid+0qP6eApw+tREt59wtf1zMQHLoJrLwNHBZpevzsKgO2XsNOtEQLcEWXzjtGPYcLKdlqshM0uQC82ykDEuTZQr5zoqpDCj2r/I21qKu+KWjn2aGGzQzytSvDXBCOt0hvMKhIK6E1atsJ+TLsH1utDr/z9k7qxkCiZIWyqD8jF2JUPGyyZmE/TJZu2730K7oygC0=
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-credentials
      namespace: keycloak-production
    type: Opaque
