---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: yasadminuser.postgresql.credentials.postgresql.acid.zalan.do
  namespace: postgres-production
spec:
  encryptedData:
    password: AgB7mVWJA2P4WTEuFREBXTT1ZPigUDL/xTl9LpNw7cuf6t5iyMBLFpAvmCQITH2OXmDKnbcmJ0ycOTiEws8v2EpXgaxuITZAHq4twKMicpafAHa4FyQaV4YU48raLKaOzjg61uomv1vXqRSX5UfdDqHLrgtQB6Hh1CSITiwQXQpWHCKrxugfGwm1WOrrQHbkivHAGf+BNR5OdfxpMKKQwIOaWFoPGYQu8v4wQ7IgfAeMgdZjAKHAI+rdXQmT0mwPrUmkTKltyjtKilq64IjJkOnmQWZZ6h1g927HVbd/1CjuDQHyZRyyg3zZ0gCRyY2Krc49eARFFvxPbZ3SIgv4dIpq3LfjDzICKt41uF28OAXqokYzttzGk4RqWldIAY0sReijlOMUGIB8hszj4d8FmqyszD9RXX9ERJzPmyTYGZ2c15/IfYEpp2Cm4W3qd0N6tLS9JSz5OurQMjnxk0B+HUThaXd5pjBjNEytWwOcZY33tbm5rZrkRVfj7x8iDBiXs3A4krvHkwq0n15VAGlgRUX6VgHRP317adQ+mO1l+mBYdDcPttNFXRf4cWVccHnlspb31z8XjgxPYDAtllQhv19z24ZDHt4SsyPvz95eBZPums7LRijwowJqSKsCIrBSxJGlpoA7bKjFac7vqKJK7kYCxfoU4ulTdMoN8eNCRDIwyU71sFecCrq/KQA3iCXqeivG9JvBOQ==
    username: AgAfWPAU5ogyR5UyGofs+sOxm5Qzr/vvcbR2c3HlVQyTeU82PIZhS7sar8kJPdxmpHeDVshkBp2CH4G62QhiFTHCiPgzYQXhM+wR6X4nCce7Uzg4KlL2fAienmib/BCMQy4SSK80xp/JjgvTE5dbFbIuWGCa2p5DRMzQjnqblcPWIMVssNOhKKTFUObHyIez8lZ1OFAel6o/m9Q3KUW7X5t8s0VHYtkeqU/FbIwUo8Stt/DKpygp0GGdDJiCv+kKBTjiZpyhKdBJTUbQEQr+d+hRF0SylNGwzn1lyyW3aRcCNLYZ5tCozh3uvU6Y73i9Z1/tUowBjW63rfiLWyjvCrkr9ufA1QlHplZs8YbKGWMHk8Q+X/tPosk+suHPosfLGAA3GApecAmuPGcFraHUKZembsEfu2sWZ7+SiL3/lJOMNxzH12QHuZltpKRp2zUIgOBBJ2XTR1scOdBUudou7q9/Tn9f16EcB/siuLnrx18q5jUpSuffwiMQKisP4Ek73IqC0e4n2jt52sBeiaFB8BtCFy+Axqs1v98rMxNtJmWy9cOKa4toVsljMQCx27cO4tYdAdwXZS9Ibq6jOPjLcrq5C+Aqxvo2jdJ2Q/XvAM3yz6SguOUh/auZpLdg7HBpisppyElN6OLETc8O7bScf5zJrtdo6pewaz9yKnEZxyMyaIVzdfqCk+5FvRdC8mVkPAmg2LFoomjLb4ylzFI=
  template:
    metadata:
      creationTimestamp: null
      name: yasadminuser.postgresql.credentials.postgresql.acid.zalan.do
      namespace: postgres-production
    type: Opaque
