apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-yas-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/23122004/Y3S2-DevOps.git'
    targetRevision: dev
    path: k8s/charts/yas-umbrella
    helm:
      valueFiles:
        - ../../environments/dev/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
