apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-cart-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/VyBui13/yas.git'
    targetRevision: 'v1.0.0' # Hoặc tag release động do nhóm cấu hình
    path: k8s/charts/cart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
