---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-credentials-secret
  namespace: elasticsearch-staging
spec:
  encryptedData:
    users: AgCdit8G9MwkYhJXanNwlDqsf/+WhXUEbSvglJCt9VSWcFWUYgP/KenqDga+ruZqrJGScDo9Z70V3I5gyN1+gdpBt4nUyf5jXWb0pHj0WT80dzheUHcs9dc74g3CIP+F2SZIe1sDqY77cHC1HcwJcyPV4EKrLsQ6Z7u3wk6mbgfKTD/UAuIYVaWww54+ABAbwOLkzSlozDlvNr3G4uY6nuyKNNxtkPr757x6fcP6FNaZze/+isHKRm2eZk8BqnJXBo56DL2OXDPH8w4U51rLHJPWYa7CIx7noudh3vG3OzQlqUeZfc/8jioRM8jilxxYeyUhUkib6OcLfb/XvMqDxzW5Fr6mMQC7kFaUmOuSSm6hVMHoqTh91lYiEgwn4FZyA9OmOa/KrClbkZ4Ah5jgj4HRom6F3OtzNoX9zgUSn9MNMUD48KdXtoESQHE5Lrq+WDavCq1iblpxKtPZFUpS38Mt7wJ0M3pTe82ZJ8UG7Kfku53sih6C1MBoywOBxjn1MYBlV+/TTf1sgPmyoPshKidXRAkrdSaPwg+jZE792vdUbSgSBm1bK/nnReEkhA/XBRXTtutTDvn5vif6h0I5ZE5+0aotRJcjbtPeXcUe6694pSUUcETEI1dNjmk4UUMXEtCoaiIESfHqjOYGYkwwCEdIKdqaRAA/ZArmPen5AaB7oN8H3Xdt08AGDG4XHOAKjFyeor6JC0Zg0Ir07HpMaFMhZlQXVZGuIKPur1i0jHZjz1UN3ose1SB0UVUEhRzTxC6hGtHaXYZLakd5A4XDsnB4qg==
    users_roles: AgBwqBL6NLSKRfruzKnxlq72LoJ2cJ2tXaPs5v65mgWge7g+Mju6q2blDdnVLba+PYDs6wcSVACxJh2Ky65RTHubrXkUeNo5ZptJFj5OpC3QOufms/yI2pg2JTI14+JmNU5yogOBRKV9suJbK8qxf4deTJmGgpvoGhhIuNV1XgAtFhraoH1Hf0grNJyJS6uX9L+1xLEI3gbKHP/itvTQuOqfVg2Mx4Tc7eU+lDZrRx1wOvrdRQSAG3wcCOTJTMlPyWf1A+j2Un3dypA2J5Nadg1t2cZ/bCazWKgKVVQJtvajFNdJTO/LkdYlOKn9MwlXG/tFQCtRMZw/bETTnaSeOUO7+oKKGWrI7RqXpKib9DhnPacsJzVY4ThnOzVF2XdN6+OzFBgCVZhc/w61gcafNnuwVALrirSASN8F0URQM9PGrfWLM6iROc5u5/H8t0DYPJhvg9agNs17RsIHAp/AGzF53rOxoouHu6B9vwhsxG918cGaAzK04gLYBgjTHoVNSGlHEUEANdksVxB1S6gKLF51ki8QzPxgTvvGnINIfLmOr2AGSVNPWyMbOBQ8D1rRpVoA67wB14/ShoWxGFZCX4TZfEwCEDgj2OFZLwZfYUHOoX+nzD+rEs++EEazWuKVX0nAeAjZI3xEMH0R5PVRknFYtYruhARG0n/ldQZVfIzbe3idBXab34S+B6hoGeJKgyC4Zs2yLkNsAdxS937BVA==
  template:
    metadata:
      creationTimestamp: null
      name: user-credentials-secret
      namespace: elasticsearch-staging
    type: Opaque
