---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-credentials
  namespace: keycloak-staging
spec:
  encryptedData:
    password: AgBUCkke5A8v+l6WTQXiW6iG/nx/sO5lxYq2ickVyjUeQbKJFqMee+7GMAc3zAJUjkyHgTs4w/WDJWx0eqmewLjUFkDyZ4RznpzRD7D/psEB90Sm887DgSpIQoPDH7lQNXulxm1LmwFuCI9SBJpSkfKrm9R+zWVK6mJp2xrh3C3JUb8PQmO+3xfrPoRwRM/LfKgc3TmHPnkINd3N7Lq7Sr8Ihc8ueQemnRmnDqURS0eJclXuasmpgORY2dzG1GsEK0/X2nQutiZbz+0cVFis6wwEHhcM+AosZPs6wJ7KxDnHItdI4870LM+rNZCDrJGmzof9ncZ2gUUeNTIbHLnVhFh/N5n4uQKPKOA+dgVxFrfdXOD2XNNEC6Iv+jwLcznnDkt3J9hw9clPIJXBzgdYkVt0EQ6+hroRzGklZBIiNEi3ms+IG5XjhZl0wjs4UqDvs+kv0KXCh3kIB/JNBDsrjkB9FYwxjLnjcdjDiQPICQ8ZpWI0R0gSeCZlN4Q6sSSDntSnh+xweg/ePV/S++yRTlh2DT4/f37hyQB1MYgLB5rKYGcvcOWt3/q3OgwO3a2iG87Vsfu85yRzvQTp3aC5gtOBp0jz862cy6MRWtGvIvw97Thw8766Aoxl/WPjWns27A0CIYSccKMMXKK3x9GzF5jKbQsQVBEWVYbZRE4h9c7PH5wRDWcbRphmK7lmfWeXU2z2jFpv2Q==
    username: AgAEA7W0uLEovimZD7U0lwPeiQ1o9pSsbAb9qM+0EBVqdekVNIWKwqVXsst2P7YIHnqrIj8zlyNpxu7B2BZX7Rpg0sM+w3gelLeKZYmkGIcfKLtV0uAiDzwj3vqQ+ZXw1H+Rx9G87xBpDOfYQ5QcfAW/1C8EYSmaWSdDzGx1EZHXxZe8hdBG0obA8cf9/16/skXD3LhZ6JsJIxOB5zf7mwnxt17DOLzsP7hW0snC5dXlRd2vPHlJt/llu0QGBzXgyeucwSoTA3IVQbVRJ7PyreX/gB3h5WKhee7u+qhjkEmzw/V/4YlhDfuspfB/aKX6t5jGCHFZpOjgsjrT5l37vkWd8jmLVIyGAOfW6rquEyx61RH/wLiSEFEq3k5VI4i5bvO4Po3KBmgBS1q7hPrvBw+rxGLLa3vUtIDaWQrYuYxn/t7cF/DRVsd46Uye8rBU0WnxOxPjQw1pQk9B/gQAZwhe/tn3mypRhYzGSAfJa+/GcUoFVDfe9BocG7bnBqY+OvZhF+651QBMDuo8ALInGPAJPzMlTYo9UwtDhMSkm/7xdz8OCnVxtRAHF62I2EbAT9P6ApAParE/uPO5okr4dFJVnKnFOWg7SOtgIf6xRkDp+j/2Vnap3+n1Os3u+L0604s2UvU9Gk72b5/9ZC0s7uFzh51Z+g3R+EOloigfqlN7LlqdWfmLG5tGlRSxflPGfJhiGHEyQA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-credentials
      namespace: keycloak-staging
    type: Opaque
