---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: keycloak-staging
spec:
  encryptedData:
    password: AgAHhITMs7HVkO7tXJ+RduZ8Gm/LLdCmk6B2FJMvDjCGxK//u5afGS8z/k/+IKOCGwn9rAAwxFyp1m23FiBBGfOxVprAQDkKb2dbK7wQbxKonUJc8c60eZJs5PW8CoImYVKFGPN8RT4MAnsg09mM4ZyvTBSgdPH2EXXJ74wNRzOyzUngn+JQ7SoDLlv1JIHpgJFzLAlrY+blbK+tmOhyv43tOOLf2o66ohijcaCkuSbOTJFWQDNkwjLS00UXbLHi2AUASNoJA4/Dqjf4DVjbB1taDI9U1//GT2gihrOa+/yoTXIAEDR5B/SGfJiNXspl/8Eg9ARDJFBm1PhohzFn5uGTHHdBSLNZW/G9kS8KkvMMLH/rDptYAXGTcbOZ3p47yIms7zCVw9rVp8VgmnJcqQUh5YqiDiGNlIoAFTVdcMwChylETzCFfVI5wtteXjwu+RCUNl3xpL8xhW2leM5ZtA6Gi4e+C54AjmCj4Nlco0zpZMTJmq+GkDsvc9QAhXY7roIh31rorleHBV1zUunPX5IVf4XyNUHQXyfSP26GvKqpKMv94o2ej0CDhnfCsUqu2/NatK7NksAeLpE4+594qQtDIZMcqcwv0tEKsfEkQIG6uHvjlSAJY9+0xixmaR7HLkRAgsWlw9j/eNPFcCi62wOScYdhNk3ZMOBCMEjZbEOusb6bUOK9XSmwNA59tAJ0cnxQTc8vSw==
    username: AgBAJ67x2sW8GkQ0RNHNDYKBhOonazEPftRJiBaJyjoYSSvgEAVRPfbcYDZfJLcsTyAXpU84iqJdMCAvF0OrczcXB0xgchXxK3tyMRRZq3V1WFQfwVDurfq1VbkrUzA+vqJXwvxTXG7iJ0bMgAnayO/3IY86x3tD5I8s10RkOB/spID1wlzIOpbj5ueP3pkEU2GBllh93+hz0lPe0tgqlmUJHzZdoE/Ca/VIEYtBkX7sXnsd7x6EliwJhwaGlXnHonBPDSwPqBrCUUjIEMq+WXIz98mEGbabYxn0wikmY4oHbE3bXUSeZrf3YoFuDRZY8VyhFk4dVauucdcNG2ky0rqwPDukkCmyrSoKUw9oTWOhXJiupThGyvU5MC+sy4SYZoeOK5CkR5Iw+u/lvghhY1Vbx3wxmXvm7OigEPjQbCIjsKiqImM3LFfE3Nh7CBu1lF7AVrEBMCCID/WeE+DoP1SiC+dAc413fm6fZ7K1FwPJUFv7UbMzGGzxSJBra/bEHp6QLJBB0Aw1qrzkaoCrWcGQ1jI5LuFcPgPciTIFjTmhLjZEEOOzmwiSLl5+D6X5xRr2Zfrv3wwS59aiKtz7GB2O52J5JFt1doQkqPmhKHiC8DAMWvTzjFWXXYINF3iYDjGXAq42ExsqgeyjqDcw2rCisVSQgozm8f4Kiv9Yup5BYHv0YgxNUoXY736RYg40nK1lQIq6Ay3EwhEbDok=
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-credentials
      namespace: keycloak-staging
    type: Opaque
