---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: yasadminuser.postgresql.credentials.postgresql.acid.zalan.do
  namespace: postgres-staging
spec:
  encryptedData:
    password: AgBMI8pQf4iEqFjMYASxvsp0AdNm7m4TCsq23TvZWi7+LdZIcoKudzFf27m78/SXsDLi01xSgVHSIPs1OfIGd55+k89tCCUjQVytP4WYljtuSjBikJSORBYAwWnVD7H/iQmSxLdMovfyhqWV4sYQMuzxoPZXFo0TibAOMdLOH/AEGHQowEO9VVrX0KCQ9bD9t6qzqlBcGfkFJwS7baob9bYr6Ky+6t58nlavOh+PfBRVt6ha6h7URQSKPdEIFhcR7CwcL1Hy4OBCzmyhqDEtMIvZhMiKZF0PM9BbwSApYEDvL9XhDufOl3Mh0eMvpexbVUuxUNTIEJ4p2uFB1RACFAW3wyHyyfiK5lCQxn9X8UYFnOO3nIFtUsvqu2nsYX88OCRtS8TaS9luQzASgyzqZKit9ORVlwbuTvrq7EZu4oazSv95teOI+a6tVX4ucjTC4rxLydi3bR37TagGpeZI8qVwiGcLoFzmP7EOa5lTQ8avEJp3J4LKstBzvu2NeGMGBRfk7NK0PmpMnpvNgnU2pXTFjcv9Im3ysLkVmQfXK3djiPwc20kpbUNmtEHVhOoTjpWl3F8e/eYAefGqYrydqRw9/bzw/tqpx7is8dZJHK4zEXRMejpTf49EPcMf1OTj12h8r8fK5Gg5Y7aqyJpt9C3fhZc/Cqqn0WRTtLA5Je9wwsgKzDAi7lp5b/In/4UFmS9xvZPwqQ==
    username: AgCL+bxQRbCIumkxX8vQ+t/KBwbPSiTHeCu87803QRv/kluFp7ccaryrtvC+aTxVs4K11G42YDRswaykIIUSrDRgQNE+LMr7+63K4FH4OM/ZQiiiR5iabNh35cAdFcxktTdYQNL08Qite8uV+wczIcUmXYgdhpvTRwbPMYp2gsJvWVYYt5n9JJXkGW8/gVLBZO5A6a94cfQ/gYGQn5nYFjIcPtKkhLczKu5cqs9KXbgz4rSU3U5lgrO2GVe4YJf57w+2nO4J1atwCqRqyrOhJYofUK67JCX1SseKV0ep/2H8hLBII/LjbcGwljINLdaLBuR/oWwWeY4ltskeASmwr4R94mVk5e9cT1UsWVyJgNN7l8WvWRd4xBmPG2T+UneTkkGjy+RKgLZDCy8WvZUrg4ETnncs0S/Pb96GCM9mrrf3OT/Fdlk2MgOIzJJKe+qfFwKcavmGdWv2OCv859kL08d7TyX7/N456Pbj2QY5+JKHcuU3uT/8AElovEE2dA0nqZR1wE0ABPclDzfeU+YywQtZN/cPIm3CBKSNYGFmEZsJO8qz6Lzz/PXa1Ao3qUw29RBmWlOJ0p4y/QKG6Puu3GXurg239DTH9NGV5uSUuXHPsU1ci9Ybq0ebIXUPxzMc3ohMWM7v9wWYrxvk3DyHrX0/veY0dknDt9xdpqvHD1/ykc4kfA7Gbqk+leHbVp2f28CyP57ygOEMbXQEOls=
  template:
    metadata:
      creationTimestamp: null
      name: yasadminuser.postgresql.credentials.postgresql.acid.zalan.do
      namespace: postgres-staging
    type: Opaque
