write:
  replicas: 1
  nodeSelector:
    type: heavy
read:
  replicas: 1
  nodeSelector:
    type: heavy
backend:
  replicas: 1
  nodeSelector:
    type: heavy
loki:
  commonConfig:
    replication_factor: 1
  auth_enabled: false
test:
  enabled: false
storage:
  type: 'filesystem'
minio:
  enabled: true
  nodeSelector:
    type: heavy
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false