grafana:
  adminPassword: admin
  adminUser: admin
  grafana.ini:
    database:
      host: postgresql.postgres:5432
      name: grafana
      password: admin
      ssl_mode: require
      type: postgres
      user: yasadminuser
  ingress:
    enabled: true
    hosts:
    - grafana.yas.local.com
    ingressClassName: nginx
  nodeSelector:
    type: heavy
hostname: grafana.yas.local.com
nodeExporter:
  enabled: false
prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    nodeSelector:
      type: heavy
