apiVersion: v1
kind: Service
metadata:
  name: storefront-nextjs
spec:
  type: ExternalName
  externalName: storefront-ui.{{ .Release.Namespace }}.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: backoffice-nextjs
spec:
  type: ExternalName
  externalName: backoffice-ui.{{ .Release.Namespace }}.svc.cluster.local
