kafka:
  replicas: 1
postgresql:
  username: yasadminuser
  namespace: postgres
debeziumConnect:
  image: ghcr.io/nashtech-garage/debezium-connect-postgresql:latest
  buildImage: false #Enabled when build debezium-connect-postgresql image