/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-23T17:40:51.310563220Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 8
 * <br>
*  Used time: 0h 1m 2s
 * <br>
*  Needed budget for current results: 3%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_sampledata_customer_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) POST:/sampledata/storefront/sampledata
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_0_postOnSampledataReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 200 not defined for path '/storefront/sampledata'.
        given().accept("*/*")
                .header("Host", "api.yas.local") // Fixed Headers
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQyODc4ODYsImlhdCI6MTc3NDI4NzU4NiwianRpIjoiMzcyZTk1Y2MtOTAyNC00YTg2LWI5Y2EtM2I5MzE2ZDNlODJiIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImZiMTA5MTNiLTY4NTQtNGM4Ny04NTc3LWVhYTk1ZjhjMWIzYyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.CBAC8lxpgZxSCPJnX9DsC4SBxDOI-Rm_c0hHOboP-8TBm9KVcND3bbF7r_5mS7E96VUFC-qwHlOndlC6jDwRor2BSAAB6tFLGZRDYpQ2YNLONMV9pz1zsvCWHCUGVCs7HCCFztxTIA5VRKOehDidOQsofJFP2_xMs6WCNvUncBZHX4bhCopKS5z-S4PXlYzdHWniHWwuR1GTSnE8cis6wkn38XdV0ur7PBSl24tLMo6slgAh9S8386ClgyBFIzxKzMTwfrq4PGBWVoqPUJeSo83UI_h5NFTnXhIsYFg08CnuH98yBznhH9AQbEqH19u2uQ9v9bVCGAZ-Bi7gMXtZ7w") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"message\": \"MJdZtMDGEUH\" " + 
                    " } ")
                .post(baseUrlOfSut + "/sampledata/storefront/sampledata")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Insert Sample Data successfully!"));
    }
    
    
    /**
    * Calls:
    * (200) POST:/sampledata/storefront/sampledata
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_1_postOnSampledataReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown. Response status 200 not defined for path '/storefront/sampledata'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" {} ")
                .post(baseUrlOfSut + "/sampledata/storefront/sampledata")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'message'", containsString("Insert Sample Data successfully!"));
    }


}
