apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: product-istio-mutual
  namespace: staging
spec:
  host: product.staging.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: cart-istio-mutual
  namespace: staging
spec:
  host: cart.staging.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: customer-istio-mutual
  namespace: staging
spec:
  host: customer.staging.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: inventory-istio-mutual
  namespace: staging
spec:
  host: inventory.staging.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: media-istio-mutual
  namespace: staging
spec:
  host: media.staging.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: order-istio-mutual
  namespace: staging
spec:
  host: order.staging.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: search-istio-mutual
  namespace: staging
spec:
  host: search.staging.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: tax-istio-mutual
  namespace: staging
spec:
  host: tax.staging.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: storefront-bff-istio-mutual
  namespace: staging
spec:
  host: storefront-bff.staging.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: backoffice-bff-istio-mutual
  namespace: staging
spec:
  host: backoffice-bff.staging.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10

