apiVersion: v1
kind: Service
metadata:
  name: storefront-nextjs
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: storefront-ui.{{ .Release.Namespace }}.svc.cluster.local
  ports:
    - name: http
      port: 3000
      targetPort: 3000