/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T22:37:39.619054892Z[GMT]
 * <br>
*  The generated test suite contains 4 tests
 * <br>
*  Covered targets: 12
 * <br>
*  Used time: 0h 1m 59s
 * <br>
*  Needed budget for current results: 86%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_inventory_admin_others {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (404) GET:/inventory/backoffice/warehouses/{id}
    */
    @Test @Timeout(60)
    public void test_0_getOnWarehousReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIwMzcsImlhdCI6MTc3NDM5MTczNywianRpIjoiMGRjNDM2MjEtODUyMC00ZmVlLTk5YjgtN2FiOWU4YjMwODEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImY4OGEwMDQ5LTM5M2EtNDg1My1hNWY4LTc4ZWY3MzJmNTM3NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.SvGtna8JbQbe0I0BQfj-k4R682B6JfUWddrGYjU4aiIXiYFhpVabXD7uVpQtfeYQ1oojJSKytnN-gw17kuwUbAqRmypP0QbmRk06kfvi_dS2JlCIyJsHCNLKnAHuuODrDf_gCjYfkRxd8mGmAlO2K36BCFk59jOsvFTGEpdfDOT3HKJkWDUYs1r4uTeJMkoWP9F-D2H8Bmn9cu0t1jPhQHne8-_h4-c0lc5p0O4YJk502HDxrsw6MXIb-nRz5j_ygefgKwcYB5BFClmND5QyxBZ_rEhw_bVGh9N2ij7Z-DDS7BdcmTatlrX_6bC0rr0a2zfEDe69qQpp-V3DVHM3kw") // Fixed Headers
                .get(baseUrlOfSut + "/inventory/backoffice/warehouses/47")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("The warehouse 47 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/:-1/inventory/v3/api-docs
    */
    @Test @Timeout(60)
    public void test_1_getOnApi_docsReturns404() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/:-1/inventory/v3/api-docs")
                .then()
                .statusCode(404);
    }
    
    
    /**
    * Calls:
    * (404) PUT:/inventory/backoffice/warehouses/{id}
    */
    @Test @Timeout(60)
    public void test_2_putOnWarehousReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIwMzcsImlhdCI6MTc3NDM5MTczNywianRpIjoiMGRjNDM2MjEtODUyMC00ZmVlLTk5YjgtN2FiOWU4YjMwODEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImY4OGEwMDQ5LTM5M2EtNDg1My1hNWY4LTc4ZWY3MzJmNTM3NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.SvGtna8JbQbe0I0BQfj-k4R682B6JfUWddrGYjU4aiIXiYFhpVabXD7uVpQtfeYQ1oojJSKytnN-gw17kuwUbAqRmypP0QbmRk06kfvi_dS2JlCIyJsHCNLKnAHuuODrDf_gCjYfkRxd8mGmAlO2K36BCFk59jOsvFTGEpdfDOT3HKJkWDUYs1r4uTeJMkoWP9F-D2H8Bmn9cu0t1jPhQHne8-_h4-c0lc5p0O4YJk502HDxrsw6MXIb-nRz5j_ygefgKwcYB5BFClmND5QyxBZ_rEhw_bVGh9N2ij7Z-DDS7BdcmTatlrX_6bC0rr0a2zfEDe69qQpp-V3DVHM3kw") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"id\" : \"607\", " + 
                    " \"districtId\" : 270, " + 
                    " \"stateOrProvinceId\" : 169, " + 
                    " \"countryId\" : 602 " + 
                    " } ")
                .put(baseUrlOfSut + "/inventory/backoffice/warehouses/607")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("The warehouse 607 is not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) DELETE:/inventory/backoffice/warehouses/{id}
    */
    @Test @Timeout(60)
    public void test_3_deleteOnWarehousReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTIwMzcsImlhdCI6MTc3NDM5MTczNywianRpIjoiMGRjNDM2MjEtODUyMC00ZmVlLTk5YjgtN2FiOWU4YjMwODEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImY4OGEwMDQ5LTM5M2EtNDg1My1hNWY4LTc4ZWY3MzJmNTM3NSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.SvGtna8JbQbe0I0BQfj-k4R682B6JfUWddrGYjU4aiIXiYFhpVabXD7uVpQtfeYQ1oojJSKytnN-gw17kuwUbAqRmypP0QbmRk06kfvi_dS2JlCIyJsHCNLKnAHuuODrDf_gCjYfkRxd8mGmAlO2K36BCFk59jOsvFTGEpdfDOT3HKJkWDUYs1r4uTeJMkoWP9F-D2H8Bmn9cu0t1jPhQHne8-_h4-c0lc5p0O4YJk502HDxrsw6MXIb-nRz5j_ygefgKwcYB5BFClmND5QyxBZ_rEhw_bVGh9N2ij7Z-DDS7BdcmTatlrX_6bC0rr0a2zfEDe69qQpp-V3DVHM3kw") // Fixed Headers
                .delete(baseUrlOfSut + "/inventory/backoffice/warehouses/191")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("The warehouse 191 is not found"))
                .body("'fieldErrors'", nullValue());
    }


}
