/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T02:06:43.946303668Z[GMT]
 * <br>
*  The generated test suite contains 8 tests
 * <br>
*  Covered targets: 28
 * <br>
*  Used time: 0h 1m 59s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_location_customer_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/location/storefront/countries
    */
    @Test @Timeout(60)
    public void test_0_getOnCountriesReturns245Elements() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MDQ1ODAsImlhdCI6MTc3NDQwNDI4MCwianRpIjoiMTg3MDAxOGItMWY2Zi00NzgyLThhNWEtYzdiMmNjNTZhODUxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImE1MGU4Y2MxLTYzNGQtNDUxMC1hZWQ1LTFlYzhhYmY0NzRkYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.UAGhBstbYe74-e4RrbQ6CWoJne2xdORrIVy7b5_NsZ2hU4HJ1BEEc08QveNosmI6NB4DNgfnoFmKAmwC96mrRMkGFLOGTz0JA60LMI6r_Ge6TtaP9fXqpQ8aQY7GKeXkbpf0JcVT3DpSq3NS_Sik2nGY-B6rG3FNMft5joxH3IdCfp9zrmw7obXAS5zUlVXFOyIfFkZWZmJFDKceErNicybeCTGZSELkCNHd2MpyL-auiIPCOeNeZxQGgySJLWczoIC7JTdG_ue0hceDFVkX3q0e4v8TJ-1tTTviGFiAi44cB1rNbVCxdpLI987GgGDKTasU8a8NInbERjpYevwn5g") // Fixed Headers
                .get(baseUrlOfSut + "/location/storefront/countries")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(245))
                .body("[0].'code2'", containsString("R  "))
                .body("[0].'name'", containsString("9TVao9wdrWsO0JES"))
                .body("[0].'code3'", containsString("aqC"))
                .body("[0].'isBillingEnabled'", equalTo(true))
                .body("[0].'isShippingEnabled'", equalTo(false))
                .body("[0].'isCityEnabled'", nullValue())
                .body("[0].'isZipCodeEnabled'", nullValue())
                .body("[0].'isDistrictEnabled'", equalTo(false))
                .body("[1].'code2'", containsString("AF "))
                .body("[1].'name'", containsString("Afghanistan"))
                .body("[1].'code3'", containsString("AFG"))
                .body("[1].'isBillingEnabled'", equalTo(false))
                .body("[1].'isShippingEnabled'", equalTo(false))
                .body("[1].'isCityEnabled'", equalTo(true))
                .body("[1].'isZipCodeEnabled'", equalTo(true))
                .body("[1].'isDistrictEnabled'", equalTo(true))
                .body("[2].'code2'", containsString("AL "))
                .body("[2].'name'", containsString("Albania"))
                .body("[2].'code3'", containsString("ALB"))
                .body("[2].'isBillingEnabled'", equalTo(false))
                .body("[2].'isShippingEnabled'", equalTo(false))
                .body("[2].'isCityEnabled'", equalTo(true))
                .body("[2].'isZipCodeEnabled'", equalTo(true))
                .body("[2].'isDistrictEnabled'", equalTo(true))
                ; // Skipping assertions on the remaining 242 elements. This limit of 3 elements can be increased in the configurations
    }
    
    
    /**
    * Calls:
    * (200) GET:/location/storefront/addresses
    */
    @Test @Timeout(60)
    public void test_1_getOnAddressesReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MDQ1ODAsImlhdCI6MTc3NDQwNDI4MCwianRpIjoiMTg3MDAxOGItMWY2Zi00NzgyLThhNWEtYzdiMmNjNTZhODUxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImE1MGU4Y2MxLTYzNGQtNDUxMC1hZWQ1LTFlYzhhYmY0NzRkYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.UAGhBstbYe74-e4RrbQ6CWoJne2xdORrIVy7b5_NsZ2hU4HJ1BEEc08QveNosmI6NB4DNgfnoFmKAmwC96mrRMkGFLOGTz0JA60LMI6r_Ge6TtaP9fXqpQ8aQY7GKeXkbpf0JcVT3DpSq3NS_Sik2nGY-B6rG3FNMft5joxH3IdCfp9zrmw7obXAS5zUlVXFOyIfFkZWZmJFDKceErNicybeCTGZSELkCNHd2MpyL-auiIPCOeNeZxQGgySJLWczoIC7JTdG_ue0hceDFVkX3q0e4v8TJ-1tTTviGFiAi44cB1rNbVCxdpLI987GgGDKTasU8a8NInbERjpYevwn5g") // Fixed Headers
                .get(baseUrlOfSut + "/location/storefront/addresses?ids=882&ids=701&ids=286&ids=934")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/location/storefront/countries
    */
    @Test @Timeout(60)
    public void test_2_getOnCountriesReturns245Elements() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/storefront/countries")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(245))
                .body("[0].'code2'", containsString("R  "))
                .body("[0].'name'", containsString("9TVao9wdrWsO0JES"))
                .body("[0].'code3'", containsString("aqC"))
                .body("[0].'isBillingEnabled'", equalTo(true))
                .body("[0].'isShippingEnabled'", equalTo(false))
                .body("[0].'isCityEnabled'", nullValue())
                .body("[0].'isZipCodeEnabled'", nullValue())
                .body("[0].'isDistrictEnabled'", equalTo(false))
                .body("[1].'code2'", containsString("AF "))
                .body("[1].'name'", containsString("Afghanistan"))
                .body("[1].'code3'", containsString("AFG"))
                .body("[1].'isBillingEnabled'", equalTo(false))
                .body("[1].'isShippingEnabled'", equalTo(false))
                .body("[1].'isCityEnabled'", equalTo(true))
                .body("[1].'isZipCodeEnabled'", equalTo(true))
                .body("[1].'isDistrictEnabled'", equalTo(true))
                .body("[2].'code2'", containsString("AL "))
                .body("[2].'name'", containsString("Albania"))
                .body("[2].'code3'", containsString("ALB"))
                .body("[2].'isBillingEnabled'", equalTo(false))
                .body("[2].'isShippingEnabled'", equalTo(false))
                .body("[2].'isCityEnabled'", equalTo(true))
                .body("[2].'isZipCodeEnabled'", equalTo(true))
                .body("[2].'isDistrictEnabled'", equalTo(true))
                ; // Skipping assertions on the remaining 242 elements. This limit of 3 elements can be increased in the configurations
    }
    
    
    /**
    * Calls:
    * (200) GET:/location/storefront/addresses
    */
    @Test @Timeout(60)
    public void test_3_getOnAddressesReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/storefront/addresses?ids=156&ids=748")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/location/storefront/district/{id}
    */
    @Test @Timeout(60)
    public void test_4_getOnDistrictReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MDQ1ODAsImlhdCI6MTc3NDQwNDI4MCwianRpIjoiMTg3MDAxOGItMWY2Zi00NzgyLThhNWEtYzdiMmNjNTZhODUxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImE1MGU4Y2MxLTYzNGQtNDUxMC1hZWQ1LTFlYzhhYmY0NzRkYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.UAGhBstbYe74-e4RrbQ6CWoJne2xdORrIVy7b5_NsZ2hU4HJ1BEEc08QveNosmI6NB4DNgfnoFmKAmwC96mrRMkGFLOGTz0JA60LMI6r_Ge6TtaP9fXqpQ8aQY7GKeXkbpf0JcVT3DpSq3NS_Sik2nGY-B6rG3FNMft5joxH3IdCfp9zrmw7obXAS5zUlVXFOyIfFkZWZmJFDKceErNicybeCTGZSELkCNHd2MpyL-auiIPCOeNeZxQGgySJLWczoIC7JTdG_ue0hceDFVkX3q0e4v8TJ-1tTTviGFiAi44cB1rNbVCxdpLI987GgGDKTasU8a8NInbERjpYevwn5g") // Fixed Headers
                .get(baseUrlOfSut + "/location/storefront/district/769")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/location/storefront/state-or-provinces/{countryId}
    */
    @Test @Timeout(60)
    public void test_5_getOnState_or_provincReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MDQ1ODAsImlhdCI6MTc3NDQwNDI4MCwianRpIjoiMTg3MDAxOGItMWY2Zi00NzgyLThhNWEtYzdiMmNjNTZhODUxIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIwNWFhYzJiYS0xZjBlLTRkMzMtYTA0Ny1mZmI5YTNmMmE0ODEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImE1MGU4Y2MxLTYzNGQtNDUxMC1hZWQ1LTFlYzhhYmY0NzRkYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyIn0.UAGhBstbYe74-e4RrbQ6CWoJne2xdORrIVy7b5_NsZ2hU4HJ1BEEc08QveNosmI6NB4DNgfnoFmKAmwC96mrRMkGFLOGTz0JA60LMI6r_Ge6TtaP9fXqpQ8aQY7GKeXkbpf0JcVT3DpSq3NS_Sik2nGY-B6rG3FNMft5joxH3IdCfp9zrmw7obXAS5zUlVXFOyIfFkZWZmJFDKceErNicybeCTGZSELkCNHd2MpyL-auiIPCOeNeZxQGgySJLWczoIC7JTdG_ue0hceDFVkX3q0e4v8TJ-1tTTviGFiAi44cB1rNbVCxdpLI987GgGDKTasU8a8NInbERjpYevwn5g") // Fixed Headers
                .get(baseUrlOfSut + "/location/storefront/state-or-provinces/104")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/location/storefront/district/{id}
    */
    @Test @Timeout(60)
    public void test_6_getOnDistrictReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/storefront/district/8380037769429993221")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/location/storefront/state-or-provinces/{countryId}
    */
    @Test @Timeout(60)
    public void test_7_getOnState_or_provincReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/location/storefront/state-or-provinces/697")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }


}
