/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-24T22:31:35.966703052Z[GMT]
 * <br>
*  The generated test suite contains 12 tests
 * <br>
*  Covered targets: 100
 * <br>
*  Used time: 0h 1m 45s
 * <br>
*  Needed budget for current results: 85%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_rating_admin_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/rating/backoffice/ratings
    */
    @Test @Timeout(60)
    public void test_0_getOnRatingsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE2ODgsImlhdCI6MTc3NDM5MTM4OCwianRpIjoiZmIyNTA2OTYtZDYzZi00NzM4LTg3YmItNGUyZGQ5NWQ5ZTRlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiY2EzMjQzLTMzNjMtNGYyMy1hZGQzLWJiOWNjMzY0MjhhYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XuVJOg2OJ16HlEZeqcxGgSBtB9Bxcv7jNqTs9zch1ZHqDUZG4-VqcfAQO0eDiIwSZhCGHo9B07accCnuGS1z9jWpbokY-A5xCTS1aQogrhri1uqpF8-aw_SlxNM79z8U7YnHesqqbchQOTog-zDAtyonzg-2L5etQRPNtxjdBkc4TAug4ZmYly-fxfJUYfVLau8j4an7ssnKyQ41ei4CoVAxD93Qrgkc6PNS7v97ZMa-BwPtLUPj9TdKj-NoHvrsXwbfGie48EfDmUoCZU6DWsU5xtGRp0E_cmkgOOx9W4o34JwXy4ouihJt7R-e7pHEJyF8zZfdO_ny8ELV3jNftg") // Fixed Headers
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "message=Mitcx5PFm&" + 
                    "createdFrom=1918-06-17T17%3A10%3A12Z&" + 
                    "createdTo=1918-12-24T01%3A39%3A15%2B01%3A59")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/backoffice/ratings
    */
    @Test @Timeout(60)
    public void test_1_getOnRatingsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE2ODgsImlhdCI6MTc3NDM5MTM4OCwianRpIjoiZmIyNTA2OTYtZDYzZi00NzM4LTg3YmItNGUyZGQ5NWQ5ZTRlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiY2EzMjQzLTMzNjMtNGYyMy1hZGQzLWJiOWNjMzY0MjhhYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XuVJOg2OJ16HlEZeqcxGgSBtB9Bxcv7jNqTs9zch1ZHqDUZG4-VqcfAQO0eDiIwSZhCGHo9B07accCnuGS1z9jWpbokY-A5xCTS1aQogrhri1uqpF8-aw_SlxNM79z8U7YnHesqqbchQOTog-zDAtyonzg-2L5etQRPNtxjdBkc4TAug4ZmYly-fxfJUYfVLau8j4an7ssnKyQ41ei4CoVAxD93Qrgkc6PNS7v97ZMa-BwPtLUPj9TdKj-NoHvrsXwbfGie48EfDmUoCZU6DWsU5xtGRp0E_cmkgOOx9W4o34JwXy4ouihJt7R-e7pHEJyF8zZfdO_ny8ELV3jNftg") // Fixed Headers
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "message=2bLUg1lpF61&" + 
                    "createdTo=1975-06-21T02%3A24%3A55.471-04%3A52")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/backoffice/ratings
    */
    @Test @Timeout(60)
    public void test_2_getOnRatingsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE2ODgsImlhdCI6MTc3NDM5MTM4OCwianRpIjoiZmIyNTA2OTYtZDYzZi00NzM4LTg3YmItNGUyZGQ5NWQ5ZTRlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiY2EzMjQzLTMzNjMtNGYyMy1hZGQzLWJiOWNjMzY0MjhhYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XuVJOg2OJ16HlEZeqcxGgSBtB9Bxcv7jNqTs9zch1ZHqDUZG4-VqcfAQO0eDiIwSZhCGHo9B07accCnuGS1z9jWpbokY-A5xCTS1aQogrhri1uqpF8-aw_SlxNM79z8U7YnHesqqbchQOTog-zDAtyonzg-2L5etQRPNtxjdBkc4TAug4ZmYly-fxfJUYfVLau8j4an7ssnKyQ41ei4CoVAxD93Qrgkc6PNS7v97ZMa-BwPtLUPj9TdKj-NoHvrsXwbfGie48EfDmUoCZU6DWsU5xtGRp0E_cmkgOOx9W4o34JwXy4ouihJt7R-e7pHEJyF8zZfdO_ny8ELV3jNftg") // Fixed Headers
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "createdFrom=2064-10-11T02%3A46%3A55Z&" + 
                    "pageSize=652")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/backoffice/ratings
    */
    @Test @Timeout(60)
    public void test_3_getOnRatingsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE2ODgsImlhdCI6MTc3NDM5MTM4OCwianRpIjoiZmIyNTA2OTYtZDYzZi00NzM4LTg3YmItNGUyZGQ5NWQ5ZTRlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiY2EzMjQzLTMzNjMtNGYyMy1hZGQzLWJiOWNjMzY0MjhhYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XuVJOg2OJ16HlEZeqcxGgSBtB9Bxcv7jNqTs9zch1ZHqDUZG4-VqcfAQO0eDiIwSZhCGHo9B07accCnuGS1z9jWpbokY-A5xCTS1aQogrhri1uqpF8-aw_SlxNM79z8U7YnHesqqbchQOTog-zDAtyonzg-2L5etQRPNtxjdBkc4TAug4ZmYly-fxfJUYfVLau8j4an7ssnKyQ41ei4CoVAxD93Qrgkc6PNS7v97ZMa-BwPtLUPj9TdKj-NoHvrsXwbfGie48EfDmUoCZU6DWsU5xtGRp0E_cmkgOOx9W4o34JwXy4ouihJt7R-e7pHEJyF8zZfdO_ny8ELV3jNftg") // Fixed Headers
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "productName=6sy6l5&" + 
                    "message=sXc8Qu06iYyZHc&" + 
                    "createdTo=2064-07-31T00%3A18%3A03.803Z")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/backoffice/ratings
    */
    @Test @Timeout(60)
    public void test_4_getOnBackofficeRatingsWithQueryParamsEmptyProductNameReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE2ODgsImlhdCI6MTc3NDM5MTM4OCwianRpIjoiZmIyNTA2OTYtZDYzZi00NzM4LTg3YmItNGUyZGQ5NWQ5ZTRlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiY2EzMjQzLTMzNjMtNGYyMy1hZGQzLWJiOWNjMzY0MjhhYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XuVJOg2OJ16HlEZeqcxGgSBtB9Bxcv7jNqTs9zch1ZHqDUZG4-VqcfAQO0eDiIwSZhCGHo9B07accCnuGS1z9jWpbokY-A5xCTS1aQogrhri1uqpF8-aw_SlxNM79z8U7YnHesqqbchQOTog-zDAtyonzg-2L5etQRPNtxjdBkc4TAug4ZmYly-fxfJUYfVLau8j4an7ssnKyQ41ei4CoVAxD93Qrgkc6PNS7v97ZMa-BwPtLUPj9TdKj-NoHvrsXwbfGie48EfDmUoCZU6DWsU5xtGRp0E_cmkgOOx9W4o34JwXy4ouihJt7R-e7pHEJyF8zZfdO_ny8ELV3jNftg") // Fixed Headers
                .get(baseUrlOfSut + "/rating/backoffice/ratings?" + 
                    "productName=&" + 
                    "customerName=h7PGXyGL")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/backoffice/ratings/latest/{count}
    */
    @Test @Timeout(60)
    public void test_5_getOnLatestReturnsEmptyList() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE2ODgsImlhdCI6MTc3NDM5MTM4OCwianRpIjoiZmIyNTA2OTYtZDYzZi00NzM4LTg3YmItNGUyZGQ5NWQ5ZTRlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiY2EzMjQzLTMzNjMtNGYyMy1hZGQzLWJiOWNjMzY0MjhhYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XuVJOg2OJ16HlEZeqcxGgSBtB9Bxcv7jNqTs9zch1ZHqDUZG4-VqcfAQO0eDiIwSZhCGHo9B07accCnuGS1z9jWpbokY-A5xCTS1aQogrhri1uqpF8-aw_SlxNM79z8U7YnHesqqbchQOTog-zDAtyonzg-2L5etQRPNtxjdBkc4TAug4ZmYly-fxfJUYfVLau8j4an7ssnKyQ41ei4CoVAxD93Qrgkc6PNS7v97ZMa-BwPtLUPj9TdKj-NoHvrsXwbfGie48EfDmUoCZU6DWsU5xtGRp0E_cmkgOOx9W4o34JwXy4ouihJt7R-e7pHEJyF8zZfdO_ny8ELV3jNftg") // Fixed Headers
                .get(baseUrlOfSut + "/rating/backoffice/ratings/latest/279")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_6_getOnProductReturnsObject() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/-1584029990?" + 
                    "pageNo=149&" + 
                    "pageSize=511")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_7_getOnProductReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE2ODgsImlhdCI6MTc3NDM5MTM4OCwianRpIjoiZmIyNTA2OTYtZDYzZi00NzM4LTg3YmItNGUyZGQ5NWQ5ZTRlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiY2EzMjQzLTMzNjMtNGYyMy1hZGQzLWJiOWNjMzY0MjhhYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XuVJOg2OJ16HlEZeqcxGgSBtB9Bxcv7jNqTs9zch1ZHqDUZG4-VqcfAQO0eDiIwSZhCGHo9B07accCnuGS1z9jWpbokY-A5xCTS1aQogrhri1uqpF8-aw_SlxNM79z8U7YnHesqqbchQOTog-zDAtyonzg-2L5etQRPNtxjdBkc4TAug4ZmYly-fxfJUYfVLau8j4an7ssnKyQ41ei4CoVAxD93Qrgkc6PNS7v97ZMa-BwPtLUPj9TdKj-NoHvrsXwbfGie48EfDmUoCZU6DWsU5xtGRp0E_cmkgOOx9W4o34JwXy4ouihJt7R-e7pHEJyF8zZfdO_ny8ELV3jNftg") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/755?pageSize=97")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_8_getOnProductReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE2ODgsImlhdCI6MTc3NDM5MTM4OCwianRpIjoiZmIyNTA2OTYtZDYzZi00NzM4LTg3YmItNGUyZGQ5NWQ5ZTRlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiY2EzMjQzLTMzNjMtNGYyMy1hZGQzLWJiOWNjMzY0MjhhYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XuVJOg2OJ16HlEZeqcxGgSBtB9Bxcv7jNqTs9zch1ZHqDUZG4-VqcfAQO0eDiIwSZhCGHo9B07accCnuGS1z9jWpbokY-A5xCTS1aQogrhri1uqpF8-aw_SlxNM79z8U7YnHesqqbchQOTog-zDAtyonzg-2L5etQRPNtxjdBkc4TAug4ZmYly-fxfJUYfVLau8j4an7ssnKyQ41ei4CoVAxD93Qrgkc6PNS7v97ZMa-BwPtLUPj9TdKj-NoHvrsXwbfGie48EfDmUoCZU6DWsU5xtGRp0E_cmkgOOx9W4o34JwXy4ouihJt7R-e7pHEJyF8zZfdO_ny8ELV3jNftg") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/681?" + 
                    "pageNo=185&" + 
                    "pageSize=850")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/products/{productId}
    */
    @Test @Timeout(60)
    public void test_9_getOnProductReturnsObject() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE2ODgsImlhdCI6MTc3NDM5MTM4OCwianRpIjoiZmIyNTA2OTYtZDYzZi00NzM4LTg3YmItNGUyZGQ5NWQ5ZTRlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiY2EzMjQzLTMzNjMtNGYyMy1hZGQzLWJiOWNjMzY0MjhhYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XuVJOg2OJ16HlEZeqcxGgSBtB9Bxcv7jNqTs9zch1ZHqDUZG4-VqcfAQO0eDiIwSZhCGHo9B07accCnuGS1z9jWpbokY-A5xCTS1aQogrhri1uqpF8-aw_SlxNM79z8U7YnHesqqbchQOTog-zDAtyonzg-2L5etQRPNtxjdBkc4TAug4ZmYly-fxfJUYfVLau8j4an7ssnKyQ41ei4CoVAxD93Qrgkc6PNS7v97ZMa-BwPtLUPj9TdKj-NoHvrsXwbfGie48EfDmUoCZU6DWsU5xtGRp0E_cmkgOOx9W4o34JwXy4ouihJt7R-e7pHEJyF8zZfdO_ny8ELV3jNftg") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/products/943?pageNo=856")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'ratingList'.size()", equalTo(0))
                .body("'totalElements'", numberMatches(0))
                .body("'totalPages'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/product/{productId}/average-star
    */
    @Test @Timeout(60)
    public void test_10_getOnAverage_starReturnsContent() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQzOTE2ODgsImlhdCI6MTc3NDM5MTM4OCwianRpIjoiZmIyNTA2OTYtZDYzZi00NzM4LTg3YmItNGUyZGQ5NWQ5ZTRlIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiI2YTRjY2Y1OC0xNGE3LTRjNjgtOGYzNS05MTA3Zjk4NzU1YjIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6ImJiY2EzMjQzLTMzNjMtNGYyMy1hZGQzLWJiOWNjMzY0MjhhYiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXlhcyIsIm9mZmxpbmVfYWNjZXNzIiwiQ1VTVE9NRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkFETUlOIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJKb2huIERvZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIn0.XuVJOg2OJ16HlEZeqcxGgSBtB9Bxcv7jNqTs9zch1ZHqDUZG4-VqcfAQO0eDiIwSZhCGHo9B07accCnuGS1z9jWpbokY-A5xCTS1aQogrhri1uqpF8-aw_SlxNM79z8U7YnHesqqbchQOTog-zDAtyonzg-2L5etQRPNtxjdBkc4TAug4ZmYly-fxfJUYfVLau8j4an7ssnKyQ41ei4CoVAxD93Qrgkc6PNS7v97ZMa-BwPtLUPj9TdKj-NoHvrsXwbfGie48EfDmUoCZU6DWsU5xtGRp0E_cmkgOOx9W4o34JwXy4ouihJt7R-e7pHEJyF8zZfdO_ny8ELV3jNftg") // Fixed Headers
                .get(baseUrlOfSut + "/rating/storefront/ratings/product/699/average-star")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body(containsString("0.0"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/rating/storefront/ratings/product/{productId}/average-star
    */
    @Test @Timeout(60)
    public void test_11_getOnAverage_starReturnsContent() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/rating/storefront/ratings/product/359/average-star")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body(containsString("0.0"));
    }


}
