/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T04:50:52.999348807Z[GMT]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 10
 * <br>
*  Used time: 0h 1m 15s
 * <br>
*  Needed budget for current results: 54%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_cart_admin_only_successes {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) GET:/cart/storefront/cart/items
    */
    @Test @Timeout(60)
    public void test_0_getOnItemsReturns1Element() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ0NzUsImlhdCI6MTc3NDQxNDE3NSwianRpIjoiMTY1OWQyYjEtZGRhOC00NTc4LTk2YWItMmM0NmEzY2IzOTVhIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjRiNDU4OWY4LWM3YzAtNGEzNS05YzEzLTY0YmMzMGM5OWQ0OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CNs_eQU032j732Iit80OK6FSRiS-J3dq8ZkHQEI_NX_3eGM23OTkC-HesLfRXxzz0vnfTPJpU-KZ8OHgAvRPMHvXanWsOLnVrjx_4KhujV0og7P1_Avh1qtWjKJrB7A5oxdnoXybb0B1vITTMPQzHMU7Tc-Z1ZZ0NxaQJAczRxaV_djUh07CLygV2N3ZDHJEkxZU-8TXiuvzU4Xaz61OE_-dT2dUCFCWh95YiEIIUL51h_G8vln53UCVMTUInTjpTEyBunTVYo6FSCgKlHVzEjNvpIGNvO1qwD0_rm_JDahZ1u7psuUN_g1EilKYNNCWUEqIIeGSd3yrikiBE2ROLg") // Fixed Headers
                .get(baseUrlOfSut + "/cart/storefront/cart/items")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(1))
                .body("[0].'customerId'", containsString("3f0f3046-410c-4d5e-9361-7e613b244378"))
                .body("[0].'productId'", numberMatches(13))
                .body("[0].'quantity'", numberMatches(2586));
    }
    
    
    /**
    * Calls:
    * (200) POST:/cart/storefront/cart/items/remove
    */
    @Test @Timeout(60)
    public void test_1_postOnRemoveReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQ0NzUsImlhdCI6MTc3NDQxNDE3NSwianRpIjoiMTY1OWQyYjEtZGRhOC00NTc4LTk2YWItMmM0NmEzY2IzOTVhIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjRiNDU4OWY4LWM3YzAtNGEzNS05YzEzLTY0YmMzMGM5OWQ0OSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.CNs_eQU032j732Iit80OK6FSRiS-J3dq8ZkHQEI_NX_3eGM23OTkC-HesLfRXxzz0vnfTPJpU-KZ8OHgAvRPMHvXanWsOLnVrjx_4KhujV0og7P1_Avh1qtWjKJrB7A5oxdnoXybb0B1vITTMPQzHMU7Tc-Z1ZZ0NxaQJAczRxaV_djUh07CLygV2N3ZDHJEkxZU-8TXiuvzU4Xaz61OE_-dT2dUCFCWh95YiEIIUL51h_G8vln53UCVMTUInTjpTEyBunTVYo6FSCgKlHVzEjNvpIGNvO1qwD0_rm_JDahZ1u7psuUN_g1EilKYNNCWUEqIIeGSd3yrikiBE2ROLg") // Fixed Headers
                .contentType("application/json")
                .body(" [ { " + 
                    " \"productId\" : 691, " + 
                    " \"quantity\" : 2147482705 " + 
                    " }, { " + 
                    " \"productId\" : 790, " + 
                    " \"quantity\" : 249 " + 
                    " } ] ")
                .post(baseUrlOfSut + "/cart/storefront/cart/items/remove")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }


}
