backend:
  replicaCount: 1
  image:
    repository: danzgne/yas-media
    tag: main

  nameOverride: media
  fullnameOverride: media
  databaseName: media
  ingress:
    enabled: false
  extraVolumes:
    - name: media-application
      configMap:
        name: media-application-configmap
  extraVolumeMounts:
    - name: media-application
      mountPath: /opt/yas/media
  extraApplicationConfigPaths:
    - /opt/yas/media/media-application.yaml

