backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-media
    tag: latest

  nameOverride: media
  fullnameOverride: media
  databaseName: media
  ingress:
    enabled: false
  extraVolumes:
    - name: media-application
      configMap:
        name: media-application-configmap
    - name: media-storage
      hostPath:
        path: /mnt/f/Devops/yas/sampledata/images
        type: Directory
  extraVolumeMounts:
    - name: media-application
      mountPath: /opt/yas/media
    - name: media-storage
      mountPath: /images
  extraApplicationConfigPaths:
    - /opt/yas/media/media-application.yaml

