backend:
  replicaCount: 1
  image:
    repository: danzgne/yas-cart
    tag: main

  nameOverride: cart
  fullnameOverride: cart
  databaseName: cart
  ingress:
    enabled: false
  extraVolumes:
    - name: cart-application-config
      configMap:
        name: cart-application-configmap
  extraVolumeMounts:
    - name: cart-application-config
      mountPath: /opt/yas/cart
  extraApplicationConfigPaths:
    - /opt/yas/cart/cart-application.yaml
