apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 9.2.3
  auth:
    fileRealm:
      - secretName: user-credentials-secret
  nodeSets:
    - name: node
      count: {{ .Values.elasticsearch.replicas }}
      config:
        node.store.allow_mmap: false
        xpack.security.http.ssl.enabled: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: do-block-storage
      podTemplate:
        spec:
          tolerations:
            - key: "node.kubernetes.io/memory-pressure"
              operator: "Exists"
              effect: "NoSchedule"
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms512m -Xmx512m"
              resources:
                requests:
                  memory: 1Gi
                  cpu: 20m
                limits:
                  memory: 1Gi
                  cpu: 1
