apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 7.17.10
  auth:
    fileRealm:
      - secretName: user-credentials-secret
  nodeSets:
    - name: node
      count: {{ .Values.elasticsearch.replicas }}
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          initContainers:
            - name: wait-for-dns
              image: busybox:1.36
              command: ['sh', '-c', 'until nslookup kubernetes.default.svc.cluster.local; do echo waiting for dns; sleep 2; done;']
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 1Gi
                  cpu: 250m
                limits:
                  memory: 1Gi
                  cpu: 1000m
