/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T04:49:35.014239254Z[GMT]
 * <br>
*  The generated test suite contains 25 tests
 * <br>
*  Covered targets: 95
 * <br>
*  Used time: 0h 1m 43s
 * <br>
*  Needed budget for current results: 64%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_customer_admin_only_faults {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (500) GET:/customer/storefront/user-address
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_getOnUser_addressShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/user-address'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .get(baseUrlOfSut + "/customer/storefront/user-address")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("500 INTERNAL_SERVER_ERROR"))
                .body("'title'", containsString("Internal Server Error"))
                .body("'detail'", containsString("CircuitBreaker 'restCircuitBreaker' is OPEN and does not permit further calls"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (500) POST:/customer/storefront/user-address
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_postOnUser_addressShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/storefront/user-address'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"contactName\" : \"pQthc\", " + 
                    " \"zipCode\" : \"VICEIS\", " + 
                    " \"stateOrProvinceId\" : 507 " + 
                    " } ")
                .post(baseUrlOfSut + "/customer/storefront/user-address")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("500 INTERNAL_SERVER_ERROR"))
                .body("'title'", containsString("Internal Server Error"))
                .body("'detail'", containsString("CircuitBreaker 'restCircuitBreaker' is OPEN and does not permit further calls"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/customer/backoffice/customers
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_2_getOnCustomersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 200 not defined for path '/backoffice/customers'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .get(baseUrlOfSut + "/customer/backoffice/customers?pageNo=501")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'totalUser'", numberMatches(0))
                .body("'customers'.size()", equalTo(0))
                .body("'totalPage'", numberMatches(0));
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/backoffice/customers
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_getOnCustomersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/customers'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/backoffice/customers?pageNo=59")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/customer/storefront/user-address
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_4_getOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/storefront/user-address")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("403 FORBIDDEN"))
                .body("'title'", containsString("Forbidden"))
                .body("'detail'", containsString("ACTION FAILED, PLEASE LOGIN"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (403) POST:/customer/backoffice/customers
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_5_postOnCustomersReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"username\" : \"qZHoj7q1FfGSMtiM\", " + 
                    " \"email\" : \"ceg_Zb06M\", " + 
                    " \"firstName\" : \"h\", " + 
                    " \"lastName\" : \"rX4Gg4Ayg\", " + 
                    " \"password\" : \"Z9qR7kOHIuycPtQ\", " + 
                    " \"role\" : \"Y8ImprZkm86xZ\" " + 
                    " } ")
                .post(baseUrlOfSut + "/customer/backoffice/customers")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/backoffice/customers"));
    }
    
    
    /**
    * Calls:
    * (403) POST:/customer/storefront/user-address
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_6_postOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"addressLine1\" : \"u5WR1O\", " + 
                    " \"city\" : \"zsSFK\", " + 
                    " \"countryId\" : 541 " + 
                    " } ")
                .post(baseUrlOfSut + "/customer/storefront/user-address")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/user-address"));
    }
    
    
    /**
    * Calls:
    * (200) PUT:/customer/storefront/user-address/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_7_putOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing PUT on path '/storefront/user-address/{id}' defines a response schema but no response body found.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .put(baseUrlOfSut + "/customer/storefront/user-address/390")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
        
        // Cleanup actions
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .delete(baseUrlOfSut + "/customer/storefront/user-address/390")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("User address not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/backoffice/customers/{email}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_8_getOnCustomReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/customers/{email}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/backoffice/customers/yeIVM2wk7X8")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/storefront/customer/profile
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_9_getOnProfileReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/storefront/customer/profile'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/storefront/customer/profile")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/customer/storefront/customer/profile
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_10_getOnProfileReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.missing GET on path '/storefront/customer/profile' defines a response schema but no response body found.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .get(baseUrlOfSut + "/customer/storefront/customer/profile")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) GET:/customer/storefront/user-address/default-address
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_11_getOnDefault_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address/default-address'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/storefront/user-address/default-address")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("403 FORBIDDEN"))
                .body("'title'", containsString("Forbidden"))
                .body("'detail'", containsString("ACTION FAILED, PLEASE LOGIN"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * 1 - (403) GET:/customer/storefront/user-address/default-address
    * 2 - (404) GET:/customer/storefront/user-address/default-address
    * Found 3 potential faults. Type-codes: 101, 204
    */
    @Test @Timeout(60)
    public void test_12_getOnDefault_addressShowsFaults_101_204() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address/default-address'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/storefront/user-address/default-address")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("403 FORBIDDEN"))
                .body("'title'", containsString("Forbidden"))
                .body("'detail'", containsString("ACTION FAILED, PLEASE LOGIN"))
                .body("'fieldErrors'", nullValue());
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/storefront/user-address/default-address'.
        // Fault204. Leakage Information Existence of Protected Resource.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .get(baseUrlOfSut + "/customer/storefront/user-address/default-address")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("User address not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (403) POST:/customer/storefront/customer/guest-user
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_13_postOnGuest_userReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/customer/guest-user'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .post(baseUrlOfSut + "/customer/storefront/customer/guest-user")
                .then()
                .statusCode(403)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) POST:/customer/storefront/customer/guest-user
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_14_postOnGuest_userReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/customer/guest-user'.
        given().accept("*/*")
                .post(baseUrlOfSut + "/customer/storefront/customer/guest-user")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/customer/guest-user"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/customer/storefront/user-address/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_15_putOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address/{id}'.
        given().accept("*/*")
                .put(baseUrlOfSut + "/customer/storefront/user-address/1653988727640071926")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/user-address/1653988727640071926"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/customer/storefront/user-address/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_16_deleteOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/storefront/user-address/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/customer/storefront/user-address/915")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/storefront/user-address/915"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/customer/storefront/user-address/default-address
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_17_getOnDefault_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/storefront/user-address/default-address'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .get(baseUrlOfSut + "/customer/storefront/user-address/default-address")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("User address not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) DELETE:/customer/storefront/user-address/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_18_deleteOnUser_addressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/storefront/user-address/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .delete(baseUrlOfSut + "/customer/storefront/user-address/272")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("404 NOT_FOUND"))
                .body("'title'", containsString("Not Found"))
                .body("'detail'", containsString("User address not found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (500) GET:/customer/backoffice/customers/profile/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_19_getOnProfilShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .get(baseUrlOfSut + "/customer/backoffice/customers/profile/TE")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("500 INTERNAL_SERVER_ERROR"))
                .body("'title'", containsString("Internal Server Error"))
                .body("'detail'", containsString("HTTP 404 Not Found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (500) PUT:/customer/backoffice/customers/profile/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_20_putOnProfilShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"firstName\" : \"wnNeICadc\" " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/backoffice/customers/profile/WqWO7OuYIo_i")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("500 INTERNAL_SERVER_ERROR"))
                .body("'title'", containsString("Internal Server Error"))
                .body("'detail'", containsString("HTTP 404 Not Found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (500) DELETE:/customer/backoffice/customers/profile/{id}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_21_deleteOnProfilShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500.
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .delete(baseUrlOfSut + "/customer/backoffice/customers/profile/LHk8NQcoVGtNhX")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("500 INTERNAL_SERVER_ERROR"))
                .body("'title'", containsString("Internal Server Error"))
                .body("'detail'", containsString("HTTP 404 Not Found"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (401) GET:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_22_getOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/customer/backoffice/customers/profile/s75itoUV")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (403) PUT:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_23_putOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"email\" : \"I0R3\" " + 
                    " } ")
                .put(baseUrlOfSut + "/customer/backoffice/customers/profile/bO9f")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/backoffice/customers/profile/bO9f"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/customer/backoffice/customers/profile/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_24_deleteOnProfilReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 403 not defined for path '/backoffice/customers/profile/{id}'.
        given().accept("*/*")
                .delete(baseUrlOfSut + "/customer/backoffice/customers/profile/yublFL86XO")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(403))
                .body("'error'", containsString("Forbidden"))
                .body("'path'", containsString("/customer/backoffice/customers/profile/yublFL86XO"));
    }


}
