/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-25T04:49:35.030651192Z[GMT]
 * <br>
*  The generated test suite contains 3 tests
 * <br>
*  Covered targets: 7
 * <br>
*  Used time: 0h 1m 43s
 * <br>
*  Needed budget for current results: 64%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_customer_admin_only_others {

    
    private static String baseUrlOfSut = "http://api.yas.local";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (400) POST:/customer/backoffice/customers
    */
    @Test @Timeout(60)
    public void test_0_postOnCustomersReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"username\" : \"jLkr\", " + 
                    " \"email\" : \"cJrxZfYg\", " + 
                    " \"firstName\" : \"chebVpj6Kk46F96q\", " + 
                    " \"lastName\" : \"rPcdlgCM\", " + 
                    " \"password\" : \"xKDpui56uc\", " + 
                    " \"role\" : \"VmzeqGg7GSfJq7k\" " + 
                    " } ")
                .post(baseUrlOfSut + "/customer/backoffice/customers")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Request information is not valid"))
                .body("'fieldErrors'.size()", equalTo(1))
                .body("'fieldErrors'", hasItems("email must be a well-formed email address"));
    }
    
    
    /**
    * Calls:
    * (400) GET:/customer/backoffice/customers/{email}
    */
    @Test @Timeout(60)
    public void test_1_getOnCustomReturns400() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBQ2xObzBsSkd1cTBOckJFem02NjctOWRqejZ1NnZrek9KRnZvTzdjZmJRIn0.eyJleHAiOjE3NzQ0MTQzNjksImlhdCI6MTc3NDQxNDA2OSwianRpIjoiNWU3ZWI5MTAtMjE1Mi00NjUxLThhNjktZjA1Y2Y3YWIxMTEwIiwiaXNzIjoiaHR0cDovL2lkZW50aXR5L3JlYWxtcy9ZYXMiLCJzdWIiOiIzZjBmMzA0Ni00MTBjLTRkNWUtOTM2MS03ZTYxM2IyNDQzNzgiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJiYWNrb2ZmaWNlLWJmZiIsInNpZCI6IjBmNGNiNTZlLWEzMDgtNGZhYy05NzM2LWE0YzJlZTg1YTUzNiIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJBRE1JTiJdfSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbl9vbmx5In0.JReMkKECe7w8qIduJpx4GS67xplG2snUk72VZXU8FO21hL5vVfqFicEsjQfUbcwynUDVfWyMZCyJsQRHRDYdxjiCm39mm0IZl6pzNtR3HJVe9RfVcFsv95i6chdAaeSDue9wpt6V0kYdiTTuFaR3PBDOQIM6jRvj1r1yJxapMEFLROxMdvKLq_eiQfngZdakMh6ItxC38Yyvxe_7-sm0GmFwJefecwTUCO6di2LhS5M0nI9vCdkBOBpYUNfEceAmwd2nThnpD0T3U6_YiSr_XFntSIN4xb15hx0HJ9Wwsu1OYSD2XsW5h4WkiZNhiEd-sZPoePJYIYe--IhN2VxYSg") // Fixed Headers
                .get(baseUrlOfSut + "/customer/backoffice/customers/_EC60e2Mobkpamdh")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'statusCode'", containsString("400 BAD_REQUEST"))
                .body("'title'", containsString("Bad Request"))
                .body("'detail'", containsString("Wrong email format for _EC60e2Mobkpamdh"))
                .body("'fieldErrors'", nullValue());
    }
    
    
    /**
    * Calls:
    * (404) GET:/:-1/customer/v3/api-docs
    */
    @Test @Timeout(60)
    public void test_2_getOnApi_docsReturns404() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/:-1/customer/v3/api-docs")
                .then()
                .statusCode(404);
    }


}
