name: backoffice service ci

on:
    push:
        branches: ["main"]
        paths:
            - "backoffice/**"
            - ".github/workflows/actions/action.yaml"
            - ".github/workflows/backoffice-ci.yaml"
    pull_request:
        branches: ["main"]
        paths:
            - "backoffice/**"
            - ".github/workflows/actions/action.yaml"
            - ".github/workflows/backoffice-ci.yaml"
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm ci
              working-directory: backoffice
            - run: npm run build
              working-directory: backoffice
            - run: npm run lint
              working-directory: backoffice
            - run: npx prettier --check .
              working-directory: backoffice
            - run: npm audit --omit=dev
              continue-on-error: true
              working-directory: backoffice
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              with:
                  projectBaseDir: backoffice
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: Snyk test
              uses: snyk/actions/node@master
              continue-on-error: true # To make sure that SARIF upload gets called
              with:
                  args: --file=backoffice/package.json --sarif-file-output=snyk.sarif --severity-threshold=high
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            - name: Upload Snyk test result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: snyk.sarif

            - name: Log in to the Container registry
              if: ${{ github.ref == 'refs/heads/main' }}
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push Docker images
              if: ${{ github.ref == 'refs/heads/main' }}
              uses: docker/build-push-action@v6
              with:
                  push: true
                  context: ./backoffice
                  tags: ghcr.io/powerstomp/yas-backoffice:latest
