name: cart service ci

on:
  push:
    paths:
      - "cart/**"
  pull_request:
    paths:
      - "cart/**"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/java-service-ci-reusable.yml
    with:
      service: cart
      service_label: Cart
    secrets: inherit
