name: customer service ci

on:
  push:
    branches: ["main"]
    paths:
      - "customer/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/customer-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: ["main"]
    paths:
      - "customer/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/customer-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks check
        run: |
          docker pull zricethezav/gitleaks:v8.18.4
          docker run --rm -v ${{ github.workspace }}:/work -w /work zricethezav/gitleaks:v8.18.4 detect --source="./customer" --config="/work/gitleaks.toml" --verbose --no-git

  build:
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Build
        run: mvn clean package -DskipTests -pl customer -am

  test:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pull-requests: write
      checks: write
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Tests
        run: mvn test -pl customer -am

      - name: Run Maven Checkstyle
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        run: mvn checkstyle:checkstyle -pl customer -am -Dcheckstyle.output.file=customer-checkstyle-result.xml

      - name: Upload Checkstyle Result
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: "**/customer-checkstyle-result.xml"

      - name: Test Results
        uses: dorny/test-reporter@v1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
        with:
          name: Customer-Service-Unit-Test-Results
          path: "customer/**/*-reports/TEST*.xml"
          reporter: java-junit

      - name: Analyze with sonar cloud
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn sonar:sonar
          -pl customer -am
          -Dsonar.projectKey=thanhdatttt_DevOps-Project
          -Dsonar.organization=thanhdatttt
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.coverage.jacoco.xmlReportPaths=${{github.workspace}}/customer/target/site/jacoco/jacoco.xml

      - name: Add coverage report to PR
        uses: madrapps/jacoco-report@v1.6.1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        with:
          paths: ${{github.workspace}}/customer/target/site/jacoco/jacoco.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
          title: "Customer Coverage Report"
          update-comment: true

  security:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk.sarif
