name: customer service ci

on:
  push:
    paths:
      - "customer/**"
  pull_request:
    paths:
      - "customer/**"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/java-service-ci-reusable.yml
    with:
      service: customer
      service_label: Customer
    secrets: inherit
