name: GitLeaks check
on:
    push:

    pull_request:
        branches: ["main"]
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
            - uses: gitleaks/gitleaks-action@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
