name: inventory service ci

on:
  push:
    branches: ["main"]
    paths:
      - "inventory/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/inventory-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: ["main"]
    paths:
      - "inventory/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/inventory-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Gitleaks Scan
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/workflows/actions

      - name: Snyk Open Source Scan
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --file=inventory/pom.xml
          
      # - name: Run Maven Build Command
      #   run: mvn clean install -pl inventory -am
      # - name: Run Maven Checkstyle
      #   if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
      #   run: mvn checkstyle:checkstyle -pl inventory -am -Dcheckstyle.output.file=inventory-checkstyle-result.xml
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install snyk -g # install snyk
      - run: snyk -v
      - name: Setup Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth "$SNYK_TOKEN"

      - name: install snyk-to-html
        run: |
          # Install the Snyk JSON to HTML Mapper using npm
          npm install snyk-to-html -g
          # Convert JSON output from `snyk test --json` into a static HTML
          snyk test --json | snyk-to-html -o result.html
          mkdir downloads
          cp -v /home/runner/work/java-goof/java-goof/*.html /home/runner/work/java-goof/java-goof/downloads

      # save the HTML in the artifact
      - name: Use the Upload Artifact GitHub Action
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: actions/upload-artifact@master
        with:
          name: results
          path: ${{github.workspace}}/reports
          

      - name: Analyze with sonar cloud
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f inventory
        
      - name: Add coverage report to PR
        uses: madrapps/jacoco-report@v1.6.1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        with:
          paths: ${{github.workspace}}/inventory/target/site/jacoco/jacoco.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 80
          min-coverage-changed-files: 60
          title: 'Inventory Coverage Report'
          update-comment: true
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./inventory
          push: true
          tags: ghcr.io/nashtech-garage/yas-inventory:latest
          
      
