name: inventory service ci

on:
  push:
    paths:
      - "inventory/**"
  pull_request:
    paths:
      - "inventory/**"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/java-service-ci-reusable.yml
    with:
      service: inventory
      service_label: Inventory
    secrets: inherit
