name: location service ci

on:
  push:
    paths:
      - "location/**"
      - "common-library/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/location-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  Build:
    outputs:
      image-tag: ${{ steps.meta.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions
      - name: Build
        run: mvn clean install -pl location -am -DskipTests
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/yas-location
          tags: |
            type=sha,format=short,prefix=
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./location
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  update-gitops:
    needs: Build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_gitops-deploy-dev.yaml
    with:
      service: location
      env: dev
      tag: ${{ needs.Build.outputs.image-tag }}
      values-key: backend
    secrets:
      gitops_pat: ${{ secrets.GITOPS_PAT }}
