name: Media Lab - Hello DevOps

on:
  push:
    branches:
      - '**' 
    paths:
      - 'media/**' 
      - '.github/workflows/media-lab.yaml'

jobs:
  Lab-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn về máy ảo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Bắt buộc phải có cái này để Gitleaks đọc lịch sử commit

      # Thêm ông bảo vệ Gitleaks vào đây!
      - name: Gitleaks Scan (Bắt lỗi ngay lập tức)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Chú ý: Tuyệt đối KHÔNG DÙNG continue-on-error: true ở đây

      - name: In lời chào
        run: |
          echo "Nếu dòng này được in ra, nghĩa là Gitleaks đã ngủ quên!"