name: media service ci

on:
  push:
    branches: ["**"]
    paths:
      - "media/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/media-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: ["**"]
    paths:
      - "media/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/media-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  Test:
    name: Test Phase
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - uses: ./.github/workflows/actions

      - name: Run Maven Test Command
        run: mvn clean test jacoco:report -pl media -am

      - name: Test Results
        uses: dorny/test-reporter@v1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
        with:
          name: Media-Service-Unit-Test-Results
          path: "media/**/*-reports/TEST*.xml"
          reporter: java-junit

      - name: Upload Test Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: media-coverage-report
          path: media/target/site/jacoco/

  Build:
    name: Build Phase
    runs-on: ubuntu-latest
    needs: Test
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/actions

      - name: Run Maven Build Command
        run: mvn clean install -DskipTests -pl common-library,media -am

      - name: Upload Checkstyle Result
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: "**/media-checkstyle-result.xml"

      - name: Analyze with sonar cloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -pl common-library,media -am \
            -Dsonar.projectKey=JuzHarii_yas \
            -Dsonar.organization=juzharii \
            -Dsonar.host.url=https://sonarcloud.io

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk Security Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --file=media/pom.xml --command=mvn

      - name: OWASP Dependency Check
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: dependency-check/Dependency-Check_Action@main

        with:
          project: "yas"
          path: "."
          format: "HTML"

      - name: Upload OWASP Dependency Check results
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: actions/upload-artifact@master
        with:
          name: OWASP Dependency Check Report
          path: ${{github.workspace}}/reports

      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./media
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yas-media:latest
