name: order service ci

on:
  push:
    paths:
      - "order/**"
  pull_request:
    paths:
      - "order/**"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/java-service-ci-reusable.yml
    with:
      service: order
      service_label: Order
    secrets: inherit
