name: payment-paypal CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'payment-paypal/**'
      # any pushes to any, matches anything within payment-paypal recursively
  pull_request:
    branches: ["main"]
    paths:
      - 'payment-paypal/**'
      # any pull requests to main, matches anything within payment-paypal recursively

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Debug Info
      run: |
        pwd
        ls -la
    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PA_TOKEN }}
        
    - name: Build and Test payment-paypal Service
      # -pl payment-paypal: Only build payment-paypal project
      # -am: Also make dependencies (build common-library if needed)
      run: mvn -B clean install -pl payment-paypal -am # switching to system maven
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: payment-paypal-test-results
        path: | 
          payment-paypal/target/*-reports/*.xml
          payment-paypal/target/site/jacoco/*

    - name: enforce minimum coverage and PR comment
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.2
      with:
        paths: |
          ${{ github.workspace }}/payment-paypal/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 70
        title: "payment-paypal coverage"
        fail_on_min_coverage: true

    - name: Cache OWASP NVD DB
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository/org/owasp/dependency-check-data
        key: owasp-nvd-${{ runner.os }}

    - name: Checkstyle
      run: mvn checkstyle:check -pl payment-paypal -am

    - name: OWASP Dependency Check
      run: mvn org.owasp:dependency-check-maven:check -pl payment-paypal -am

    - name: Upload OWASP Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: payment-paypal-owasp-report
        path: payment-paypal/target/dependency-check-report.html