name: promotion service ci

on:   
  push:
    branches: ["**"]
    paths:
      - "promotion/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/promotion-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: ["main"]
    paths:
      - "promotion/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/promotion-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Maven Test
        run: mvn -pl promotion -am verify
      - name: Install Dependencies
        run: mvn -pl promotion -am install -DskipTests
      - name: Test Results
        uses: dorny/test-reporter@v1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
        with:
          name: Promotion-Service-Unit-Test-Results
          path: "promotion/**/*-reports/TEST*.xml"
          reporter: java-junit
      - name: Add coverage report to PR
        uses: madrapps/jacoco-report@v1.6.1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        with:
          paths: ${{github.workspace}}/promotion/target/site/jacoco/jacoco.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 70
          min-coverage-changed-files: 60
          title: 'Promotion Coverage Report'
          update-comment: true
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: promotion-coverage-report
          path: ${{github.workspace}}/promotion/target/site/jacoco/
      - name: Gitleaks check (Service Level)
        run: |
          docker run --rm -v ${{ github.workspace }}:/work -w /work zricethezav/gitleaks:v8.18.4 detect --source="./promotion" --no-git --verbose

  build:
    runs-on: ubuntu-latest
    needs: test  
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Maven Build
        run: mvn -pl promotion -am -DskipTests install

      - name: Run Maven Checkstyle
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        run: mvn checkstyle:checkstyle -pl promotion -am -Dcheckstyle.output.file=promotion-checkstyle-result.xml
      - name: Upload Checkstyle Result
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/promotion-checkstyle-result.xml'
      - name: OWASP Dependency Check
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'yas'
          path: '.'
          format: 'HTML'
          args: >
            --disableCentral
            --failOnCVSS 11
      - name: Upload OWASP Dependency Check results
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: actions/upload-artifact@master
        with:
          name: OWASP Dependency Check Report
          path: ${{github.workspace}}/reports
      - name: Analyze with sonar cloud
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f promotion

      - name: Setup Snyk
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: snyk/actions/setup@master

      - name: Run Snyk Scan (Code Quality & Security)
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test ./promotion --severity-threshold=medium --sarif-file-output=snyk-results.sarif

      - name: Upload Snyk results
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && !cancelled() }}]
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-results.sarif
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./promotion
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yas-promotion:latest
