name: rating service ci

on:
  push:
    paths:
      - "rating/**"
  pull_request:
    paths:
      - "rating/**"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/java-service-ci-reusable.yml
    with:
      service: rating
      service_label: Rating
    secrets: inherit
