name: search service ci

on:
  push:
    paths:
      - "search/**"
  pull_request:
    paths:
      - "search/**"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/java-service-ci-reusable.yml
    with:
      service: search
      service_label: Search
    secrets: inherit
