name: storefront-bff service ci

on:
  push:
    branches: ["**"]
    paths:
      - "storefront-bff/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/storefront-bff-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: ["main"]
    paths:
      - "storefront-bff/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/storefront-bff-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Maven Test
        run: mvn -pl storefront-bff -am verify  # Chạy test và sinh JaCoCo report
      - name: Install Dependencies  # Thêm step này để install JARs cho job build
        run: mvn -pl storefront-bff -am install -DskipTests
      - name: Test Results
        uses: dorny/test-reporter@v1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
        with:
          name: Storefront-Bff-Service-Unit-Test-Results
          path: "storefront-bff/**/*-reports/TEST*.xml"
          reporter: java-junit
      - name: Add coverage report to PR
        uses: madrapps/jacoco-report@v1.6.1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        with:
          paths: ${{github.workspace}}/storefront-bff/target/site/jacoco/jacoco.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 70  # Gate coverage > 70%
          min-coverage-changed-files: 60
          title: 'Storefront-Bff Coverage Report'
          update-comment: true
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: storefront-bff-coverage-report
          path: ${{github.workspace}}/storefront-bff/target/site/jacoco/
      - name: Gitleaks check (Service Level)
        run: |
          docker run --rm -v ${{ github.workspace }}:/work -w /work zricethezav/gitleaks:v8.18.4 detect --source="./storefront-bff" --no-git --verbose

  build:
    runs-on: ubuntu-latest
    needs: test  
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Maven Build
        run: mvn -pl storefront-bff -am -DskipTests install
        # build without running test again

      - name: Run Maven Checkstyle
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        run: mvn checkstyle:checkstyle -pl storefront-bff -am -Dcheckstyle.output.file=storefront-bff-checkstyle-result.xml
      - name: Upload Checkstyle Result
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/storefront-bff-checkstyle-result.xml'
      - name: OWASP Dependency Check
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'yas'
          path: '.'
          format: 'HTML'
          # Thêm dòng args dưới đây để tắt Central Analyzer
          args: >
            --disableCentral
            --failOnCVSS 11 # Đặt ngưỡng CVSS > 10 để không fail build nhưng vẫn sinh report
      - name: Upload OWASP Dependency Check results
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: actions/upload-artifact@master
        with:
          name: OWASP Dependency Check Report
          path: ${{github.workspace}}/reports
      - name: Analyze with sonar cloud
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f storefront-bff

      - name: Setup Snyk
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: snyk/actions/setup@master

      - name: Run Snyk Scan (Code Quality & Security)
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        continue-on-error: true # Thêm dòng này để nếu snyk thấy lỗi vẫn chạy tiếp step upload
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test ./storefront-bff --severity-threshold=medium --sarif-file-output=snyk-results.sarif

      - name: Upload Snyk results
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && !cancelled() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-results.sarif
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./storefront-bff
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yas-storefront-bff:latest  # Chỉnh namespace cho repo fork