name: tax service ci

on:
    push:
        branches: ["main"]
        paths:
            - "tax/**"
            - ".github/workflows/actions/action.yaml"
            - ".github/workflows/tax-ci.yaml"
            - "pom.xml"
    pull_request:
        branches: ["main"]
        paths:
            - "tax/**"
            - ".github/workflows/actions/action.yaml"
            - ".github/workflows/tax-ci.yaml"
            - "pom.xml"
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
            - uses: ./.github/workflows/actions
            - name: Run Maven Build Command
              run: mvn clean install -pl tax -am
            - name: Run Maven Checkstyle

              run: mvn checkstyle:checkstyle -pl tax -am -Dcheckstyle.output.file=tax-checkstyle-result.xml
            - name: Upload Checkstyle Result

              uses: jwgmeligmeyling/checkstyle-github-action@master
              with:
                  path: "**/tax-checkstyle-result.xml"
            - name: Test Results
              uses: dorny/test-reporter@v1
              if: ${{ (success() || failure()) }}
              with:
                  name: Tax-Service-Unit-Test-Results
                  path: "tax/**/*-reports/TEST*.xml"
                  reporter: java-junit
            - name: Analyze with sonar cloud

              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f tax

            - uses: snyk/actions/setup@master
            - name: Snyk test
              run: snyk test --file=tax/pom.xml --sarif-file-output=snyk.sarif --severity-threshold=high
              continue-on-error: true # To make sure that SARIF upload gets called
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            - name: Upload Snyk test result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: snyk.sarif

            - name: OWASP Dependency Check

              uses: dependency-check/Dependency-Check_Action@main
              env:
                  JAVA_HOME: /opt/jdk
              with:
                  project: "yas"
                  path: "."
                  format: "HTML"
            - name: Upload OWASP Dependency Check results

              uses: actions/upload-artifact@master
              with:
                  name: OWASP Dependency Check Report
                  path: ${{github.workspace}}/reports
            - name: Add coverage report to PR
              uses: madrapps/jacoco-report@v1.6.1

              with:
                  paths: ${{github.workspace}}/tax/target/site/jacoco/jacoco.xml
                  token: ${{secrets.GITHUB_TOKEN}}
                  min-coverage-overall: 70
                  min-coverage-changed-files: 70
                  title: "Tax Coverage Report"
                  update-comment: true
            - name: Log in to the Container registry
              if: ${{ github.ref == 'refs/heads/main' }}
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push Docker images
              if: ${{ github.ref == 'refs/heads/main' }}
              uses: docker/build-push-action@v6
              with:
                  context: ./tax
                  push: true
                  tags: ghcr.io/powerstomp/yas-tax:latest
