name: tax service ci

on:
  push:
    paths:
      - "tax/**"
  pull_request:
    paths:
      - "tax/**"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/java-service-ci-reusable.yml
    with:
      service: tax
      service_label: Tax
    secrets: inherit
