name: webhook service ci

on:
  push:
    branches: ["**"] # Xét trên tất cả các branch 
    paths: # Chỉ chạy nếu có sự thay đổi file ở các đường dẫn sau
      - "webhook/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/webhook-ci.yaml"
      - "pom.xml"
  pull_request:  
    branches: ["main"] # Chạy khi có pull_request vào nhánh main
    paths:
      - "webhook/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/webhook-ci.yaml"
      - "pom.xml"
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Kiểm tra xem code có phải từ repo gốc hay không
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:

      - uses: actions/checkout@v4 # Tải code về máy ảo
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      
      - name: Run Maven Test 
        # # Chạy các unit test đã cài đặt
        run: mvn -pl webhook -am verify
      
      - name: Install Dependencies 
        # Cài đặt các artifact vào kho lưu trữ cục bộ để các job sau có thể sử dụng
        run: mvn -pl webhook -am install -DskipTests 
      
      - name: Test Results
        uses: dorny/test-reporter@v1 # Báo cáo kết quả Test
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
        with:
          name: webhook-Service-Unit-Test-Results
          path: "webhook/**/*-reports/TEST*.xml"
          reporter: java-junit
      
      - name: Add coverage report to PR # Báo cáo độ bao phủ mã nguồn
        uses: madrapps/jacoco-report@v1.6.1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        with:
          paths: ${{github.workspace}}/webhook/target/site/jacoco/jacoco.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 70
          min-coverage-changed-files: 60
          title: 'webhook Coverage Report'
          update-comment: true
      
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4 # Đẩy file báo cáo dạng HTML lên GitHub
        with:
          name: webhook-coverage-report
          path: ${{github.workspace}}/webhook/target/site/jacoco/

  build:
    runs-on: ubuntu-latest
    needs: test # chỉ bắt đầu chạy sau khi Job test đã hoàn thành thành công
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      
      - name: Run Maven Build
        run: mvn -pl webhook -am -DskipTests install
      
      - name: Run Maven Checkstyle # Kiểm tra định dạng Code
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        run: mvn checkstyle:checkstyle -pl webhook -am -Dcheckstyle.output.file=webhook-checkstyle-result.xml
      
      - name: Upload Checkstyle Result
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/webhook-checkstyle-result.xml'
      
      
      - name: OWASP Dependency Check # Quét các lỗ hổng của thư viện
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'yas'
          path: '.'
          format: 'HTML'
          args: >
            --disableCentral
            --failOnCVSS 11

      - name: Upload OWASP Dependency Check results
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: actions/upload-artifact@master
        with:
          name: OWASP Dependency Check Report
          path: ${{github.workspace}}/reports
      
      - name: Analyze with sonar cloud # tìm bug tiềm ẩn và kiểm tra độ phủ của test.
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f webhook

      
      - name: Setup Snyk 
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: snyk/actions/setup@master
      
      - name: Run Snyk Scan # Quét chuyên sâu hơn về bảo mật mã nguồn (SQL Injection, Cross-Site Scripting,..)
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        continue-on-error: true # cho phép workflow tiếp tục chạy ngay cả khi Snyk phát hiện lỗi bảo mật
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test ./webhook --severity-threshold=medium --sarif-file-output=snyk-results.sarif

      
      - name: Upload Snyk results
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && !cancelled() && hashFiles('snyk-results.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-results.sarif
      
      - name: Log in to Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./webhook
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yas-webhook:latest