name: webhook service ci

on:
  push:
    branches: ["main"]
    paths:
      - "webhook/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/webhook-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: ["main"]
    paths:
      - "webhook/**"
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/webhook-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

env:
  FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks Scan
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  build:
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions
      - name: Run Maven Build Command
        run: mvn clean install -pl webhook -am
      
  test:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pull-requests: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Tests
        run: mvn clean verify -pl webhook -am
      - name: Test Results
        uses: dorny/test-reporter@v1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && (success() || failure()) }}
        with:
          name: Webhook-Service-Test-Results
          path: "webhook/**/*-reports/TEST*.xml"
          reporter: java-junit
      - name: Analyze with sonar cloud
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f webhook
          -Dsonar.projectKey=thanhdatttt_DevOps-Project
          -Dsonar.organization=thanhdatttt
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=$SONAR_TOKEN 
          -Dsonar.coverage.jacoco.xmlReportPaths=${{github.workspace}}/webhook/target/site/jacoco/jacoco.xml
      - name: Add coverage report to PR
        uses: madrapps/jacoco-report@v1.6.1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        with:
          paths: ${{github.workspace}}/webhook/target/site/jacoco/jacoco.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
          title: 'Webhook Coverage Report'
          update-comment: true
          
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
