---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-credentials-secret
  namespace: elasticsearch-dev
spec:
  encryptedData:
    users: AgBZe2dFkPsrMhvltavRo8iYvs9ISZhwRTW2oR2jIlkRiPptnQnc/pXt5NNB0aIrFCRxPqN+7yYUyZjx1Yrisici/5WtnQNa9TRiLj7Dkq1isF+qIWSpz0osQEpBjXNQsLKBcaANbqv2cd4dD65A6djZMM2/spbgtD4PNnu+TjvMA3AaWMNAbrNJhJ8M+qkx7Gm1pA5EfQF7U1GFU0Gau9L2zLkIpN+sRZToFAPBeNGDgXNMGWPlh2/bhY8cNUb35317DFgssqJM6yi/V+cS1f9oH3MhIQ9SXk+Xx54c/55BdSgE45FR8rjWAmsTD9l5ibI/eRkVAVV3WbqYXi90ex8Brn8BHdKjI2nsWAsBNzaX6qCmRQpktF3lgP0v+UYNfc5C7hlyDlyfwtlNsoJrpKEpG8Akp93+Kw9bTjw40adja0Y2fXKxb4GsNVOAwAx/wTEWmcs7yAyCrg4KAj1MVZF2t0G73/1Se9pyEOTV+kB07iAtXhnkoocMNBIDhpvMehcdb7LMD3GaZYLid3LjzurhWnNL9+20Vg08yZW7O2p4G1ASn6cg+LcDe32HSv5LTpqHp7c7eCkn92l9x3UVJQQ0hV7SA9+vyGxcWOYPvh8uQAddbAYfw9cBAeZcc9e0s4byZ1fKpW2pt3Tq+RTm/qxFlDSyfxpXMoqQpB5DFFrciPhzBSqgtWrfOrAPsw5XRdZ/KnOHdytT+/5/rVXIGMQiCP9gcByG1PBH802ftJ3HozKzTFkysXLSYPaM/aygQ44rxyadb0f5GrPXNT6P/9C9Ew==
    users_roles: AgAQq9oX60qtNml8XVi5nNlANZl2ceMxPVrICuDFCMbiYxIL7gapR9T4rRguh3XQP0mcXFizMYEtO9u0OYwonlvWcA4sajmvbMS7wsVd6vlAZ+knyByUCGCDe0y7dAdfJA6QfB39NKrIvzE4Qip7P5Fr0aD8LX99vKLUIctWeGhtbv2l0icOglJsGCJ6bb17kAAy7KRLfCpIDbe+rQHOx8vNMTe45sDH6K7VhYpU4CNPpGnn4UAKdJmBS0ZZ0gpmG2CyRuuEcD3e/tl1gkd7dwd/QLCE+JI0VEos4AIWYi+FlBTjQ55paXqF8qVpWLIUVe/ExTQh98EETQNawgxm7hqjUPIwWn9PFyGVeuLYWqRzbq5VqnJazr7XNG1bNmGcGlSPkuWyAhQSnppKLpxaDJ+BJzLYZhG9Sd8EjQSYguq4anvtFLhEPk4RWlFAG5tgbqpEs70Fsz+c58MMrk/CAa9iRrXIHA+8i4TCkjeGTkVj69dvtUkaH4HFX6he9mBkfHROtFDGDphN662NW0V3ykhX8AFzQUPnI8A+p8qZmKdFhYDeuVkQScdsDdKQmJyPKNBS5rDFaGZO88HymQVW96Ht+cZS8dGAbX5bsb2Zmd56J5c7CtcOEiDE/JjFeSH2M1QzgfFqJ23r7KmWaugSIGnAeduv4QeSnz+qgCUqDaJ6ULSVuh+P4Ofre9GeXGsqoUJiPpQADGj0CQZg9neadA==
  template:
    metadata:
      creationTimestamp: null
      name: user-credentials-secret
      namespace: elasticsearch-dev
    type: Opaque
