---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-credentials
  namespace: keycloak-dev
spec:
  encryptedData:
    password: AgCvJZhoT7V0Zb0N6Ol8UJjZVk2DMzjTKBaFqkq9dItX49DtBTlFymzQj26W0KnNaW2POuI48pibJXOC8GzSTcPHdmY4HUSEG493QPcURqGuvjUBOgvxzmMQS+1WHKwx+kXeCDSdHDrt6ZkeDXuxYUwru0BlDw3wPvmg8we1K1yyd2Y6SFw0+fEshvoktjqshudlL2at3rkuGrmVzhjqK1jRVBxt4IMi/enuWauEMfZzCZjP+Yv6FWl7iFan00Y+2VpzjkWRVGZJyzwMo15YHGCzoLaV+i8QvoNDsTdOQhSb2SZVeM6OoaPLtu+Y3DI23zglA+MKxe/5VgjTrQn1DMIxIACG9QcoQ6KhUm/T7liZZKtg9cIZ7X4MJtnjiRt+KIGD5Ynk2TmxfCqXEszf4Lss3tSZ4rnRTqrTnCalrjCt+r2FijHhgKrieFvSIwwoVI3MctIusrzBSZnhJRz8nHO4Kmp05nOorFEAcWPcNuu/+2hOpoxCtH6BZaDsgFX7qq7AXAk4bBNE64i0BuluYVBlID3tfyTfirg+6XdsvTNQJokCGIZoAmxVRZuv8g5j//OTNwOIViyyvcidZvcOVkseQA5a6RGKOY6+1dZY2dIH7eS0ygzvtVoosAM/NyM12mxLq9SrtV6MsysOicZ2Q1uOpFN1BckaEjzc7DMpLJhJcydXcXPCpKkir3Uo8c8qFk8LWCM2PA==
    username: AgAja5CB3c0Hrs86anxv95AH0QlLinW2XBrkSS2qpnyBUbLuMwXSPNxQCxn+82D/NTSy36ZrCPjvmFROBRkvkUHD8k7o110uIpuA7BIpaS3ioj0sxXfR4xKtD1t2V4val7OQUpOrcpyKl1s1+KwsOQ+l8ENmUKvgAUnK9nr1RKFhUmbaWoNYdRs5EKLYgz+27NXLpbAJKxjEMuCoOoBlfxNWTje5CtPKCpxfy/QESTTIdF/efhcKVKSNEeL2OtZYyjxSyhW3gvVMTFL5ZZq1N2rvUVu/eEK5+fpCv9kBujLVWZJnwpyFpKRc+lxfWdr2TzOmVKQzNpoMTexdueAmril4AbA7vmQhhOmTB9K5e6O46CGn+CGCN9Bta8lza/BKSx6rl/DSz/T4gp2KNCwz1oGroY9TI+SLyneRAmEMfLLtebZohzZ+ER/FKcBALC6FvwPhL9ZcsQbc7wrSayP7QFSWyS1rW2ZYuDDVALX/NdDrCLdg/w3AOT6hWZRDnpUTcf4o/yN/afsYv/pyipfsP3gGiQ516RykYvYQub7677QaPZTWTA2juqzh0KQVKbEsIUHjLhPeZgciNEp7wbhmltocmyw3kjlKyb5nb39TsgNOou7OdFpCc458TYH0LyjJqxq+p9peJOfgVQQpqSUv70cBTpep2R/XacOUxPzkr3GNla4GBvnxZ9hh8Tx08WgR7X9pe2ZOCA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-credentials
      namespace: keycloak-dev
    type: Opaque
