---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-credentials
  namespace: keycloak-dev
spec:
  encryptedData:
    password: AgAJid1orOTO/ujf0Vbv4GQ27MLWn3EoPVwsi/yeAAqGqZJq2vKHdnsVKVMmm4FDPXeL9fMN6luoYNW8c6FAEqfimrOGEYnxH0PMQSclRmVuuXyF1UEeN41RHZs1vH7CMhtI6e4UX7e3Y+/qfdTZOAw0uDHqmkdN8IDDlaVWxZLi9tS8B7poWHXqo+VZ5tDZ6bP0DCT58X4hr9EUw0+iOpX5K+bLCnu735fGx9pqUnkvcuJio0nNpkNHI6GxCdTv7Hfp8SD+Rwx8w3VPqbZjCuLDBBVK7//Ki3CHgq99Z9uh3STgiMk3AVYz7eBdEHDpx1yyLmfO7+0Cj4eLrIWFvEWtAUC4rGX7KxGf4O0LHaQKtYf9UR6TgFWFWaVN/Kq+mKFIybEmFrscIcOrwOjLTZwxYGW+e1+kIRD+k0vkZj3D+3X23OTn31pPrsm2hc9YK3C9QElbk7QZwhV7sraZ6io+gtqTrWUYwsUTMyFcS2msoqWSWN+FQnUSBEPquYec/pgCVSizClgXNRob4jdakPRSmILHJOOXd2svyA4PzUJKZuIXZss9WcwmmuasOIxpNYHrTOGakIIHWEYxw8vvcjxh6YqqQhoUQTQZgBdv31FjAbSys7a2JjsDDo52S8+zVddJ2cPUolHst1jNPnB+rTxFscoh+OcYoi2eR4F4Y3ZKPEMyY8FM3BnX2eaFFt6ktrGVwbXM5g==
    username: AgAQmojJcbtncgMjtQi5ZqFZFUXUQv4WIYOwyx/5g35yxcQ2nVn5by9026Sd1hBr8ghe+vZmoLR+DPs9zh2TzFp74S43Kq12zyN8SlqIQWOfODD7cfEbaZXH9pOQzSNyNS1G0aXBs49T7Kf6vmmiwIOowTeWTiPOVQmlCwEsp/R/inFzX829Ed55XMh/vjusXCnjOOJrHbR8dRp4VjKYkPlzlrAliJOB/qPrUSp4dShniGvfqf6WYHkXyxqn0X5Uvj5Fmkc35AuJZ9zzXheOx73Cu2NVT+ILKINOn4aKorWUV0+owW/0u2BcwZRpQIauLCDaROslYuyXCXTW8TQj8n6PKpXec5Zj4VRCnDnE3B4+Z3kiwtbpcE+xMxr8XP5NNkuwbEp6jwwIcEkIr9YdycbpkcqPez/vgafaZ0hvWo9b0MHt35cJhJC0tqcEgzHLNXSP7L9RBmsIih8NbXfkZ0KDtkebRXMlZxVmkBg6wO26b+2V8TRyDMRg/49kB7HI2eangBEiFFTi4pyJFFYqwdEhAOD20/zDwj6/18J0OvIi+iuCPxPaO83XoLqggrzjMt3xhD3SrpWIHE8nl7iLp7OPELUD8QJZwg18BXpHsuwYSTvddojBMw3AZ3S2HU6C6kdJqtESrKMgHDMJDQVtgrB+zA1mLF1EGICYiZKhb+m4Y8pXYlUM/tYxDLmYdXM0vprfWfr8uDCkKn+QPdI=
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-credentials
      namespace: keycloak-dev
    type: Opaque
