---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: yasadminuser.postgresql.credentials.postgresql.acid.zalan.do
  namespace: postgres-dev
spec:
  encryptedData:
    password: AgBL/HnQvgs60S9Vl5oCQ+//mzi49ayeQE30XAjkOJ1kj7NZkNsMLyavwwtT0bhCap9tSxUmIbNm42mV3bUepNCciRKtkTFyr9/QI85DC9O7iaZ2pyapJA1eOy5N0UpvUIfXeDVPJt5YQCE8cLWiVh0FYIzPiiuQGR2MszkrgDvy5U8ZfLQRsZRHRS4akumE7lTY9wSS62daZB3JLYFapEaLQDFngGRA3sMrlejwHywpSVlJGXQ9xI5rf1gvc0mUF2As0hdra88my0igUnBpMZlcjjuHTcASDTwByJtb+CbtJlenL3YccYI7KpeZVBYf5vbm7ChL8AnYwGLXptocYQrH6hk9vs38LxpxSbXP5r/+VuPQrfilmNIJ/9iqCvXnu33pIJO3mqYQg54JKUcl3TmN8aA+qZzkAOJ5gBYRZeMPZCGtt3ZMbsrHDPQ3+7EB+ko+4Uinf9LOWwMjiOscP64AL/dLukrsDuaA+tNXT7/+ZjqWpgCxmHVL1Be/mDYeMjM7Tpr0u8v7SszXhUXSAtnRx7t4RIUT6LqH28gjd8PFris/H3gFi8XEgVhMSZuGLSNLi+ArNqhq0p/95syFgRDPvCtxdS0uX7HK/2pq5ByH237cqyDSWLun48f4dQRHO8xCel16x7lCkdKDqE+J3btwkfLVF/zs+f8BgTK4RB2USESN1BSpzyqcEvuMSFMw1B4xzVdIoA==
    username: AgBs8P8DlHqY8T0q8IayborCdIvuoxAXvXee/3/MH5QQWHm945cw58IYmev/Tmt/Q0kRLNgO6XSeibGw5Nyl5xSYXURn0KzAOWzpvUyP1Jhc0c+jMKyPWLtQrUat8yAWRSFuq+OKkFF9tcDENksWi3uQHLPaW44CPOhFF5TJO1BzhzqBvIWlP0Wq0McPiYQ7Q7u0rxruKqY3B7VpKuzRH6jHmLk/UHDMlcTPVo+9c2DrPD4RN3pHup6gdVT844xWXHuCKptuvK17OPV9ptj202Tsl8zyrXmNkxHaHTv0pbhG5bh6G+fwkSap9cmKaUOzzytnawNFxu7YGAL/Fm3MKXabmoIzy7LGcv5SqwqqhRqiPBJuGJ0hZiu3Wntkdm36qEEq+0I8jYD0MGVw6a5lODEApWUwnfCQP/w/C6RUob6Z+/b2sCiW/rr0L/3RMFDF6sGuuEBRghTKk2qCK+4j1EMGk0mYufaDd1EHnD9lyrt9sSslp1SxS8mgn7OVLU/OvpWh+4oB1UXrgaqh3MQtOKBbAnIb2Rvu+Yj9IjJOTQeXo8A4sapaW6fHHBXAYPmJrwuWDBDKExSFyqBxfrbf9iqUaDItFvuebMnk2qLBRejKG6QmhcX8Uvw4zNncwg2lr6RHXr+vm6mjHLdANpS9ipdkQcN9RsyI7BQCJ+uzZrFpAXIQgMfmEFRAjxiRz8J5TGbQiph5aYQaXLgC/dQ=
  template:
    metadata:
      creationTimestamp: null
      name: yasadminuser.postgresql.credentials.postgresql.acid.zalan.do
      namespace: postgres-dev
    type: Opaque
