  elasticsearch.url=https://elasticsearch-es-http.elasticsearch.svc.cluster.local:9200
  elasticsearch.username=elastic
  elasticsearch.password=ZiG0P5GLgJgvtatjsazWAKY3

  server.port=8092
  server.servlet.context-path=/search


  spring.elasticsearch.uris.rest.connection-timeout=10

  spring.elasticsearch.uris=https://elasticsearch-es-http.elasticsearch.svc.cluster.local:9200
  spring.elasticsearch.username=elastic
  spring.elasticsearch.password=ZiG0P5GLgJgvtatjsazWAKY3
  spring.elasticsearch.restclient.ssl.verification-mode=none

  spring.application.name=search
  spring.threads.virtual.enabled=true
  management.tracing.sampling.probability=1.0
  management.endpoints.web.exposure.include=health,info,prometheus
  management.endpoint.health.show-details=always
  management.endpoint.health.probes.enabled=true
  management.metrics.distribution.percentiles-histogram.http.server.requests=true
  management.metrics.tags.application=${spring.application.name}

  logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

  spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak-service.keycloak.svc.cluster.local/realms/Yas

  # swagger-ui custom path
  springdoc.swagger-ui.path=/swagger-ui
  springdoc.packagesToScan=com.yas.search
  springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
  springdoc.swagger-ui.oauth.client-id=swagger-ui
  springdoc.oauthflow.authorization-url=http://keycloak-service.keycloak.svc.cluster.local/realms/Yas/protocol/openid-connect/auth
  springdoc.oauthflow.token-url=http://keycloak-service.keycloak.svc.cluster.local/realms/Yas/protocol/openid-connect/token

  yas.services.product=http://api.yas.local/product
  spring.kafka.consumer.bootstrap-servers=kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  spring.kafka.consumer.group-id=search
  product.topic.name=dbproduct.public.product

  spring.kafka.producer.bootstrap-servers=kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  spring.kafka.producer.key-serializer=org.springframework.kafka.support.serializer.JsonSerializer
  spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

