backend:
  replicaCount: 1
  image:
    repository: danzgne/yas-payment-paypal
    tag: main

  nameOverride: payment-paypal
  fullnameOverride: payment-paypal
  databaseName: payment-paypal
  ingress:
    enabled: false
  extraVolumes:
    - name: payment-paypal-application-config
      configMap:
        name: payment-paypal-application-configmap
  extraVolumeMounts:
    - name: payment-paypal-application-config
      mountPath: /opt/yas/payment-paypal
  extraApplicationConfigPaths:
    - /opt/yas/payment-paypal/payment-paypal-application.yaml